In [1]:
import math
import re
import warnings
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.tools.tools import add_constant
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import durbin_watson

from linearmodels import PanelOLS
from linearmodels.panel import compare

import geopandas as gpd
from libpysal.weights import Queen, lag_spatial
from esda.moran import Moran
from spreg import ML_Lag, ML_Error

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pre_ts_analysis = pd.read_csv('Research_Firearm/pre_ts_analysis_clean.csv')

In [3]:
pre_ts_analysis.columns

Index(['Year', 'Precinct', 'Full Time Positions', 'Budget', 'Borough',
       'MURDER & NON NEGL. MANSLAUGHTER', 'RAPE', 'ROBBERY', 'FELONY ASSAULT',
       'BURGLARY', 'GRAND LARCENY', 'GRAND LARCENY OF MOTOR VEHICLE',
       'TOTAL SEVEN MAJOR FELONY OFFENSES', 'Population_Year'],
      dtype='object')

In [4]:
precinct_counts = pre_ts_analysis['Precinct'].value_counts()
print(precinct_counts.to_string())

Precinct
1      18
68     18
94     18
90     18
88     18
84     18
83     18
81     18
79     18
78     18
77     18
76     18
75     18
73     18
72     18
71     18
70     18
100    18
101    18
102    18
111    18
122    18
120    18
115    18
114    18
113    18
112    18
110    18
103    18
109    18
108    18
107    18
106    18
105    18
104    18
69     18
67     18
5      18
66     18
32     18
30     18
28     18
26     18
25     18
24     18
23     18
20     18
19     18
17     18
13     18
10     18
9      18
7      18
6      18
33     18
34     18
40     18
49     18
63     18
62     18
61     18
60     18
52     18
50     18
48     18
41     18
47     18
46     18
45     18
44     18
43     18
42     18
123    18

In [5]:
pre_ts_analysis

,Year,Precinct,Full Time Positions,Budget,Borough,MURDER & NON NEGL. MANSLAUGHTER,RAPE,ROBBERY,FELONY ASSAULT,BURGLARY,GRAND LARCENY,GRAND LARCENY OF MOTOR VEHICLE,TOTAL SEVEN MAJOR FELONY OFFENSES,Population_Year
0,2006,1,219,11001943,MANHATTAN SOUTH,1,4,119,94,255,1462,78,2013,59431
1,2006,5,240,12354423,MANHATTAN SOUTH,2,5,132,104,152,605,40,1040,53356
2,2006,6,237,10716126,MANHATTAN SOUTH,3,6,214,123,280,1283,70,1979,61259
3,2006,7,174,7786080,MANHATTAN SOUTH,4,7,176,105,127,362,83,864,55703
4,2006,9,234,10190005,MANHATTAN SOUTH,1,14,252,165,297,775,75,1579,76639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1309,2023,114,252,20752787,QUEENS NORTH,8,40,279,509,224,920,430,2410,210231
1310,2023,115,289,16525730,QUEENS NORTH,4,27,365,481,136,863,337,2213,181382
1311,2023,120,399,29273345,STATEN ISLAND,12,19,163,470,142,414,156,1376,125104
1312,2023,122,249,19873478,STATEN ISLAND,2,8,50,169,100,474,109,912,146208
1313,2023,123,148,13394487,STATEN ISLAND,1,2,20,88,57,286,79,533,101539

In [6]:
# Filtering the DataFrame for precincts 6, 76, and 83
filtered_df = pre_ts_analysis[pre_ts_analysis['Precinct'].isin([6, 76, 83])]

# Grouping by 'Precinct' and 'Year' and counting occurrences
precinct_year_counts = filtered_df.groupby(['Precinct', 'Year']).size().reset_index(name='Count')

# Display the DataFrame
print(precinct_year_counts)

    Precinct  Year  Count
0          6  2006      1
1          6  2007      1
2          6  2008      1
3          6  2009      1
4          6  2010      1
5          6  2011      1
6          6  2012      1
7          6  2013      1
8          6  2014      1
9          6  2015      1
10         6  2016      1
11         6  2017      1
12         6  2018      1
13         6  2019      1
14         6  2020      1
15         6  2021      1
16         6  2022      1
17         6  2023      1
18        76  2006      1
19        76  2007      1
20        76  2008      1
21        76  2009      1
22        76  2010      1
23        76  2011      1
24        76  2012      1
25        76  2013      1
26        76  2014      1
27        76  2015      1
28        76  2016      1
29        76  2017      1
30        76  2018      1
31        76  2019      1
32        76  2020      1
33        76  2021      1
34        76  2022      1
35        76  2023      1
36        83  2006      1
37        83  2007      1
38        83  2008      1
39        83  2009      1
40        83  2010      1
41        83  2011      1
42        83  2012      1
43        83  2013      1
44        83  2014      1
45        83  2015      1
46        83  2016      1
47        83  2017      1
48        83  2018      1
49        83  2019      1
50        83  2020      1
51        83  2021      1
52        83  2022      1
53        83  2023      1

## Define Violent and Crime, also calculate the percentage based crime and budget allocation on precinct level

In [7]:
# Create 'Violent Crime' column
pre_ts_analysis['Violent Crime'] = pre_ts_analysis['FELONY ASSAULT'] + pre_ts_analysis['MURDER & NON NEGL. MANSLAUGHTER'] + pre_ts_analysis['RAPE'] + pre_ts_analysis['ROBBERY']
# Create 'Property Crime' column
pre_ts_analysis['Property Crime'] = pre_ts_analysis['GRAND LARCENY'] + pre_ts_analysis['GRAND LARCENY OF MOTOR VEHICLE'] + pre_ts_analysis['BURGLARY']

In [8]:
# Calculate yearly totals
yearly_totals = pre_ts_analysis.groupby('Year').sum().reset_index()
# List of metrics for which want to calculate yearly totals
metrics = ['Violent Crime', 'Property Crime', 'Full Time Positions']
# Rename columns to *_by_year
yearly_totals = yearly_totals.rename(columns={metric: f"{metric.lower()}_by_year" for metric in metrics})
# Merge yearly totals with merged_data
merged_data = pd.merge(pre_ts_analysis, yearly_totals[['Year'] + [f"{metric.lower()}_by_year" for metric in metrics]], 
                       on='Year', how='left')

# List of metrics for which to calculate yearly totals and per capita rates
metrics = ['Violent Crime', 'Property Crime','Full Time Positions']
# Loop through each metric
for metric in metrics:
    # Compute the per capita rate
    per_capita_col_name = f"{metric}_per_capita"
    merged_data[per_capita_col_name] = merged_data[metric] / merged_data['Population_Year']    
    # Compute the percentage-based rate
    pct_col_name = f"{metric}_pct"
    yearly_col_name = f"{metric.lower()}_by_year"
    merged_data[pct_col_name] = merged_data[metric] / merged_data[yearly_col_name]

In [9]:
pre_ts_analysis = merged_data

In [10]:
# Calculate yearly totals
yearly_totals = pre_ts_analysis.groupby('Year').sum().reset_index()
# List of metrics for which want to calculate yearly totals
metrics = ['MURDER & NON NEGL. MANSLAUGHTER', 'RAPE', 'ROBBERY', 'FELONY ASSAULT', 
    'BURGLARY', 'GRAND LARCENY', 'GRAND LARCENY OF MOTOR VEHICLE', 
    'TOTAL SEVEN MAJOR FELONY OFFENSES', 'Budget','Population_Year']
# Rename columns to *_by_year
yearly_totals = yearly_totals.rename(columns={metric: f"{metric.lower()}_by_year" for metric in metrics})
# Merge yearly totals with merged_data
merged_data = pd.merge(pre_ts_analysis, yearly_totals[['Year'] + [f"{metric.lower()}_by_year" for metric in metrics]], 
                       on='Year', how='left')

# List of metrics for which to calculate yearly totals and per capita rates
metrics = ['MURDER & NON NEGL. MANSLAUGHTER', 'RAPE', 'ROBBERY', 'FELONY ASSAULT', 
    'BURGLARY', 'GRAND LARCENY', 'GRAND LARCENY OF MOTOR VEHICLE', 
    'TOTAL SEVEN MAJOR FELONY OFFENSES', 'Budget','Population_Year']
# Loop through each metric
for metric in metrics:
    # Compute the per capita rate
    per_capita_col_name = f"{metric}_per_capita"
    merged_data[per_capita_col_name] = merged_data[metric] / merged_data['Population_Year']    
    # Compute the percentage-based rate
    pct_col_name = f"{metric}_pct"
    yearly_col_name = f"{metric.lower()}_by_year"
    merged_data[pct_col_name] = merged_data[metric] / merged_data[yearly_col_name]

In [11]:
pre_ts_analysis = merged_data

In [12]:
pre_ts_analysis['Population_Year_pct']

0       0.007676
1       0.006891
2       0.007912
3       0.007194
4       0.009898
          ...
1309    0.023993
1310    0.020700
1311    0.014278
1312    0.016686
1313    0.011588
Name: Population_Year_pct, Length: 1314, dtype: float64

In [13]:
pre_ts_analysis.groupby('Year')['Population_Year_pct'].sum()

Year
2006    1.0
2007    1.0
2008    1.0
2009    1.0
2010    1.0
2011    1.0
2012    1.0
2013    1.0
2014    1.0
2015    1.0
2016    1.0
2017    1.0
2018    1.0
2019    1.0
2020    1.0
2021    1.0
2022    1.0
2023    1.0
Name: Population_Year_pct, dtype: float64

## Create lag 1 for meature previous one year for crime and budget variable

In [14]:
# Get all columns ending with '_pct' or '_per_capita'
cols_to_lag = [col for col in pre_ts_analysis.columns if col.endswith('_pct') or col.endswith('_per_capita')]

# Loop through the columns and create a lag-1 column for each
for col in cols_to_lag:
    lag_col_name = col + '_lag1'  # Name of the new lag column
    pre_ts_analysis[lag_col_name] = pre_ts_analysis.groupby('Precinct')[col].shift(1)

In [15]:
pre_ts_analysis.columns

Index(['Year', 'Precinct', 'Full Time Positions', 'Budget', 'Borough',
       'MURDER & NON NEGL. MANSLAUGHTER', 'RAPE', 'ROBBERY', 'FELONY ASSAULT',
       'BURGLARY', 'GRAND LARCENY', 'GRAND LARCENY OF MOTOR VEHICLE',
       'TOTAL SEVEN MAJOR FELONY OFFENSES', 'Population_Year', 'Violent Crime',
       'Property Crime', 'violent crime_by_year', 'property crime_by_year',
       'full time positions_by_year', 'Violent Crime_per_capita',
       'Violent Crime_pct', 'Property Crime_per_capita', 'Property Crime_pct',
       'Full Time Positions_per_capita', 'Full Time Positions_pct',
       'murder & non negl. manslaughter_by_year', 'rape_by_year',
       'robbery_by_year', 'felony assault_by_year', 'burglary_by_year',
       'grand larceny_by_year', 'grand larceny of motor vehicle_by_year',
       'total seven major felony offenses_by_year', 'budget_by_year',
       'population_year_by_year', 'MURDER & NON NEGL. MANSLAUGHTER_per_capita',
       'MURDER & NON NEGL. MANSLAUGHTER_pct', 'RAPE_per_capita', 'RAPE_pct',
       'ROBBERY_per_capita', 'ROBBERY_pct', 'FELONY ASSAULT_per_capita',
       'FELONY ASSAULT_pct', 'BURGLARY_per_capita', 'BURGLARY_pct',
       'GRAND LARCENY_per_capita', 'GRAND LARCENY_pct',
       'GRAND LARCENY OF MOTOR VEHICLE_per_capita',
       'GRAND LARCENY OF MOTOR VEHICLE_pct',
       'TOTAL SEVEN MAJOR FELONY OFFENSES_per_capita',
       'TOTAL SEVEN MAJOR FELONY OFFENSES_pct', 'Budget_per_capita',
       'Budget_pct', 'Population_Year_per_capita', 'Population_Year_pct',
       'Violent Crime_per_capita_lag1', 'Violent Crime_pct_lag1',
       'Property Crime_per_capita_lag1', 'Property Crime_pct_lag1',
       'Full Time Positions_per_capita_lag1', 'Full Time Positions_pct_lag1',
       'MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1',
       'MURDER & NON NEGL. MANSLAUGHTER_pct_lag1', 'RAPE_per_capita_lag1',
       'RAPE_pct_lag1', 'ROBBERY_per_capita_lag1', 'ROBBERY_pct_lag1',
       'FELONY ASSAULT_per_capita_lag1', 'FELONY ASSAULT_pct_lag1',
       'BURGLARY_per_capita_lag1', 'BURGLARY_pct_lag1',
       'GRAND LARCENY_per_capita_lag1', 'GRAND LARCENY_pct_lag1',
       'GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1',
       'GRAND LARCENY OF MOTOR VEHICLE_pct_lag1',
       'TOTAL SEVEN MAJOR FELONY OFFENSES_per_capita_lag1',
       'TOTAL SEVEN MAJOR FELONY OFFENSES_pct_lag1', 'Budget_per_capita_lag1',
       'Budget_pct_lag1', 'Population_Year_per_capita_lag1',
       'Population_Year_pct_lag1'],
      dtype='object')

In [16]:
expanded_df_with_lags = pd.read_csv("expanded_df_with_lags_demo_06_23.csv")

In [17]:
expanded_df_with_lags

,precinct,Year,total_pop,minority_pct,per_capita_income_inflation_adjust,total_pop_lag1,minority_pct_lag1,per_capita_income_lag1
0,1,2006,83293.379121,0.267230,87482.282663,NaN,NaN,NaN
1,5,2006,93739.912088,0.384627,74453.142608,NaN,NaN,NaN
2,6,2006,70587.428571,0.190757,93954.047326,NaN,NaN,NaN
3,7,2006,88347.670330,0.404016,69879.516762,NaN,NaN,NaN
4,9,2006,112501.010989,0.247033,80506.118187,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1363,115,2023,2047.527473,0.513890,34558.424961,10033.153846,0.522893,33555.777314
1364,120,2023,4539.483516,0.077920,32880.827564,13677.076923,0.085590,32549.305142
1365,121,2023,-12066.340659,0.293450,31389.833940,-2129.153846,0.288328,31228.143323
1366,122,2023,-3587.186813,0.187455,42985.665619,6173.923077,0.181993,41685.091045
1367,123,2023,-5433.010989,0.245493,35143.468631,-952.923077,0.237874,34682.755284

In [18]:
expanded_df_with_lags.rename(columns={'precinct': 'Precinct'}, inplace=True)

In [19]:
# Step 1: Match dtypes for merge keys
expanded_df_with_lags['Year'] = pre_ts_analysis['Year'].dtype.type(expanded_df_with_lags['Year'])
expanded_df_with_lags['Precinct'] = pre_ts_analysis['Precinct'].dtype.type(expanded_df_with_lags['Precinct'])

# Step 2: Merge (left join to keep all rows from pre_ts_analysis)
pre_ts_analysis = pre_ts_analysis.merge(
    expanded_df_with_lags,
    how='left',
    on=['Year', 'Precinct']
)

print(pre_ts_analysis.head())

   Year  Precinct  Full Time Positions    Budget          Borough  \
0  2006         1                  219  11001943  MANHATTAN SOUTH
1  2006         5                  240  12354423  MANHATTAN SOUTH
2  2006         6                  237  10716126  MANHATTAN SOUTH
3  2006         7                  174   7786080  MANHATTAN SOUTH
4  2006         9                  234  10190005  MANHATTAN SOUTH

   MURDER & NON NEGL. MANSLAUGHTER  RAPE  ROBBERY  FELONY ASSAULT  BURGLARY  \
0                                1     4      119              94       255
1                                2     5      132             104       152
2                                3     6      214             123       280
3                                4     7      176             105       127
4                                1    14      252             165       297

   ...  Budget_per_capita_lag1  Budget_pct_lag1  \
0  ...                     NaN              NaN
1  ...                     NaN              NaN
2  ...                     NaN              NaN
3  ...                     NaN              NaN
4  ...                     NaN              NaN

   Population_Year_per_capita_lag1  Population_Year_pct_lag1      total_pop  \
0                              NaN                       NaN   83293.379121
1                              NaN                       NaN   93739.912088
2                              NaN                       NaN   70587.428571
3                              NaN                       NaN   88347.670330
4                              NaN                       NaN  112501.010989

   minority_pct  per_capita_income_inflation_adjust  total_pop_lag1  \
0      0.267230                        87482.282663             NaN
1      0.384627                        74453.142608             NaN
2      0.190757                        93954.047326             NaN
3      0.404016                        69879.516762             NaN
4      0.247033                        80506.118187             NaN

   minority_pct_lag1  per_capita_income_lag1
0                NaN                     NaN
1                NaN                     NaN
2                NaN                     NaN
3                NaN                     NaN
4                NaN                     NaN

[5 rows x 87 columns]

In [20]:
# Define updated regression formula
regression_formula = (
    "Budget_per_capita ~ Q('Violent Crime_per_capita_lag1') + "
    "Q('Property Crime_per_capita_lag1') + "
    "Budget_per_capita_lag1 + "
    "minority_pct_lag1 + "
    "per_capita_income_lag1 + "  
    "total_pop_lag1"
)

# Run the regression
model = smf.ols(formula=regression_formula, data=pre_ts_analysis).fit()

# Display summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     3309.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:07   Log-Likelihood:                -5053.5
No. Observations:                1224   AIC:                         1.012e+04
Df Residuals:                    1217   BIC:                         1.016e+04
Df Model:                           6
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                              12.3158      3.039      4.053      0.000       6.354      18.278
Q('Violent Crime_per_capita_lag1')   1313.9418    190.767      6.888      0.000     939.673    1688.210
Q('Property Crime_per_capita_lag1')   524.1690    138.415      3.787      0.000     252.611     795.727
Budget_per_capita_lag1                  0.9141      0.010     93.306      0.000       0.895       0.933
minority_pct_lag1                      -4.6539      3.138     -1.483      0.138     -10.811       1.503
per_capita_income_lag1              -4.735e-05   3.94e-05     -1.200      0.230      -0.000       3e-05
total_pop_lag1                        -2.8e-05   7.57e-06     -3.701      0.000   -4.28e-05   -1.32e-05
==============================================================================
Omnibus:                      681.673   Durbin-Watson:                   1.374
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            87626.683
Skew:                           1.569   Prob(JB):                         0.00
Kurtosis:                      44.332   Cond. No.                     6.50e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.5e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

In [21]:
cols = [
    'Budget_per_capita',
    'Violent Crime_per_capita_lag1',
    'Property Crime_per_capita_lag1',
    'Budget_per_capita_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]

df = pre_ts_analysis[cols].dropna().copy()

# Standardize predictors and outcome
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.drop(columns=['Budget_per_capita']))
y_scaled = scaler.fit_transform(df[['Budget_per_capita']])

# Convert back to DataFrame with same column names
X_scaled_df = pd.DataFrame(X_scaled, columns=df.columns[1:], index=df.index)
y_scaled_series = pd.Series(y_scaled.flatten(), name='Budget_per_capita', index=df.index)

# Add intercept
X_scaled_df = sm.add_constant(X_scaled_df)

# Fit standardized OLS model
model_std = sm.OLS(y_scaled_series, X_scaled_df).fit()

# Show results
print(model_std.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     3309.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:07   Log-Likelihood:                 8.2928
No. Observations:                1224   AIC:                            -2.586
Df Residuals:                    1217   BIC:                             33.18
Df Model:                           6
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                           2.637e-16      0.007   3.83e-14      1.000      -0.014       0.014
Violent Crime_per_capita_lag1      0.0622      0.009      6.888      0.000       0.045       0.080
Property Crime_per_capita_lag1     0.0308      0.008      3.787      0.000       0.015       0.047
Budget_per_capita_lag1             0.9154      0.010     93.306      0.000       0.896       0.935
minority_pct_lag1                 -0.0135      0.009     -1.483      0.138      -0.031       0.004
per_capita_income_lag1            -0.0112      0.009     -1.200      0.230      -0.029       0.007
total_pop_lag1                    -0.0276      0.007     -3.701      0.000      -0.042      -0.013
==============================================================================
Omnibus:                      681.673   Durbin-Watson:                   1.374
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            87626.683
Skew:                           1.569   Prob(JB):                         0.00
Kurtosis:                      44.332   Cond. No.                         2.79
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [22]:
cols = [
    'Precinct',                
    'Budget_per_capita',
    'Violent Crime_per_capita_lag1',
    'Property Crime_per_capita_lag1',
    'Budget_per_capita_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]

df = pre_ts_analysis[cols].dropna().copy()

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X = df.drop(columns=['Precinct', 'Budget_per_capita'])
y = df[['Budget_per_capita']]

X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y).ravel() 

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)
y_scaled_series = pd.Series(y_scaled, name='Budget_per_capita', index=df.index)

X_scaled_df = sm.add_constant(X_scaled_df)

model_std = sm.OLS(y_scaled_series, X_scaled_df).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']} 
)

print(model_std.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     4756.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.23e-90
Time:                        01:21:07   Log-Likelihood:                 8.2928
No. Observations:                1224   AIC:                            -2.586
Df Residuals:                    1217   BIC:                             33.18
Df Model:                           6
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                           2.637e-16      0.006   4.12e-14      1.000      -0.013       0.013
Violent Crime_per_capita_lag1      0.0622      0.012      5.112      0.000       0.038       0.086
Property Crime_per_capita_lag1     0.0308      0.010      3.157      0.002       0.012       0.050
Budget_per_capita_lag1             0.9154      0.021     44.353      0.000       0.875       0.956
minority_pct_lag1                 -0.0135      0.009     -1.512      0.130      -0.031       0.004
per_capita_income_lag1            -0.0112      0.007     -1.641      0.101      -0.025       0.002
total_pop_lag1                    -0.0276      0.008     -3.360      0.001      -0.044      -0.012
==============================================================================
Omnibus:                      681.673   Durbin-Watson:                   1.374
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            87626.683
Skew:                           1.569   Prob(JB):                         0.00
Kurtosis:                      44.332   Cond. No.                         2.79
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [23]:
cols = [
    "Budget_per_capita",
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[cols].dropna().copy()

# Standardize predictors (X) and target (y)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.drop(columns=["Budget_per_capita"]))
y_scaled = scaler.fit_transform(df[["Budget_per_capita"]])  # returns 2D array

# Convert to DataFrame and Series with proper labels
X_scaled_df = pd.DataFrame(X_scaled, columns=cols[1:], index=df.index)
y_scaled_series = pd.Series(y_scaled.flatten(), name="Budget_per_capita", index=df.index)

X_scaled_df = sm.add_constant(X_scaled_df)

# Fit the OLS regression with standardized variables
model_full_crime = sm.OLS(y_scaled_series, X_scaled_df).fit()

print(model_full_crime.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     1818.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:07   Log-Likelihood:                 15.035
No. Observations:                1224   AIC:                            -6.070
Df Residuals:                    1212   BIC:                             55.25
Df Model:                          11
Covariance Type:            nonrobust
===================================================================================================================
                                                      coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                            2.637e-16      0.007   3.84e-14      1.000      -0.013       0.013
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0193      0.011      1.800      0.072      -0.002       0.040
RAPE_per_capita_lag1                                0.0305      0.011      2.827      0.005       0.009       0.052
FELONY ASSAULT_per_capita_lag1                      0.0023      0.015      0.150      0.881      -0.028       0.032
BURGLARY_per_capita_lag1                            0.0044      0.011      0.407      0.684      -0.017       0.026
GRAND LARCENY_per_capita_lag1                       0.0335      0.011      3.103      0.002       0.012       0.055
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0052      0.009     -0.557      0.577      -0.023       0.013
ROBBERY_per_capita_lag1                             0.0340      0.016      2.173      0.030       0.003       0.065
Budget_per_capita_lag1                              0.9077      0.011     81.174      0.000       0.886       0.930
minority_pct_lag1                                  -0.0185      0.009     -1.959      0.050      -0.037    3.11e-05
per_capita_income_lag1                             -0.0136      0.011     -1.283      0.200      -0.034       0.007
total_pop_lag1                                     -0.0276      0.008     -3.673      0.000      -0.042      -0.013
==============================================================================
Omnibus:                      679.923   Durbin-Watson:                   1.398
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            90316.416
Skew:                           1.553   Prob(JB):                         0.00
Kurtosis:                      44.967   Cond. No.                         5.68
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [24]:
cols = [
    "Budget_per_capita",
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[["Precinct"] + cols].dropna().copy()

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X = df.drop(columns=["Precinct", "Budget_per_capita"])
y = df[["Budget_per_capita"]]

X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y).ravel()

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)
y_scaled_ser = pd.Series(y_scaled, name="Budget_per_capita", index=df.index)

# Add intercept
X_scaled_df = sm.add_constant(X_scaled_df)

res = sm.OLS(y_scaled_ser, X_scaled_df).fit(
    cov_type="cluster",
    cov_kwds={"groups": df["Precinct"]}
)

print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     3727.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.19e-93
Time:                        01:21:08   Log-Likelihood:                 15.035
No. Observations:                1224   AIC:                            -6.070
Df Residuals:                    1212   BIC:                             55.25
Df Model:                          11
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                            2.637e-16      0.007   3.98e-14      1.000      -0.013       0.013
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0193      0.008      2.566      0.010       0.005       0.034
RAPE_per_capita_lag1                                0.0305      0.012      2.623      0.009       0.008       0.053
FELONY ASSAULT_per_capita_lag1                      0.0023      0.019      0.121      0.904      -0.035       0.039
BURGLARY_per_capita_lag1                            0.0044      0.011      0.400      0.689      -0.017       0.026
GRAND LARCENY_per_capita_lag1                       0.0335      0.013      2.633      0.008       0.009       0.058
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0052      0.008     -0.626      0.531      -0.021       0.011
ROBBERY_per_capita_lag1                             0.0340      0.020      1.717      0.086      -0.005       0.073
Budget_per_capita_lag1                              0.9077      0.026     35.432      0.000       0.857       0.958
minority_pct_lag1                                  -0.0185      0.009     -2.134      0.033      -0.035      -0.002
per_capita_income_lag1                             -0.0136      0.007     -1.907      0.057      -0.028       0.000
total_pop_lag1                                     -0.0276      0.009     -3.111      0.002      -0.045      -0.010
==============================================================================
Omnibus:                      679.923   Durbin-Watson:                   1.398
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            90316.416
Skew:                           1.553   Prob(JB):                         0.00
Kurtosis:                      44.967   Cond. No.                         5.68
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [25]:
cols = [
    "Budget_per_capita",
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[["Precinct"] + cols].dropna().copy()

scaler_X = StandardScaler()
scaler_y = StandardScaler()

X = df.drop(columns=["Precinct", "Budget_per_capita"])
y = df[["Budget_per_capita"]]

X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y).ravel()

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)
y_scaled_ser = pd.Series(y_scaled, name="Budget_per_capita", index=df.index)

# Add intercept
X_scaled_df = sm.add_constant(X_scaled_df)

res = sm.OLS(y_scaled_ser, X_scaled_df).fit(
    cov_type="cluster",
    cov_kwds={"groups": df["Precinct"]}
)

print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     3699.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.88e-92
Time:                        01:21:08   Log-Likelihood:                 12.654
No. Observations:                1224   AIC:                            -3.309
Df Residuals:                    1213   BIC:                             52.90
Df Model:                          10
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                            2.637e-16      0.007    3.9e-14      1.000      -0.013       0.013
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0251      0.008      3.348      0.001       0.010       0.040
RAPE_per_capita_lag1                                0.0349      0.011      3.159      0.002       0.013       0.057
FELONY ASSAULT_per_capita_lag1                      0.0176      0.016      1.087      0.277      -0.014       0.049
BURGLARY_per_capita_lag1                            0.0122      0.010      1.234      0.217      -0.007       0.032
GRAND LARCENY_per_capita_lag1                       0.0378      0.013      3.018      0.003       0.013       0.062
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0023      0.008     -0.276      0.782      -0.019       0.014
Budget_per_capita_lag1                              0.9083      0.026     35.024      0.000       0.857       0.959
minority_pct_lag1                                  -0.0129      0.008     -1.516      0.130      -0.030       0.004
per_capita_income_lag1                             -0.0148      0.007     -2.073      0.038      -0.029      -0.001
total_pop_lag1                                     -0.0281      0.009     -3.230      0.001      -0.045      -0.011
==============================================================================
Omnibus:                      677.260   Durbin-Watson:                   1.393
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            89288.665
Skew:                           1.544   Prob(JB):                         0.00
Kurtosis:                      44.728   Cond. No.                         4.46
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [26]:
cols = [
    "Budget_per_capita",
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[cols].dropna().copy()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df.drop(columns=["Budget_per_capita"]))
y_scaled = scaler.fit_transform(df[["Budget_per_capita"]]) 

# Convert to DataFrame and Series with proper labels
X_scaled_df = pd.DataFrame(X_scaled, columns=cols[1:], index=df.index)
y_scaled_series = pd.Series(y_scaled.flatten(), name="Budget_per_capita", index=df.index)

X_scaled_df = sm.add_constant(X_scaled_df)

# Fit the OLS regression with standardized variables
model_full_crime = sm.OLS(y_scaled_series, X_scaled_df).fit()

print(model_full_crime.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     1994.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:08   Log-Likelihood:                 12.654
No. Observations:                1224   AIC:                            -3.309
Df Residuals:                    1213   BIC:                             52.90
Df Model:                          10
Covariance Type:            nonrobust
===================================================================================================================
                                                      coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                            2.637e-16      0.007   3.83e-14      1.000      -0.013       0.013
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0251      0.010      2.414      0.016       0.005       0.046
RAPE_per_capita_lag1                                0.0349      0.011      3.293      0.001       0.014       0.056
FELONY ASSAULT_per_capita_lag1                      0.0176      0.014      1.297      0.195      -0.009       0.044
BURGLARY_per_capita_lag1                            0.0122      0.010      1.183      0.237      -0.008       0.032
GRAND LARCENY_per_capita_lag1                       0.0378      0.011      3.554      0.000       0.017       0.059
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0023      0.009     -0.253      0.801      -0.020       0.016
Budget_per_capita_lag1                              0.9083      0.011     81.126      0.000       0.886       0.930
minority_pct_lag1                                  -0.0129      0.009     -1.416      0.157      -0.031       0.005
per_capita_income_lag1                             -0.0148      0.011     -1.397      0.163      -0.036       0.006
total_pop_lag1                                     -0.0281      0.008     -3.740      0.000      -0.043      -0.013
==============================================================================
Omnibus:                      677.260   Durbin-Watson:                   1.393
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            89288.665
Skew:                           1.544   Prob(JB):                         0.00
Kurtosis:                      44.728   Cond. No.                         4.46
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [27]:
X_vars = [
    'Violent Crime_pct_lag1',
    'Property Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

# Drop missing values
df = pre_ts_analysis[X_vars + [y_var]].dropna().copy()

# Standardize X
scaler = StandardScaler()
X_standardized = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Standardize y
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = (df[y_var] - y_mean) / y_std
y_standardized.index = df.index  # match index with X

# Add constant (intercept)
X_standardized = sm.add_constant(X_standardized)

# Fit the standardized OLS model
model_standardized = sm.OLS(y_standardized, X_standardized).fit()

# Print summary
print(model_standardized.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.909
Model:                            OLS   Adj. R-squared:                  0.909
Method:                 Least Squares   F-statistic:                     2038.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:08   Log-Likelihood:                -266.20
No. Observations:                1224   AIC:                             546.4
Df Residuals:                    1217   BIC:                             582.2
Df Model:                           6
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                    1.318e-16      0.009   1.53e-14      1.000      -0.017       0.017
Violent Crime_pct_lag1      0.0963      0.014      6.972      0.000       0.069       0.123
Property Crime_pct_lag1     0.0231      0.010      2.245      0.025       0.003       0.043
Budget_pct_lag1             0.8652      0.014     62.547      0.000       0.838       0.892
minority_pct_lag1          -0.0296      0.011     -2.653      0.008      -0.052      -0.008
per_capita_income_lag1     -0.0259      0.011     -2.288      0.022      -0.048      -0.004
total_pop_lag1             -0.0020      0.010     -0.201      0.841      -0.021       0.017
==============================================================================
Omnibus:                      638.893   Durbin-Watson:                   1.943
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           227150.288
Skew:                           1.129   Prob(JB):                         0.00
Kurtosis:                      69.700   Cond. No.                         3.29
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Paper Analysis

In [28]:
X_vars = [
    'Violent Crime_pct_lag1',
    'Property Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

df = pre_ts_analysis[X_vars + [y_var, 'Precinct']].dropna().copy()

# Standardize X
scaler = StandardScaler()
X_standardized = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Standardize y
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = (df[y_var] - y_mean) / y_std
y_standardized.index = df.index  

# Add constant (intercept)
X_standardized = sm.add_constant(X_standardized)

# Fit the model with clustered standard errors by precinct
model_clustered = sm.OLS(y_standardized, X_standardized).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Print the summary
print(model_clustered.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.909
Model:                            OLS   Adj. R-squared:                  0.909
Method:                 Least Squares   F-statistic:                     3348.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           5.54e-85
Time:                        01:21:08   Log-Likelihood:                -266.20
No. Observations:                1224   AIC:                             546.4
Df Residuals:                    1217   BIC:                             582.2
Df Model:                           6
Covariance Type:              cluster
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                    1.318e-16      0.008   1.56e-14      1.000      -0.017       0.017
Violent Crime_pct_lag1      0.0963      0.029      3.378      0.001       0.040       0.152
Property Crime_pct_lag1     0.0231      0.012      1.914      0.056      -0.001       0.047
Budget_pct_lag1             0.8652      0.042     20.480      0.000       0.782       0.948
minority_pct_lag1          -0.0296      0.015     -1.943      0.052      -0.060       0.000
per_capita_income_lag1     -0.0259      0.013     -1.946      0.052      -0.052       0.000
total_pop_lag1             -0.0020      0.009     -0.214      0.830      -0.020       0.016
==============================================================================
Omnibus:                      638.893   Durbin-Watson:                   1.943
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           227150.288
Skew:                           1.129   Prob(JB):                         0.00
Kurtosis:                      69.700   Cond. No.                         3.29
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [29]:
cols = [
    "Precinct", 
    "Budget_per_capita",
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[cols].dropna().copy()

# Save precincts for clustering
precinct_ids = df["Precinct"]

# Standardize predictors and response
X_vars = cols[2:] 
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[X_vars])
y_scaled = scaler.fit_transform(df[["Budget_per_capita"]])

X_scaled_df = pd.DataFrame(X_scaled, columns=X_vars, index=df.index)
y_scaled_series = pd.Series(y_scaled.flatten(), name="Budget_per_capita", index=df.index)

X_vif = X_scaled_df.copy()
vif_df = pd.DataFrame()
vif_df["Variable"] = X_vif.columns
vif_df["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]
print("=== VIF Results ===")
print(vif_df.sort_values("VIF", ascending=False))

# Add intercept
X_scaled_df = sm.add_constant(X_scaled_df)

# Fit model with clustering by precinct
model_clustered = sm.OLS(y_scaled_series, X_scaled_df).fit(
    cov_type="cluster",
    cov_kwds={"groups": precinct_ids}
)

print("\n=== Clustered Standard Errors OLS Summary ===")
print(model_clustered.summary())

=== VIF Results ===
                                           Variable       VIF
4                           ROBBERY_per_capita_lag1  5.188648
2                    FELONY ASSAULT_per_capita_lag1  4.921896
7                            Budget_per_capita_lag1  2.652618
3                          BURGLARY_per_capita_lag1  2.520715
1                              RAPE_per_capita_lag1  2.470722
5                     GRAND LARCENY_per_capita_lag1  2.468585
0   MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1  2.445818
9                            per_capita_income_lag1  2.380523
8                                 minority_pct_lag1  1.886324
6    GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1  1.843906
10                                   total_pop_lag1  1.193997

=== Clustered Standard Errors OLS Summary ===
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.943
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     3727.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.19e-93
Time:                        01:21:08   Log-Likelihood:                 15.035
No. Observations:                1224   AIC:                            -6.070
Df Residuals:                    1212   BIC:                             55.25
Df Model:                          11
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                            2.637e-16      0.007   3.98e-14      1.000      -0.013       0.013
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0193      0.008      2.566      0.010       0.005       0.034
RAPE_per_capita_lag1                                0.0305      0.012      2.623      0.009       0.008       0.053
FELONY ASSAULT_per_capita_lag1                      0.0023      0.019      0.121      0.904      -0.035       0.039
BURGLARY_per_capita_lag1                            0.0044      0.011      0.400      0.689      -0.017       0.026
ROBBERY_per_capita_lag1                             0.0340      0.020      1.717      0.086      -0.005       0.073
GRAND LARCENY_per_capita_lag1                       0.0335      0.013      2.633      0.008       0.009       0.058
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0052      0.008     -0.626      0.531      -0.021       0.011
Budget_per_capita_lag1                              0.9077      0.026     35.432      0.000       0.857       0.958
minority_pct_lag1                                  -0.0185      0.009     -2.134      0.033      -0.035      -0.002
per_capita_income_lag1                             -0.0136      0.007     -1.907      0.057      -0.028       0.000
total_pop_lag1                                     -0.0276      0.009     -3.111      0.002      -0.045      -0.010
==============================================================================
Omnibus:                      679.923   Durbin-Watson:                   1.398
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            90316.416
Skew:                           1.553   Prob(JB):                         0.00
Kurtosis:                      44.967   Cond. No.                         5.68
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [30]:
cols = [
    "Precinct", 
    "Budget_per_capita",
    'Violent Crime_per_capita_lag1',
    'Property Crime_per_capita_lag1',
    'Budget_per_capita_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]

df = pre_ts_analysis[cols].dropna().copy()

precinct_ids = df["Precinct"]

# Standardize predictors and response
X_vars = cols[2:]  
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[X_vars])
y_scaled = scaler.fit_transform(df[["Budget_per_capita"]])

X_scaled_df = pd.DataFrame(X_scaled, columns=X_vars, index=df.index)
y_scaled_series = pd.Series(y_scaled.flatten(), name="Budget_per_capita", index=df.index)

X_vif = X_scaled_df.copy()
vif_df = pd.DataFrame()
vif_df["Variable"] = X_vif.columns
vif_df["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]
print("=== VIF Results ===")
print(vif_df.sort_values("VIF", ascending=False))

X_scaled_df = sm.add_constant(X_scaled_df)

model_clustered = sm.OLS(y_scaled_series, X_scaled_df).fit(
    cov_type="cluster",
    cov_kwds={"groups": precinct_ids}
)

print("\n=== Clustered Standard Errors OLS Summary ===")
print(model_clustered.summary())

=== VIF Results ===
                         Variable       VIF
2          Budget_per_capita_lag1  2.027871
4          per_capita_income_lag1  1.833138
3               minority_pct_lag1  1.737612
0   Violent Crime_per_capita_lag1  1.720789
1  Property Crime_per_capita_lag1  1.393977
5                  total_pop_lag1  1.174885

=== Clustered Standard Errors OLS Summary ===
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     4756.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.23e-90
Time:                        01:21:08   Log-Likelihood:                 8.2928
No. Observations:                1224   AIC:                            -2.586
Df Residuals:                    1217   BIC:                             33.18
Df Model:                           6
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                           2.637e-16      0.006   4.12e-14      1.000      -0.013       0.013
Violent Crime_per_capita_lag1      0.0622      0.012      5.112      0.000       0.038       0.086
Property Crime_per_capita_lag1     0.0308      0.010      3.157      0.002       0.012       0.050
Budget_per_capita_lag1             0.9154      0.021     44.353      0.000       0.875       0.956
minority_pct_lag1                 -0.0135      0.009     -1.512      0.130      -0.031       0.004
per_capita_income_lag1            -0.0112      0.007     -1.641      0.101      -0.025       0.002
total_pop_lag1                    -0.0276      0.008     -3.360      0.001      -0.044      -0.012
==============================================================================
Omnibus:                      681.673   Durbin-Watson:                   1.374
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            87626.683
Skew:                           1.569   Prob(JB):                         0.00
Kurtosis:                      44.332   Cond. No.                         2.79
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [31]:
cols = [
    "Precinct",  # for clustering
    "Budget_per_capita",
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[cols].dropna().copy()

# Cluster IDs
precinct_ids = df["Precinct"]


X_vars = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var = "Budget_per_capita"

# Standardize X
x_scaler = StandardScaler()
X_scaled = x_scaler.fit_transform(df[X_vars])
X_scaled_df = pd.DataFrame(X_scaled, columns=X_vars, index=df.index)

# Standardize y (mean/std)
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = ((df[y_var] - y_mean) / y_std).astype(float)
y_standardized.index = df.index


X_for_vif = X_scaled_df.copy()
vif_df = pd.DataFrame({
    "Variable": X_for_vif.columns,
    "VIF": [variance_inflation_factor(X_for_vif.values, i) for i in range(X_for_vif.shape[1])]
}).sort_values("VIF", ascending=False)

print("=== VIF Results (no FE) ===")
print(vif_df)


X_design = sm.add_constant(X_scaled_df).astype(float)

model_clustered_nofe = sm.OLS(y_standardized, X_design).fit(
    cov_type="cluster",
    cov_kwds={"groups": precinct_ids}
)

print("\n=== Clustered SE OLS (No Fixed Effects) ===")
print(model_clustered_nofe.summary())

=== VIF Results (no FE) ===
                         Variable       VIF
2          Budget_per_capita_lag1  2.027871
4          per_capita_income_lag1  1.833138
3               minority_pct_lag1  1.737612
0   Violent Crime_per_capita_lag1  1.720789
1  Property Crime_per_capita_lag1  1.393977
5                  total_pop_lag1  1.174885

=== Clustered SE OLS (No Fixed Effects) ===
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.942
Model:                            OLS   Adj. R-squared:                  0.942
Method:                 Least Squares   F-statistic:                     4756.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.23e-90
Time:                        01:21:09   Log-Likelihood:                 8.7930
No. Observations:                1224   AIC:                            -3.586
Df Residuals:                    1217   BIC:                             32.18
Df Model:                           6
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                           2.706e-16      0.006   4.23e-14      1.000      -0.013       0.013
Violent Crime_per_capita_lag1      0.0622      0.012      5.112      0.000       0.038       0.086
Property Crime_per_capita_lag1     0.0308      0.010      3.157      0.002       0.012       0.050
Budget_per_capita_lag1             0.9150      0.021     44.353      0.000       0.875       0.955
minority_pct_lag1                 -0.0135      0.009     -1.512      0.130      -0.031       0.004
per_capita_income_lag1            -0.0112      0.007     -1.641      0.101      -0.025       0.002
total_pop_lag1                    -0.0276      0.008     -3.360      0.001      -0.044      -0.012
==============================================================================
Omnibus:                      681.673   Durbin-Watson:                   1.374
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            87626.683
Skew:                           1.569   Prob(JB):                         0.00
Kurtosis:                      44.332   Cond. No.                         2.79
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [32]:
cols = [
    "Precinct",
    "Year",
    "Budget_per_capita",
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]

df = pre_ts_analysis[cols].dropna().copy()

# Save for clustering
precinct_ids = df["Precinct"]

# Year fixed effects (one-way FE)
year_dummies = pd.get_dummies(df["Year"], prefix="Year", drop_first=True, dtype=float)


X_vars = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var = "Budget_per_capita"

x_scaler = StandardScaler()
X_scaled = x_scaler.fit_transform(df[X_vars])
X_scaled_df = pd.DataFrame(X_scaled, columns=X_vars, index=df.index)

y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = ((df[y_var] - y_mean) / y_std).astype(float)
y_standardized.index = df.index

# Combine standardized X with year FE
X_combined = pd.concat([X_scaled_df, year_dummies], axis=1)


X_for_vif = X_scaled_df.copy()
vif_df = pd.DataFrame({
    "Variable": X_for_vif.columns,
    "VIF": [variance_inflation_factor(X_for_vif.values, i) for i in range(X_for_vif.shape[1])]
}).sort_values("VIF", ascending=False)

print("=== VIF Results (core predictors only; FE excluded) ===")
print(vif_df)

X_combined = sm.add_constant(X_combined).astype(float)

model_clustered_timefe = sm.OLS(y_standardized, X_combined).fit(
    cov_type="cluster",
    cov_kwds={"groups": precinct_ids}
)

print("\n=== Clustered SE OLS with Year FE ===")
print(model_clustered_timefe.summary())

=== VIF Results (core predictors only; FE excluded) ===
                         Variable       VIF
2          Budget_per_capita_lag1  2.027871
4          per_capita_income_lag1  1.833138
3               minority_pct_lag1  1.737612
0   Violent Crime_per_capita_lag1  1.720789
1  Property Crime_per_capita_lag1  1.393977
5                  total_pop_lag1  1.174885

=== Clustered SE OLS with Year FE ===
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.956
Method:                 Least Squares   F-statistic:                     7160.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):          5.78e-110
Time:                        01:21:09   Log-Likelihood:                 191.53
No. Observations:                1224   AIC:                            -337.1
Df Residuals:                    1201   BIC:                            -219.5
Df Model:                          22
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              0.1682      0.043      3.894      0.000       0.084       0.253
Violent Crime_per_capita_lag1      0.0477      0.016      3.040      0.002       0.017       0.078
Property Crime_per_capita_lag1     0.0170      0.012      1.388      0.165      -0.007       0.041
Budget_per_capita_lag1             0.9423      0.027     34.580      0.000       0.889       0.996
minority_pct_lag1                 -0.0134      0.008     -1.785      0.074      -0.028       0.001
per_capita_income_lag1            -0.0064      0.006     -1.124      0.261      -0.018       0.005
total_pop_lag1                    -0.0210      0.008     -2.554      0.011      -0.037      -0.005
Year_2008                         -0.2032      0.040     -5.108      0.000      -0.281      -0.125
Year_2009                         -0.2599      0.037     -7.011      0.000      -0.333      -0.187
Year_2010                         -0.2024      0.072     -2.800      0.005      -0.344      -0.061
Year_2011                          0.2002      0.050      3.968      0.000       0.101       0.299
Year_2012                         -0.3792      0.055     -6.876      0.000      -0.487      -0.271
Year_2013                         -0.1103      0.058     -1.918      0.055      -0.223       0.002
Year_2014                         -0.2312      0.041     -5.570      0.000      -0.312      -0.150
Year_2015                         -0.2381      0.049     -4.886      0.000      -0.334      -0.143
Year_2016                         -0.2002      0.049     -4.045      0.000      -0.297      -0.103
Year_2017                         -0.1487      0.049     -3.026      0.002      -0.245      -0.052
Year_2018                         -0.0407      0.052     -0.776      0.438      -0.143       0.062
Year_2019                         -0.2242      0.053     -4.269      0.000      -0.327      -0.121
Year_2020                         -0.2075      0.053     -3.884      0.000      -0.312      -0.103
Year_2021                         -0.2562      0.054     -4.765      0.000      -0.362      -0.151
Year_2022                         -0.1788      0.049     -3.686      0.000      -0.274      -0.084
Year_2023                         -0.1790      0.043     -4.160      0.000      -0.263      -0.095
==============================================================================
Omnibus:                      506.403   Durbin-Watson:                   1.877
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           463430.077
Skew:                           0.156   Prob(JB):                         0.00
Kurtosis:                      98.325   Cond. No.                         28.2
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [33]:
X_vars = [
    'Violent Crime_pct_lag1',
    'Property Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create year dummies and ensure numeric dtype
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
df = pd.concat([df, year_dummies], axis=1)

# Standardize main X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors with year dummies
X_combined = pd.concat([X_base, year_dummies], axis=1)

# Standardize the outcome variable
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = ((df[y_var] - y_mean) / y_std).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Force all data to float64
X_combined = X_combined.astype(float)

# Fit OLS with clustered SEs by precinct
model_clustered_timefe = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Display results
print(model_clustered_timefe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.910
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1367.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           1.81e-84
Time:                        01:21:09   Log-Likelihood:                -265.84
No. Observations:                1224   AIC:                             577.7
Df Residuals:                    1201   BIC:                             695.2
Df Model:                          22
Covariance Type:              cluster
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0121      0.062      0.196      0.845      -0.109       0.133
Violent Crime_pct_lag1      0.0973      0.029      3.325      0.001       0.040       0.155
Property Crime_pct_lag1     0.0232      0.012      1.885      0.059      -0.001       0.047
Budget_pct_lag1             0.8643      0.043     20.056      0.000       0.780       0.949
minority_pct_lag1          -0.0323      0.017     -1.863      0.062      -0.066       0.002
per_capita_income_lag1     -0.0255      0.013     -1.939      0.052      -0.051       0.000
total_pop_lag1             -0.0022      0.009     -0.240      0.810      -0.020       0.016
Year_2008                  -0.0008      0.061     -0.014      0.989      -0.121       0.119
Year_2009                  -0.0031      0.054     -0.056      0.955      -0.109       0.103
Year_2010                  -0.0035      0.083     -0.042      0.967      -0.167       0.160
Year_2011                  -0.0070      0.095     -0.074      0.941      -0.194       0.180
Year_2012                  -0.0059      0.076     -0.078      0.938      -0.155       0.143
Year_2013                  -0.0141      0.084     -0.168      0.866      -0.179       0.151
Year_2014                  -0.0064      0.068     -0.095      0.925      -0.139       0.126
Year_2015                  -0.0127      0.068     -0.186      0.853      -0.146       0.121
Year_2016                  -0.0139      0.072     -0.194      0.846      -0.155       0.127
Year_2017                  -0.0242      0.055     -0.437      0.662      -0.133       0.084
Year_2018                  -0.0139      0.066     -0.210      0.834      -0.143       0.116
Year_2019                  -0.0149      0.063     -0.236      0.814      -0.139       0.109
Year_2020                  -0.0195      0.063     -0.309      0.757      -0.143       0.104
Year_2021                  -0.0200      0.062     -0.321      0.748      -0.142       0.102
Year_2022                  -0.0234      0.065     -0.361      0.718      -0.150       0.103
Year_2023                  -0.0224      0.064     -0.348      0.728      -0.148       0.104
==============================================================================
Omnibus:                      630.243   Durbin-Watson:                   1.944
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           225605.647
Skew:                           1.093   Prob(JB):                         0.00
Kurtosis:                      69.475   Cond. No.                         27.1
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [34]:
X_vars = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var = 'Budget_per_capita'

# Load relevant data and drop missing
required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create year dummies and ensure numeric dtype
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
df = pd.concat([df, year_dummies], axis=1)

# Standardize main X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors with year dummies
X_combined = pd.concat([X_base, year_dummies], axis=1)

# Standardize the outcome variable
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = ((df[y_var] - y_mean) / y_std).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Force all data to float64
X_combined = X_combined.astype(float)

# Fit OLS with clustered SEs by precinct
model_clustered_timefe = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Display results
print(model_clustered_timefe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     5855.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):          1.66e-108
Time:                        01:21:09   Log-Likelihood:                 197.03
No. Observations:                1224   AIC:                            -338.1
Df Residuals:                    1196   BIC:                            -195.0
Df Model:                          27
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                               0.1797      0.042      4.271      0.000       0.097       0.262
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0072      0.007      1.091      0.275      -0.006       0.020
RAPE_per_capita_lag1                                0.0259      0.010      2.710      0.007       0.007       0.045
FELONY ASSAULT_per_capita_lag1                      0.0192      0.016      1.174      0.241      -0.013       0.051
BURGLARY_per_capita_lag1                            0.0064      0.010      0.636      0.525      -0.013       0.026
GRAND LARCENY_per_capita_lag1                       0.0208      0.012      1.710      0.087      -0.003       0.045
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0140      0.008     -1.659      0.097      -0.031       0.003
ROBBERY_per_capita_lag1                             0.0131      0.020      0.664      0.507      -0.026       0.052
Budget_per_capita_lag1                              0.9334      0.029     31.814      0.000       0.876       0.991
minority_pct_lag1                                  -0.0151      0.007     -2.045      0.041      -0.030      -0.001
per_capita_income_lag1                             -0.0111      0.006     -1.806      0.071      -0.023       0.001
total_pop_lag1                                     -0.0205      0.008     -2.484      0.013      -0.037      -0.004
Year_2008                                          -0.2018      0.039     -5.113      0.000      -0.279      -0.124
Year_2009                                          -0.2595      0.038     -6.915      0.000      -0.333      -0.186
Year_2010                                          -0.2065      0.069     -2.994      0.003      -0.342      -0.071
Year_2011                                           0.1900      0.053      3.567      0.000       0.086       0.294
Year_2012                                          -0.3898      0.053     -7.304      0.000      -0.494      -0.285
Year_2013                                          -0.1258      0.056     -2.257      0.024      -0.235      -0.017
Year_2014                                          -0.2435      0.043     -5.712      0.000      -0.327      -0.160
Year_2015                                          -0.2514      0.048     -5.269      0.000      -0.345      -0.158
Year_2016                                          -0.2168      0.048     -4.513      0.000      -0.311      -0.123
Year_2017                                          -0.1679      0.047     -3.552      0.000      -0.261      -0.075
Year_2018                                          -0.0617      0.051     -1.203      0.229      -0.162       0.039
Year_2019                                          -0.2558      0.049     -5.226      0.000      -0.352      -0.160
Year_2020                                          -0.2343      0.051     -4.613      0.000      -0.334      -0.135
Year_2021                                          -0.2662      0.052     -5.071      0.000      -0.369      -0.163
Year_2022                                          -0.1860      0.046     -4.027      0.000      -0.277      -0.095
Year_2023                                          -0.1773      0.043     -4.099      0.000      -0.262      -0.093
==============================================================================
Omnibus:                      512.201   Durbin-Watson:                   1.885
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           467461.918
Skew:                           0.226   Prob(JB):                         0.00
Kurtosis:                      98.738   Cond. No.                         42.8
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [35]:
X_vars = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"

]
y_var = 'Budget_per_capita'

# Ensure required columns are present
required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create Year and Precinct dummies
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
precinct_dummies = pd.get_dummies(df['Precinct'], prefix='Precinct', drop_first=True, dtype=float)

# Standardize X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors + year dummies + precinct dummies
X_combined = pd.concat([X_base, year_dummies, precinct_dummies], axis=1)

# Standardize y
y_standardized = ((df[y_var] - df[y_var].mean()) / df[y_var].std()).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Ensure all are float type
X_combined = X_combined.astype(float)

# Fit model with **clustered SEs by precinct**
model_fe_both = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Print results
print(model_fe_both.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.965
Method:                 Least Squares   F-statistic:                     50.81
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.35e-36
Time:                        01:21:10   Log-Likelihood:                 359.35
No. Observations:                1224   AIC:                            -520.7
Df Residuals:                    1125   BIC:                            -14.83
Df Model:                          98
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                               0.1592      0.093      1.709      0.087      -0.023       0.342
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0033      0.008      0.433      0.665      -0.012       0.018
RAPE_per_capita_lag1                                0.0285      0.011      2.546      0.011       0.007       0.050
FELONY ASSAULT_per_capita_lag1                      0.0325      0.016      1.982      0.047       0.000       0.065
BURGLARY_per_capita_lag1                            0.0085      0.014      0.589      0.556      -0.020       0.037
GRAND LARCENY_per_capita_lag1                       0.0901      0.032      2.850      0.004       0.028       0.152
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1      0.0127      0.015      0.840      0.401      -0.017       0.042
ROBBERY_per_capita_lag1                            -0.0135      0.031     -0.435      0.664      -0.074       0.047
Budget_per_capita_lag1                              0.5299      0.104      5.094      0.000       0.326       0.734
minority_pct_lag1                                  -0.0016      0.018     -0.085      0.932      -0.037       0.034
per_capita_income_lag1                              0.0027      0.022      0.124      0.901      -0.040       0.045
total_pop_lag1                                     -0.0089      0.014     -0.634      0.526      -0.036       0.019
Year_2008                                          -0.0785      0.046     -1.704      0.088      -0.169       0.012
Year_2009                                          -0.1087      0.050     -2.167      0.030      -0.207      -0.010
Year_2010                                          -0.0518      0.094     -0.551      0.582      -0.236       0.132
Year_2011                                           0.3649      0.052      7.058      0.000       0.264       0.466
Year_2012                                          -0.0396      0.105     -0.376      0.707      -0.246       0.167
Year_2013                                           0.1484      0.101      1.472      0.141      -0.049       0.346
Year_2014                                           0.0663      0.092      0.719      0.472      -0.115       0.247
Year_2015                                           0.0517      0.093      0.553      0.580      -0.131       0.235
Year_2016                                           0.0752      0.092      0.817      0.414      -0.105       0.256
Year_2017                                           0.1299      0.096      1.359      0.174      -0.057       0.317
Year_2018                                           0.2616      0.099      2.641      0.008       0.067       0.456
Year_2019                                           0.1259      0.111      1.133      0.257      -0.092       0.344
Year_2020                                           0.1355      0.110      1.235      0.217      -0.080       0.351
Year_2021                                           0.0988      0.103      0.963      0.336      -0.102       0.300
Year_2022                                           0.1341      0.093      1.445      0.148      -0.048       0.316
Year_2023                                           0.1136      0.083      1.365      0.172      -0.049       0.277
Precinct_5                                          0.1197      0.053      2.264      0.024       0.016       0.223
Precinct_6                                         -0.1445      0.051     -2.831      0.005      -0.245      -0.044
Precinct_7                                          0.1208      0.067      1.800      0.072      -0.011       0.252
Precinct_9                                         -0.2980      0.072     -4.125      0.000      -0.440      -0.156
Precinct_10                                        -0.0424      0.021     -2.022      0.043      -0.084      -0.001
Precinct_13                                        -0.5291      0.121     -4.370      0.000      -0.766      -0.292
Precinct_17                                        -0.3831      0.112     -3.425      0.001      -0.602      -0.164
Precinct_19                                        -0.8107      0.204     -3.982      0.000      -1.210      -0.412
Precinct_20                                        -0.5726      0.149     -3.841      0.000      -0.865      -0.280
Precinct_23                                         0.0345      0.091      0.377      0.706      -0.145       0.214
Precinct_24                                        -0.5056      0.133     -3.791      0.000      -0.767      -0.244
Precinct_25                                         0.5779      0.194      2.984      0.003       0.198       0.957
Precinct_26                                         0.3278      0.104      3.153      0.002       0.124       0.531
Precinct_28                                         0.7485      0.210      3.565      0.000       0.337       1.160
Precinct_30                                         0.2702      0.122      2.221      0.026       0.032       0.509
Precinct_32                                         0.1342      0.119      1.132      0.258      -0.098       0.367
Precinct_33                                         0.1014      0.100      1.013      0.311      -0.095       0.298
Precinct_34                                        -0.3422      0.109     -3.136      0.002      -0.556      -0.128
Precinct_40                                         0.0108      0.097      0.111      0.912      -0.180       0.201
Precinct_41                                         0.4072      0.164      2.477      0.013       0.085       0.729
Precinct_42                                        -0.1556      0.092     -1.698      0.090      -0.335       0.024
Precinct_43                                        -0.5588      0.129     -4.336      0.000      -0.811      -0.306
Precinct_44                                        -0.2267      0.090     -2.508      0.012      -0.404      -0.050
Precinct_45                                        -0.5330      0.150     -3.562      0.000      -0.826      -0.240
Precinct_46                                        -0.1849      0.091     -2.025      0.043      -0.364      -0.006
Precinct_47                                        -0.5169      0.140     -3.695      0.000      -0.791      -0.243
Precinct_48                                        -0.0151      0.087     -0.174      0.862      -0.185       0.155
Precinct_49                                        -0.3981      0.120     -3.327      0.001      -0.633      -0.164
Precinct_50                                        -0.4525      0.133     -3.404      0.001      -0.713      -0.192
Precinct_52                                        -0.4257      0.109     -3.898      0.000      -0.640      -0.212
Precinct_60                                        -0.3095      0.100     -3.111      0.002      -0.505      -0.115
Precinct_61                                        -0.7402      0.195     -3.797      0.000      -1.122      -0.358
Precinct_62                                        -0.7942      0.193     -4.125      0.000      -1.172      -0.417
Precinct_63                                        -0.5383      0.139     -3.876      0.000      -0.811      -0.266
Precinct_66                                        -0.7876      0.196     -4.020      0.000      -1.172      -0.404
Precinct_67                                        -0.4027      0.115     -3.488      0.000      -0.629      -0.176
Precinct_68                                        -0.6555      0.172     -3.804      0.000      -0.993      -0.318
Precinct_69                                        -0.3219      0.105     -3.062      0.002      -0.528      -0.116
Precinct_70                                        -0.4283      0.115     -3.719      0.000      -0.654      -0.203
Precinct_71                                        -0.1685      0.083     -2.037      0.042      -0.331      -0.006
Precinct_72                                        -0.5678      0.144     -3.940      0.000      -0.850      -0.285
Precinct_73                                         0.2034      0.141      1.447      0.148      -0.072       0.479
Precinct_75                                        -0.3553      0.093     -3.804      0.000      -0.538      -0.172
Precinct_76                                         0.4033      0.113      3.571      0.000       0.182       0.625
Precinct_77                                         0.0166      0.091      0.182      0.855      -0.162       0.195
Precinct_78                                        -0.0429      0.060     -0.716      0.474      -0.160       0.075
Precinct_79                                        -0.0072      0.092     -0.078      0.938      -0.188       0.173
Precinct_81                                         0.2312      0.117      1.981      0.048       0.002       0.460
Precinct_83                                        -0.3449      0.098     -3.511      0.000      -0.537      -0.152
Precinct_84                                         0.7560      0.193      3.915      0.000       0.378       1.134
Precinct_88                                         0.0922      0.077      1.204      0.229      -0.058       0.242
Precinct_90                                        -0.4909      0.121     -4.050      0.000      -0.728      -0.253
Precinct_94                                        -0.0623      0.075     -0.829      0.407      -0.210       0.085
Precinct_100                                        0.3434      0.122      2.808      0.005       0.104       0.583
Precinct_101                                        0.2335      0.128      1.824      0.068      -0.017       0.484
Precinct_102                                       -0.5744      0.155     -3.695      0.000      -0.879      -0.270
Precinct_103                                       -0.2725      0.084     -3.227      0.001      -0.438      -0.107
Precinct_104                                       -0.7244      0.184     -3.946      0.000      -1.084      -0.365
Precinct_105                                       -0.5284      0.148     -3.582      0.000      -0.817      -0.239
Precinct_106                                       -0.5225      0.141     -3.702      0.000      -0.799      -0.246
Precinct_107                                       -0.6697      0.171     -3.909      0.000      -1.006      -0.334
Precinct_108                                       -0.6594      0.166     -3.969      0.000      -0.985      -0.334
Precinct_109                                       -0.7950      0.199     -3.994      0.000      -1.185      -0.405
Precinct_110                                       -0.7569      0.171     -4.417      0.000      -1.093      -0.421
Precinct_111                                       -0.5112      0.161     -3.181      0.001      -0.826      -0.196
Precinct_112                                       -0.5708      0.159     -3.595      0.000      -0.882      -0.260
Precinct_114                                       -0.7481      0.185     -4.050      0.000      -1.110      -0.386
Precinct_115                                       -0.7057      0.164     -4.305      0.000      -1.027      -0.384
Precinct_120                                        0.2282      0.127      1.802      0.072      -0.020       0.476
Precinct_122                                       -0.3618      0.146     -2.473      0.013      -0.649      -0.075
Precinct_123                                       -0.3521      0.157     -2.243      0.025      -0.660      -0.044
==============================================================================
Omnibus:                     1217.684   Durbin-Watson:                   1.889
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           416442.809
Skew:                           3.945   Prob(JB):                         0.00
Kurtosis:                      93.018   Cond. No.                         264.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 98, but rank is 27
  warnings.warn('covariance of constraints does not have full '

Start to regornize Vol+ property crime

In [36]:
X_vars = [
    'Violent Crime_per_capita_lag1',
    'Property Crime_per_capita_lag1',
    'Budget_per_capita_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_per_capita'

# Ensure required columns are present
required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create Year dummies only (one-way FE)
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)

# Standardize X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors + year dummies
X_combined = pd.concat([X_base, year_dummies], axis=1)

# Standardize y
y_standardized = ((df[y_var] - df[y_var].mean()) / df[y_var].std()).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined).astype(float)

# Fit model with clustered SEs by precinct
model_fe_year = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Print results
print(model_fe_year.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.956
Method:                 Least Squares   F-statistic:                     7160.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):          5.78e-110
Time:                        01:21:10   Log-Likelihood:                 191.53
No. Observations:                1224   AIC:                            -337.1
Df Residuals:                    1201   BIC:                            -219.5
Df Model:                          22
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              0.1682      0.043      3.894      0.000       0.084       0.253
Violent Crime_per_capita_lag1      0.0477      0.016      3.040      0.002       0.017       0.078
Property Crime_per_capita_lag1     0.0170      0.012      1.388      0.165      -0.007       0.041
Budget_per_capita_lag1             0.9423      0.027     34.580      0.000       0.889       0.996
minority_pct_lag1                 -0.0134      0.008     -1.785      0.074      -0.028       0.001
per_capita_income_lag1            -0.0064      0.006     -1.124      0.261      -0.018       0.005
total_pop_lag1                    -0.0210      0.008     -2.554      0.011      -0.037      -0.005
Year_2008                         -0.2032      0.040     -5.108      0.000      -0.281      -0.125
Year_2009                         -0.2599      0.037     -7.011      0.000      -0.333      -0.187
Year_2010                         -0.2024      0.072     -2.800      0.005      -0.344      -0.061
Year_2011                          0.2002      0.050      3.968      0.000       0.101       0.299
Year_2012                         -0.3792      0.055     -6.876      0.000      -0.487      -0.271
Year_2013                         -0.1103      0.058     -1.918      0.055      -0.223       0.002
Year_2014                         -0.2312      0.041     -5.570      0.000      -0.312      -0.150
Year_2015                         -0.2381      0.049     -4.886      0.000      -0.334      -0.143
Year_2016                         -0.2002      0.049     -4.045      0.000      -0.297      -0.103
Year_2017                         -0.1487      0.049     -3.026      0.002      -0.245      -0.052
Year_2018                         -0.0407      0.052     -0.776      0.438      -0.143       0.062
Year_2019                         -0.2242      0.053     -4.269      0.000      -0.327      -0.121
Year_2020                         -0.2075      0.053     -3.884      0.000      -0.312      -0.103
Year_2021                         -0.2562      0.054     -4.765      0.000      -0.362      -0.151
Year_2022                         -0.1788      0.049     -3.686      0.000      -0.274      -0.084
Year_2023                         -0.1790      0.043     -4.160      0.000      -0.263      -0.095
==============================================================================
Omnibus:                      506.403   Durbin-Watson:                   1.877
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           463430.077
Skew:                           0.156   Prob(JB):                         0.00
Kurtosis:                      98.325   Cond. No.                         28.2
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [37]:
X_vars = [
    'Violent Crime_per_capita_lag1',
    'Property Crime_per_capita_lag1',
    'Budget_per_capita_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_per_capita'

# Ensure required columns are present
required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create Year and Precinct dummies
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
precinct_dummies = pd.get_dummies(df['Precinct'], prefix='Precinct', drop_first=True, dtype=float)

# Standardize X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

X_combined = pd.concat([X_base, year_dummies, precinct_dummies], axis=1)

# Standardize y
y_standardized = ((df[y_var] - df[y_var].mean()) / df[y_var].std()).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Ensure all are float type
X_combined = X_combined.astype(float)

model_fe_both = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Print results
print(model_fe_both.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.967
Model:                            OLS   Adj. R-squared:                  0.964
Method:                 Least Squares   F-statistic:                     41.60
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           4.74e-32
Time:                        01:21:10   Log-Likelihood:                 354.08
No. Observations:                1224   AIC:                            -520.2
Df Residuals:                    1130   BIC:                            -39.83
Df Model:                          93
Covariance Type:              cluster
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              0.1762      0.096      1.830      0.067      -0.013       0.365
Violent Crime_per_capita_lag1      0.0228      0.026      0.883      0.377      -0.028       0.074
Property Crime_per_capita_lag1     0.0824      0.035      2.345      0.019       0.014       0.151
Budget_per_capita_lag1             0.5328      0.103      5.152      0.000       0.330       0.735
minority_pct_lag1                 -0.0019      0.018     -0.107      0.915      -0.037       0.033
per_capita_income_lag1             0.0080      0.022      0.365      0.715      -0.035       0.051
total_pop_lag1                    -0.0027      0.013     -0.203      0.839      -0.028       0.023
Year_2008                         -0.0806      0.047     -1.723      0.085      -0.172       0.011
Year_2009                         -0.1150      0.049     -2.342      0.019      -0.211      -0.019
Year_2010                         -0.0523      0.096     -0.545      0.585      -0.240       0.136
Year_2011                          0.3689      0.051      7.236      0.000       0.269       0.469
Year_2012                         -0.0327      0.106     -0.310      0.756      -0.240       0.174
Year_2013                          0.1586      0.099      1.595      0.111      -0.036       0.354
Year_2014                          0.0820      0.091      0.899      0.369      -0.097       0.261
Year_2015                          0.0700      0.094      0.748      0.454      -0.113       0.253
Year_2016                          0.0987      0.093      1.062      0.288      -0.083       0.281
Year_2017                          0.1594      0.095      1.676      0.094      -0.027       0.346
Year_2018                          0.2926      0.098      2.993      0.003       0.101       0.484
Year_2019                          0.1712      0.111      1.549      0.121      -0.045       0.388
Year_2020                          0.1766      0.109      1.615      0.106      -0.038       0.391
Year_2021                          0.1177      0.108      1.093      0.274      -0.093       0.329
Year_2022                          0.1648      0.099      1.670      0.095      -0.029       0.358
Year_2023                          0.1459      0.090      1.628      0.103      -0.030       0.321
Precinct_5                         0.1106      0.058      1.922      0.055      -0.002       0.223
Precinct_6                        -0.1529      0.052     -2.945      0.003      -0.255      -0.051
Precinct_7                         0.0957      0.070      1.366      0.172      -0.042       0.233
Precinct_9                        -0.3102      0.066     -4.704      0.000      -0.439      -0.181
Precinct_10                       -0.0409      0.022     -1.854      0.064      -0.084       0.002
Precinct_13                       -0.5391      0.120     -4.508      0.000      -0.774      -0.305
Precinct_17                       -0.4099      0.102     -4.004      0.000      -0.611      -0.209
Precinct_19                       -0.8699      0.193     -4.507      0.000      -1.248      -0.492
Precinct_20                       -0.6102      0.138     -4.409      0.000      -0.881      -0.339
Precinct_23                        0.0232      0.095      0.244      0.807      -0.163       0.209
Precinct_24                       -0.5583      0.122     -4.581      0.000      -0.797      -0.319
Precinct_25                        0.6128      0.204      3.008      0.003       0.214       1.012
Precinct_26                        0.2964      0.107      2.762      0.006       0.086       0.507
Precinct_28                        0.7265      0.216      3.371      0.001       0.304       1.149
Precinct_30                        0.2543      0.125      2.038      0.042       0.010       0.499
Precinct_32                        0.1494      0.123      1.213      0.225      -0.092       0.391
Precinct_33                        0.0760      0.101      0.752      0.452      -0.122       0.274
Precinct_34                       -0.3806      0.096     -3.949      0.000      -0.569      -0.192
Precinct_40                        0.0043      0.105      0.041      0.967      -0.201       0.210
Precinct_41                        0.4306      0.180      2.393      0.017       0.078       0.783
Precinct_42                       -0.1639      0.083     -1.981      0.048      -0.326      -0.002
Precinct_43                       -0.5893      0.109     -5.417      0.000      -0.802      -0.376
Precinct_44                       -0.2429      0.078     -3.104      0.002      -0.396      -0.090
Precinct_45                       -0.5831      0.125     -4.666      0.000      -0.828      -0.338
Precinct_46                       -0.2067      0.083     -2.485      0.013      -0.370      -0.044
Precinct_47                       -0.5532      0.112     -4.938      0.000      -0.773      -0.334
Precinct_48                       -0.0409      0.087     -0.471      0.638      -0.211       0.129
Precinct_49                       -0.4535      0.096     -4.744      0.000      -0.641      -0.266
Precinct_50                       -0.4996      0.111     -4.495      0.000      -0.717      -0.282
Precinct_52                       -0.4731      0.093     -5.069      0.000      -0.656      -0.290
Precinct_60                       -0.3398      0.086     -3.973      0.000      -0.507      -0.172
Precinct_61                       -0.7906      0.172     -4.606      0.000      -1.127      -0.454
Precinct_62                       -0.8687      0.175     -4.957      0.000      -1.212      -0.525
Precinct_63                       -0.5948      0.123     -4.841      0.000      -0.836      -0.354
Precinct_66                       -0.8620      0.177     -4.859      0.000      -1.210      -0.514
Precinct_67                       -0.4345      0.092     -4.739      0.000      -0.614      -0.255
Precinct_68                       -0.7212      0.150     -4.794      0.000      -1.016      -0.426
Precinct_69                       -0.3610      0.084     -4.309      0.000      -0.525      -0.197
Precinct_70                       -0.4785      0.102     -4.709      0.000      -0.678      -0.279
Precinct_71                       -0.2019      0.071     -2.861      0.004      -0.340      -0.064
Precinct_72                       -0.6133      0.126     -4.857      0.000      -0.861      -0.366
Precinct_73                        0.2143      0.150      1.427      0.154      -0.080       0.509
Precinct_75                       -0.3750      0.081     -4.617      0.000      -0.534      -0.216
Precinct_76                        0.3532      0.120      2.951      0.003       0.119       0.588
Precinct_77                       -0.0218      0.085     -0.256      0.798      -0.189       0.145
Precinct_78                       -0.1060      0.054     -1.960      0.050      -0.212    1.19e-06
Precinct_79                       -0.0496      0.090     -0.549      0.583      -0.226       0.127
Precinct_81                        0.1937      0.122      1.593      0.111      -0.045       0.432
Precinct_83                       -0.3973      0.076     -5.219      0.000      -0.547      -0.248
Precinct_84                        0.7068      0.196      3.602      0.000       0.322       1.091
Precinct_88                        0.0429      0.081      0.532      0.595      -0.115       0.201
Precinct_90                       -0.5634      0.105     -5.366      0.000      -0.769      -0.358
Precinct_94                       -0.1259      0.050     -2.532      0.011      -0.223      -0.028
Precinct_100                       0.3224      0.125      2.581      0.010       0.078       0.567
Precinct_101                       0.2379      0.127      1.866      0.062      -0.012       0.488
Precinct_102                      -0.6272      0.130     -4.813      0.000      -0.883      -0.372
Precinct_103                      -0.2966      0.072     -4.148      0.000      -0.437      -0.156
Precinct_104                      -0.7881      0.158     -4.995      0.000      -1.097      -0.479
Precinct_105                      -0.5869      0.123     -4.788      0.000      -0.827      -0.347
Precinct_106                      -0.5773      0.117     -4.950      0.000      -0.806      -0.349
Precinct_107                      -0.7270      0.150     -4.839      0.000      -1.022      -0.433
Precinct_108                      -0.7045      0.140     -5.034      0.000      -0.979      -0.430
Precinct_109                      -0.8476      0.174     -4.866      0.000      -1.189      -0.506
Precinct_110                      -0.7837      0.153     -5.134      0.000      -1.083      -0.484
Precinct_111                      -0.5808      0.135     -4.295      0.000      -0.846      -0.316
Precinct_112                      -0.6173      0.137     -4.521      0.000      -0.885      -0.350
Precinct_114                      -0.7930      0.162     -4.906      0.000      -1.110      -0.476
Precinct_115                      -0.7264      0.142     -5.110      0.000      -1.005      -0.448
Precinct_120                       0.2199      0.123      1.784      0.074      -0.022       0.461
Precinct_122                      -0.4154      0.128     -3.234      0.001      -0.667      -0.164
Precinct_123                      -0.4072      0.138     -2.951      0.003      -0.678      -0.137
==============================================================================
Omnibus:                     1194.033   Durbin-Watson:                   1.885
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           393385.144
Skew:                           3.815   Prob(JB):                         0.00
Kurtosis:                      90.494   Cond. No.                         177.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 93, but rank is 22
  warnings.warn('covariance of constraints does not have full '

In [38]:
X_vars = [
    'Violent Crime_pct_lag1',
    'Property Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

# Ensure required columns are present
required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create Year and Precinct dummies
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
precinct_dummies = pd.get_dummies(df['Precinct'], prefix='Precinct', drop_first=True, dtype=float)

# Standardize X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors + year dummies + precinct dummies
X_combined = pd.concat([X_base, year_dummies, precinct_dummies], axis=1)

# Standardize y
y_standardized = ((df[y_var] - df[y_var].mean()) / df[y_var].std()).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Ensure all are float type
X_combined = X_combined.astype(float)

model_fe_both = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

# Print results
print(model_fe_both.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.928
Model:                            OLS   Adj. R-squared:                  0.922
Method:                 Least Squares   F-statistic:                     20.50
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           1.54e-22
Time:                        01:21:10   Log-Likelihood:                -126.77
No. Observations:                1224   AIC:                             441.5
Df Residuals:                    1130   BIC:                             921.9
Df Model:                          93
Covariance Type:              cluster
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.2671      0.098      2.726      0.006       0.075       0.459
Violent Crime_pct_lag1      0.0506      0.055      0.923      0.356      -0.057       0.158
Property Crime_pct_lag1    -0.0310      0.036     -0.861      0.389      -0.102       0.040
Budget_pct_lag1             0.5251      0.102      5.133      0.000       0.325       0.726
minority_pct_lag1           0.0055      0.025      0.217      0.828      -0.044       0.055
per_capita_income_lag1      0.0216      0.028      0.772      0.440      -0.033       0.076
total_pop_lag1             -0.0210      0.031     -0.669      0.504      -0.083       0.041
Year_2008                  -0.0003      0.043     -0.008      0.994      -0.085       0.085
Year_2009                  -0.0020      0.037     -0.052      0.958      -0.075       0.071
Year_2010                  -0.0018      0.077     -0.024      0.981      -0.152       0.149
Year_2011                  -0.0052      0.073     -0.070      0.944      -0.148       0.138
Year_2012                  -0.0048      0.064     -0.074      0.941      -0.131       0.121
Year_2013                  -0.0124      0.081     -0.154      0.878      -0.171       0.146
Year_2014                  -0.0060      0.071     -0.085      0.932      -0.145       0.133
Year_2015                  -0.0106      0.068     -0.155      0.876      -0.145       0.123
Year_2016                  -0.0117      0.074     -0.158      0.874      -0.156       0.133
Year_2017                  -0.0218      0.058     -0.377      0.706      -0.135       0.091
Year_2018                  -0.0143      0.058     -0.246      0.805      -0.128       0.100
Year_2019                  -0.0141      0.056     -0.253      0.800      -0.123       0.095
Year_2020                  -0.0175      0.056     -0.310      0.757      -0.128       0.093
Year_2021                  -0.0181      0.057     -0.317      0.751      -0.130       0.094
Year_2022                  -0.0209      0.059     -0.356      0.722      -0.136       0.094
Year_2023                  -0.0201      0.060     -0.334      0.738      -0.138       0.098
Precinct_5                 -0.7780      0.141     -5.500      0.000      -1.055      -0.501
Precinct_6                 -0.4744      0.106     -4.481      0.000      -0.682      -0.267
Precinct_7                 -0.7018      0.149     -4.717      0.000      -0.993      -0.410
Precinct_9                 -0.5546      0.110     -5.040      0.000      -0.770      -0.339
Precinct_10                -0.6343      0.140     -4.536      0.000      -0.908      -0.360
Precinct_13                -0.2915      0.090     -3.229      0.001      -0.468      -0.115
Precinct_17                -0.6281      0.149     -4.223      0.000      -0.920      -0.337
Precinct_19                 0.0183      0.075      0.244      0.808      -0.129       0.166
Precinct_20                -0.6710      0.143     -4.683      0.000      -0.952      -0.390
Precinct_23                -0.4545      0.119     -3.816      0.000      -0.688      -0.221
Precinct_24                -0.6711      0.141     -4.760      0.000      -0.947      -0.395
Precinct_25                -0.4606      0.123     -3.747      0.000      -0.702      -0.220
Precinct_26                -0.7577      0.160     -4.731      0.000      -1.072      -0.444
Precinct_28                -0.4428      0.112     -3.937      0.000      -0.663      -0.222
Precinct_30                -0.5557      0.117     -4.746      0.000      -0.785      -0.326
Precinct_32                -0.2229      0.108     -2.062      0.039      -0.435      -0.011
Precinct_33                -0.4249      0.100     -4.269      0.000      -0.620      -0.230
Precinct_34                -0.2850      0.079     -3.617      0.000      -0.439      -0.131
Precinct_40                 0.2296      0.198      1.157      0.247      -0.159       0.619
Precinct_41                -0.4642      0.117     -3.954      0.000      -0.694      -0.234
Precinct_42                -0.3249      0.141     -2.311      0.021      -0.600      -0.049
Precinct_43                 0.3210      0.212      1.516      0.129      -0.094       0.736
Precinct_44                 0.7328      0.273      2.680      0.007       0.197       1.269
Precinct_45                -0.4197      0.085     -4.947      0.000      -0.586      -0.253
Precinct_46                 0.3916      0.203      1.930      0.054      -0.006       0.789
Precinct_47                 0.0896      0.178      0.502      0.616      -0.260       0.439
Precinct_48                -0.1412      0.133     -1.061      0.289      -0.402       0.120
Precinct_49                -0.2518      0.086     -2.911      0.004      -0.421      -0.082
Precinct_50                -0.5871      0.120     -4.888      0.000      -0.823      -0.352
Precinct_52                 0.1418      0.163      0.868      0.385      -0.178       0.462
Precinct_60                -0.2883      0.083     -3.467      0.001      -0.451      -0.125
Precinct_61                -0.5315      0.103     -5.175      0.000      -0.733      -0.330
Precinct_62                -0.5659      0.148     -3.823      0.000      -0.856      -0.276
Precinct_63                -0.6035      0.134     -4.510      0.000      -0.866      -0.341
Precinct_66                -0.5232      0.135     -3.878      0.000      -0.788      -0.259
Precinct_67                 0.4278      0.215      1.992      0.046       0.007       0.849
Precinct_68                -0.7026      0.155     -4.539      0.000      -1.006      -0.399
Precinct_69                -0.6474      0.132     -4.892      0.000      -0.907      -0.388
Precinct_70                 0.3695      0.169      2.185      0.029       0.038       0.701
Precinct_71                -0.1423      0.102     -1.397      0.163      -0.342       0.057
Precinct_72                -0.4958      0.113     -4.378      0.000      -0.718      -0.274
Precinct_73                 0.4091      0.230      1.781      0.075      -0.041       0.859
Precinct_75                 1.3848      0.459      3.019      0.003       0.486       2.284
Precinct_76                -0.8274      0.172     -4.806      0.000      -1.165      -0.490
Precinct_77                 0.0949      0.132      0.717      0.473      -0.164       0.354
Precinct_78                -0.5347      0.123     -4.364      0.000      -0.775      -0.295
Precinct_79                 0.1742      0.162      1.074      0.283      -0.144       0.492
Precinct_81                -0.2907      0.113     -2.579      0.010      -0.512      -0.070
Precinct_83                -0.0960      0.133     -0.722      0.470      -0.357       0.165
Precinct_84                 0.0442      0.075      0.586      0.558      -0.104       0.192
Precinct_88                -0.6339      0.127     -4.989      0.000      -0.883      -0.385
Precinct_90                -0.2686      0.089     -3.009      0.003      -0.444      -0.094
Precinct_94                -0.6347      0.122     -5.182      0.000      -0.875      -0.395
Precinct_100               -0.8241      0.173     -4.753      0.000      -1.164      -0.484
Precinct_101               -0.3419      0.098     -3.475      0.001      -0.535      -0.149
Precinct_102               -0.2810      0.091     -3.084      0.002      -0.460      -0.102
Precinct_103               -0.0250      0.132     -0.189      0.850      -0.284       0.234
Precinct_104               -0.3776      0.093     -4.041      0.000      -0.561      -0.194
Precinct_105                0.4429      0.169      2.617      0.009       0.111       0.775
Precinct_106               -0.3891      0.085     -4.595      0.000      -0.555      -0.223
Precinct_107               -0.4420      0.095     -4.641      0.000      -0.629      -0.255
Precinct_108               -0.6462      0.122     -5.316      0.000      -0.884      -0.408
Precinct_109                0.1857      0.095      1.953      0.051      -0.001       0.372
Precinct_110               -0.3999      0.115     -3.477      0.001      -0.625      -0.175
Precinct_111               -0.5428      0.113     -4.786      0.000      -0.765      -0.321
Precinct_112               -0.7155      0.150     -4.776      0.000      -1.009      -0.422
Precinct_114               -0.0837      0.088     -0.955      0.340      -0.256       0.088
Precinct_115               -0.2156      0.093     -2.313      0.021      -0.398      -0.033
Precinct_120                0.9991      0.278      3.588      0.000       0.453       1.545
Precinct_122                0.0462      0.101      0.458      0.647      -0.152       0.244
Precinct_123               -0.6966      0.160     -4.347      0.000      -1.011      -0.383
==============================================================================
Omnibus:                      948.637   Durbin-Watson:                   1.957
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           189611.235
Skew:                           2.642   Prob(JB):                         0.00
Kurtosis:                      63.745   Cond. No.                         172.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 93, but rank is 22
  warnings.warn('covariance of constraints does not have full '

# Spatial Analysis

In [39]:
# Load GeoJSON
precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson")

# Check CRS
precincts_gdf_s = precincts_gdf_s.to_crs(epsg=4326)

In [40]:
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

In [41]:
precincts_gdf_s

,FID,shape_area,shape_leng,Precinct,geometry
0,1,4.730176e+07,80586.154615,1,"MULTIPOLYGON (((-74.04388 40.69019, -74.04351 ..."
1,2,1.808880e+07,18676.124259,5,"POLYGON ((-73.98864 40.72293, -73.98869 40.722..."
2,3,2.213193e+07,27182.610113,6,"POLYGON ((-73.99968 40.73855, -73.99684 40.737..."
3,4,1.836402e+07,17301.308682,7,"POLYGON ((-73.97345 40.71896, -73.97351 40.718..."
4,5,2.139423e+07,19773.233410,9,"POLYGON ((-73.97161 40.72672, -73.97163 40.726..."
...,...,...,...,...,...
72,73,1.132939e+08,58272.204348,115,"POLYGON ((-73.85908 40.76252, -73.85943 40.762..."
73,74,2.325353e+08,96171.721461,120,"POLYGON ((-74.05357 40.60370, -74.05407 40.603..."
74,75,4.757161e+08,138115.721207,121,"MULTIPOLYGON (((-74.15946 40.64145, -74.15975 ..."
75,76,4.547993e+08,154881.006310,122,"MULTIPOLYGON (((-74.05051 40.56642, -74.05047 ..."
76,77,4.608700e+08,120830.181066,123,"POLYGON ((-74.16983 40.56108, -74.16974 40.560..."

In [42]:
merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")

# Create spatial weights
from libpysal.weights import Queen, lag_spatial
w = Queen.from_dataframe(merged_sp)
w.transform = "r"

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\2348201342.py:5: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

In [43]:
precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

# Merge
merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")

# Clean column names for regression formula compatibility
merged_sp.columns = [col.replace(" ", "_") for col in merged_sp.columns]

# Filter out 2006 (first lag year)
merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

# Define variables
X_vars = [
    'Violent_Crime_pct_lag1',
    'Property_Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

# Create spatial weights
w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# Create spatial lag of outcome
merged_sp['lag_Budget_pct'] = lag_spatial(w, merged_sp[y_var])

# Fill missing X values (if any) before spatial lagging
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f'lag_{var}'] = lag_spatial(w, merged_sp[var])

# Drop rows where spatial lags are still NaN (disconnected precincts only)
lag_vars = [f'lag_{var}' for var in X_vars] + ['lag_Budget_pct']
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars)

# Confirm number of usable rows
print("Original (post-2006):", len(merged_sp))
print("Rows after dropna (usable for regression):", len(merged_sp_clean))

# Build regression formula
formula = f"{y_var} ~ lag_Budget_pct + " + " + ".join(X_vars + [f'lag_{var}' for var in X_vars])

# Fit model
model = smf.ols(formula=formula, data=merged_sp_clean).fit()
print(model.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\2642333130.py:25: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Original (post-2006): 1241
Rows after dropna (usable for regression): 1241
                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.917
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     1039.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:21:54   Log-Likelihood:                 6865.2
No. Observations:                1241   AIC:                        -1.370e+04
Df Residuals:                    1227   BIC:                        -1.363e+04
Df Model:                          13
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -0.0009      0.001     -1.670      0.095      -0.002       0.000
lag_Budget_pct                 -3.6045      0.489     -7.369      0.000      -4.564      -2.645
Violent_Crime_pct_lag1          0.0533      0.007      7.142      0.000       0.039       0.068
Property_Crime_pct_lag1         0.0236      0.009      2.579      0.010       0.006       0.041
Budget_pct_lag1                 0.8199      0.016     51.724      0.000       0.789       0.851
minority_pct_lag1            5.437e-05      0.000      0.205      0.837      -0.000       0.001
per_capita_income_lag1       6.334e-10   3.18e-09      0.199      0.842    -5.6e-09    6.87e-09
total_pop_lag1               4.317e-10    7.7e-10      0.560      0.575   -1.08e-09    1.94e-09
lag_Violent_Crime_pct_lag1     -0.0756      0.013     -5.807      0.000      -0.101      -0.050
lag_Property_Crime_pct_lag1    -0.0187      0.014     -1.375      0.170      -0.045       0.008
lag_Budget_pct_lag1             3.9186      0.500      7.845      0.000       2.939       4.899
lag_minority_pct_lag1           0.0003      0.001      0.538      0.591      -0.001       0.001
lag_per_capita_income_lag1  -2.142e-08   6.44e-09     -3.327      0.001    -3.4e-08   -8.79e-09
lag_total_pop_lag1           -1.04e-09   1.12e-09     -0.932      0.351   -3.23e-09    1.15e-09
==============================================================================
Omnibus:                      646.826   Durbin-Watson:                   2.144
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           162464.215
Skew:                           1.216   Prob(JB):                         0.00
Kurtosis:                      59.000   Cond. No.                     5.15e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.15e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

In [44]:
# Load precinct shapefile and merge with panel data
precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})
merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")

# Clean column names
merged_sp.columns = [col.replace(" ", "_") for col in merged_sp.columns]

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

# Define independent variables (keep all original X_vars)
X_vars = [
    'Violent_Crime_pct_lag1',
    'Property_Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]

# Define spatial lag variables (exclude lag_Budget_pct)
spatial_lags = [
    'lag_Violent_Crime_pct_lag1',
    'lag_Property_Crime_pct_lag1',
    'lag_Budget_pct_lag1',
    'lag_minority_pct_lag1',
    'lag_per_capita_income_lag1',
    'lag_total_pop_lag1'
]

y_var = 'Budget_pct'

# Create spatial weights matrix
w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# Fill missing values in predictors (optional, safe for spatial lagging)
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())

# Compute spatial lags (except lag_Budget_pct)
for var in X_vars:
    merged_sp[f'lag_{var}'] = lag_spatial(w, merged_sp[var])

# Drop rows with any missing value in outcome or predictors
merged_sp_clean = merged_sp.dropna(subset=[y_var] + X_vars + spatial_lags)

# Build regression formula (excluding lag_Budget_pct)
formula = f"{y_var} ~ " + " + ".join(X_vars + spatial_lags)

# Fit model
model = smf.ols(formula=formula, data=merged_sp_clean).fit()
print(model.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\1746595464.py:34: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.913
Model:                            OLS   Adj. R-squared:                  0.912
Method:                 Least Squares   F-statistic:                     1074.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:22:15   Log-Likelihood:                 6838.3
No. Observations:                1241   AIC:                        -1.365e+04
Df Residuals:                    1228   BIC:                        -1.358e+04
Df Model:                          12
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -0.0006      0.001     -1.076      0.282      -0.002       0.001
Violent_Crime_pct_lag1          0.0575      0.008      7.554      0.000       0.043       0.072
Property_Crime_pct_lag1         0.0247      0.009      2.644      0.008       0.006       0.043
Budget_pct_lag1                 0.8079      0.016     50.162      0.000       0.776       0.839
minority_pct_lag1             2.01e-05      0.000      0.074      0.941      -0.001       0.001
per_capita_income_lag1       1.981e-10   3.25e-09      0.061      0.951   -6.17e-09    6.56e-09
total_pop_lag1               6.438e-10   7.86e-10      0.819      0.413   -8.99e-10    2.19e-09
lag_Violent_Crime_pct_lag1     -0.0698      0.013     -5.256      0.000      -0.096      -0.044
lag_Property_Crime_pct_lag1    -0.0259      0.014     -1.868      0.062      -0.053       0.001
lag_Budget_pct_lag1             0.2479      0.038      6.508      0.000       0.173       0.323
lag_minority_pct_lag1           0.0003      0.001      0.550      0.582      -0.001       0.001
lag_per_capita_income_lag1  -2.153e-09   6.01e-09     -0.358      0.720   -1.39e-08    9.64e-09
lag_total_pop_lag1          -8.393e-10   1.14e-09     -0.737      0.461   -3.07e-09     1.4e-09
==============================================================================
Omnibus:                      763.617   Durbin-Watson:                   2.284
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           220069.128
Skew:                           1.654   Prob(JB):                         0.00
Kurtosis:                      68.154   Cond. No.                     2.94e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.94e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [45]:
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())

In [46]:
# Define predictors
X_vars = [
    'Violent Crime_pct_lag1',
    'Property Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]

In [47]:
# Clean column names: replace spaces with underscores
merged_sp.columns = [col.replace(" ", "_") for col in merged_sp.columns]

# Define cleaned predictors and dependent variable
X_vars = [
    'Violent_Crime_pct_lag1',
    'Property_Crime_pct_lag1',
    'Budget_pct_lag1',
    'minority_pct_lag1',
    'per_capita_income_lag1',
    'total_pop_lag1'
]
y_var = 'Budget_pct'

# Create spatial weights matrix
w = Queen.from_dataframe(merged_sp)
w.transform = 'r'  # Row-standardized

# Add spatial lag of the dependent variable
merged_sp['lag_Budget_pct'] = lag_spatial(w, merged_sp[y_var])

# Add spatial lags of all predictor variables
for var in X_vars:
    merged_sp[f'lag_{var}'] = lag_spatial(w, merged_sp[var])

# Drop rows with missing values in predictors or lags (e.g., disconnected precincts)
all_predictors = ['lag_Budget_pct'] + X_vars + [f'lag_{var}' for var in X_vars]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + all_predictors)

# Build the formula for regression
formula = f"{y_var} ~ lag_Budget_pct + " + " + ".join(X_vars + [f'lag_{var}' for var in X_vars])

# Fit the OLS model
model = smf.ols(formula=formula, data=merged_sp_clean).fit()

print(model.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\563835111.py:16: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_pct   R-squared:                       0.917
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     1039.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):               0.00
Time:                        01:22:34   Log-Likelihood:                 6865.2
No. Observations:                1241   AIC:                        -1.370e+04
Df Residuals:                    1227   BIC:                        -1.363e+04
Df Model:                          13
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                      -0.0009      0.001     -1.670      0.095      -0.002       0.000
lag_Budget_pct                 -3.6045      0.489     -7.369      0.000      -4.564      -2.645
Violent_Crime_pct_lag1          0.0533      0.007      7.142      0.000       0.039       0.068
Property_Crime_pct_lag1         0.0236      0.009      2.579      0.010       0.006       0.041
Budget_pct_lag1                 0.8199      0.016     51.724      0.000       0.789       0.851
minority_pct_lag1            5.437e-05      0.000      0.205      0.837      -0.000       0.001
per_capita_income_lag1       6.334e-10   3.18e-09      0.199      0.842    -5.6e-09    6.87e-09
total_pop_lag1               4.317e-10    7.7e-10      0.560      0.575   -1.08e-09    1.94e-09
lag_Violent_Crime_pct_lag1     -0.0756      0.013     -5.807      0.000      -0.101      -0.050
lag_Property_Crime_pct_lag1    -0.0187      0.014     -1.375      0.170      -0.045       0.008
lag_Budget_pct_lag1             3.9186      0.500      7.845      0.000       2.939       4.899
lag_minority_pct_lag1           0.0003      0.001      0.538      0.591      -0.001       0.001
lag_per_capita_income_lag1  -2.142e-08   6.44e-09     -3.327      0.001    -3.4e-08   -8.79e-09
lag_total_pop_lag1           -1.04e-09   1.12e-09     -0.932      0.351   -3.23e-09    1.15e-09
==============================================================================
Omnibus:                      646.826   Durbin-Watson:                   2.144
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           162464.215
Skew:                           1.216   Prob(JB):                         0.00
Kurtosis:                      59.000   Cond. No.                     5.15e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.15e+09. This might indicate that there are
strong multicollinearity or other numerical problems.

In [48]:
X_vars = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var = 'Budget_per_capita'

required_columns = X_vars + [y_var, 'Precinct', 'Year']
df = pre_ts_analysis[required_columns].dropna().copy()

# Create year dummies and ensure numeric dtype
year_dummies = pd.get_dummies(df['Year'], prefix='Year', drop_first=True, dtype=float)
df = pd.concat([df, year_dummies], axis=1)

# Standardize main X predictors
scaler = StandardScaler()
X_base = pd.DataFrame(
    scaler.fit_transform(df[X_vars]),
    columns=X_vars,
    index=df.index
)

# Combine X predictors with year dummies
X_combined = pd.concat([X_base, year_dummies], axis=1)

# Standardize the outcome variable
y_mean = df[y_var].mean()
y_std = df[y_var].std()
y_standardized = ((df[y_var] - y_mean) / y_std).astype(float)
y_standardized.index = df.index

# Add intercept
X_combined = sm.add_constant(X_combined)

# Force all data to float64
X_combined = X_combined.astype(float)

# Fit OLS with clustered SEs by precinct
model_clustered_timefe = sm.OLS(y_standardized, X_combined).fit(
    cov_type='cluster',
    cov_kwds={'groups': df['Precinct']}
)

print(model_clustered_timefe.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     5855.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):          1.66e-108
Time:                        01:22:34   Log-Likelihood:                 197.03
No. Observations:                1224   AIC:                            -338.1
Df Residuals:                    1196   BIC:                            -195.0
Df Model:                          27
Covariance Type:              cluster
===================================================================================================================
                                                      coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                               0.1797      0.042      4.271      0.000       0.097       0.262
MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1     0.0072      0.007      1.091      0.275      -0.006       0.020
RAPE_per_capita_lag1                                0.0259      0.010      2.710      0.007       0.007       0.045
FELONY ASSAULT_per_capita_lag1                      0.0192      0.016      1.174      0.241      -0.013       0.051
BURGLARY_per_capita_lag1                            0.0064      0.010      0.636      0.525      -0.013       0.026
GRAND LARCENY_per_capita_lag1                       0.0208      0.012      1.710      0.087      -0.003       0.045
GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1     -0.0140      0.008     -1.659      0.097      -0.031       0.003
ROBBERY_per_capita_lag1                             0.0131      0.020      0.664      0.507      -0.026       0.052
Budget_per_capita_lag1                              0.9334      0.029     31.814      0.000       0.876       0.991
minority_pct_lag1                                  -0.0151      0.007     -2.045      0.041      -0.030      -0.001
per_capita_income_lag1                             -0.0111      0.006     -1.806      0.071      -0.023       0.001
total_pop_lag1                                     -0.0205      0.008     -2.484      0.013      -0.037      -0.004
Year_2008                                          -0.2018      0.039     -5.113      0.000      -0.279      -0.124
Year_2009                                          -0.2595      0.038     -6.915      0.000      -0.333      -0.186
Year_2010                                          -0.2065      0.069     -2.994      0.003      -0.342      -0.071
Year_2011                                           0.1900      0.053      3.567      0.000       0.086       0.294
Year_2012                                          -0.3898      0.053     -7.304      0.000      -0.494      -0.285
Year_2013                                          -0.1258      0.056     -2.257      0.024      -0.235      -0.017
Year_2014                                          -0.2435      0.043     -5.712      0.000      -0.327      -0.160
Year_2015                                          -0.2514      0.048     -5.269      0.000      -0.345      -0.158
Year_2016                                          -0.2168      0.048     -4.513      0.000      -0.311      -0.123
Year_2017                                          -0.1679      0.047     -3.552      0.000      -0.261      -0.075
Year_2018                                          -0.0617      0.051     -1.203      0.229      -0.162       0.039
Year_2019                                          -0.2558      0.049     -5.226      0.000      -0.352      -0.160
Year_2020                                          -0.2343      0.051     -4.613      0.000      -0.334      -0.135
Year_2021                                          -0.2662      0.052     -5.071      0.000      -0.369      -0.163
Year_2022                                          -0.1860      0.046     -4.027      0.000      -0.277      -0.095
Year_2023                                          -0.1773      0.043     -4.099      0.000      -0.262      -0.093
==============================================================================
Omnibus:                      512.201   Durbin-Watson:                   1.885
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           467461.918
Skew:                           0.226   Prob(JB):                         0.00
Kurtosis:                      98.738   Cond. No.                         42.8
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

In [49]:
def clean_name(s: str) -> str:
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")

# clean all column names for formula safety
merged_sp = clean_cols(merged_sp)

# filter out first lag year
merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1",
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var  = clean_name(y_var_raw)

# -------- spatial weights (Queen contiguity, row-standardized) --------
w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# spatial lag of outcome
lag_y = f"lag_{y_var}"
merged_sp[lag_y] = lag_spatial(w, merged_sp[y_var])

for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f"lag_{var}"] = lag_spatial(w, merged_sp[var])

lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars).copy()

print("Original (post-2006):", len(merged_sp))
print("Rows after dropna (usable for regression):", len(merged_sp_clean))

# -------- formula: SDM (Wy + X + WX) --------
rhs = [lag_y] + X_vars + [f"lag_{v}" for v in X_vars]
formula = f"{y_var} ~ " + " + ".join(rhs)
print("Formula:", formula)


model_cluster = smf.ols(formula=formula, data=merged_sp_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_sp_clean["Precinct"]}
)
print(model_cluster.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\1994377868.py:39: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Original (post-2006): 1241
Rows after dropna (usable for regression): 1241
Formula: Budget_per_capita ~ lag_Budget_per_capita + MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1 + RAPE_per_capita_lag1 + FELONY_ASSAULT_per_capita_lag1 + BURGLARY_per_capita_lag1 + GRAND_LARCENY_per_capita_lag1 + GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1 + ROBBERY_per_capita_lag1 + Budget_per_capita_lag1 + minority_pct_lag1 + per_capita_income_lag1 + total_pop_lag1 + lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1 + lag_RAPE_per_capita_lag1 + lag_FELONY_ASSAULT_per_capita_lag1 + lag_BURGLARY_per_capita_lag1 + lag_GRAND_LARCENY_per_capita_lag1 + lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1 + lag_ROBBERY_per_capita_lag1 + lag_Budget_per_capita_lag1 + lag_minority_pct_lag1 + lag_per_capita_income_lag1 + lag_total_pop_lag1
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.962
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     303.6
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           6.76e-61
Time:                        01:22:55   Log-Likelihood:                -4860.9
No. Observations:                1241   AIC:                             9770.
Df Residuals:                    1217   BIC:                             9893.
Df Model:                          23
Covariance Type:              cluster
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
Intercept                                             59.4643     16.133      3.686      0.000      27.844      91.084
lag_Budget_per_capita                                -18.0937      4.143     -4.367      0.000     -26.214      -9.973
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1        2.058e+04   9605.428      2.143      0.032    1758.634    3.94e+04
RAPE_per_capita_lag1                                1.822e+04   4990.962      3.650      0.000    8433.536     2.8e+04
FELONY_ASSAULT_per_capita_lag1                      1612.1327    897.152      1.797      0.072    -146.253    3370.518
BURGLARY_per_capita_lag1                            -258.6491    927.425     -0.279      0.780   -2076.369    1559.071
GRAND_LARCENY_per_capita_lag1                        151.0650    395.861      0.382      0.703    -624.809     926.939
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1      -677.8544    996.976     -0.680      0.497   -2631.892    1276.183
ROBBERY_per_capita_lag1                             -146.3307    996.056     -0.147      0.883   -2098.565    1805.904
Budget_per_capita_lag1                                 0.8333      0.031     27.043      0.000       0.773       0.894
minority_pct_lag1                                     -1.4234      4.747     -0.300      0.764     -10.728       7.881
per_capita_income_lag1                              2.266e-05   6.35e-05      0.357      0.721      -0.000       0.000
total_pop_lag1                                     -4.574e-05   1.68e-05     -2.719      0.007   -7.87e-05   -1.28e-05
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1     2.53e+05   8.66e+04      2.921      0.003    8.32e+04    4.23e+05
lag_RAPE_per_capita_lag1                            1.486e+04   4.35e+04      0.342      0.733   -7.04e+04       1e+05
lag_FELONY_ASSAULT_per_capita_lag1                  1.292e+04   3644.110      3.546      0.000    5778.596    2.01e+04
lag_BURGLARY_per_capita_lag1                        -1.64e+04   5653.936     -2.901      0.004   -2.75e+04   -5317.846
lag_GRAND_LARCENY_per_capita_lag1                   -186.7827    903.625     -0.207      0.836   -1957.855    1584.289
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1  1.236e+04   5081.525      2.432      0.015    2396.999    2.23e+04
lag_ROBBERY_per_capita_lag1                         -2.46e+04   5810.263     -4.235      0.000    -3.6e+04   -1.32e+04
lag_Budget_per_capita_lag1                            18.5326      4.219      4.393      0.000      10.264      26.802
lag_minority_pct_lag1                                -20.9991     12.790     -1.642      0.101     -46.066       4.068
lag_per_capita_income_lag1                            -0.0004      0.000     -1.660      0.097      -0.001    7.16e-05
lag_total_pop_lag1                                  2.766e-05   2.35e-05      1.175      0.240   -1.85e-05    7.38e-05
==============================================================================
Omnibus:                      558.993   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            24247.048
Skew:                           1.356   Prob(JB):                         0.00
Kurtosis:                      24.484   Cond. No.                     2.68e+10
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 2.68e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 23, but rank is 19
  warnings.warn('covariance of constraints does not have full '

In [50]:
def clean_name(s: str) -> str:
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged_sp = clean_cols(merged_sp)

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var = clean_name(y_var_raw)

w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# Lag of outcome
lag_y = f"lag_{y_var}"
merged_sp[lag_y] = lag_spatial(w, merged_sp[y_var])

# Lags of predictors
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f"lag_{var}"] = lag_spatial(w, merged_sp[var])

# Drop rows with missing spatial lags
lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars).copy()

year_dummies = pd.get_dummies(merged_sp_clean['Year'], prefix='Year', drop_first=True, dtype=float)
merged_sp_clean = pd.concat([merged_sp_clean, year_dummies], axis=1)

rhs = [lag_y] + X_vars + [f"lag_{v}" for v in X_vars] + list(year_dummies.columns)
formula = f"{y_var} ~ " + " + ".join(rhs)
print("Formula:", formula)

model_timefe_cluster = smf.ols(formula=formula, data=merged_sp_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_sp_clean["Precinct"]}
)

print(model_timefe_cluster.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\2406526920.py:35: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Formula: Budget_per_capita ~ lag_Budget_per_capita + MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1 + RAPE_per_capita_lag1 + FELONY_ASSAULT_per_capita_lag1 + BURGLARY_per_capita_lag1 + GRAND_LARCENY_per_capita_lag1 + GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1 + ROBBERY_per_capita_lag1 + Budget_per_capita_lag1 + minority_pct_lag1 + per_capita_income_lag1 + total_pop_lag1 + lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1 + lag_RAPE_per_capita_lag1 + lag_FELONY_ASSAULT_per_capita_lag1 + lag_BURGLARY_per_capita_lag1 + lag_GRAND_LARCENY_per_capita_lag1 + lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1 + lag_ROBBERY_per_capita_lag1 + lag_Budget_per_capita_lag1 + lag_minority_pct_lag1 + lag_per_capita_income_lag1 + lag_total_pop_lag1 + Year_2008 + Year_2009 + Year_2010 + Year_2011 + Year_2012 + Year_2013 + Year_2014 + Year_2015 + Year_2016 + Year_2017 + Year_2018 + Year_2019 + Year_2020 + Year_2021 + Year_2022 + Year_2023
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.968
Method:                 Least Squares   F-statistic:                     436.7
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           3.90e-71
Time:                        01:23:17   Log-Likelihood:                -4738.1
No. Observations:                1241   AIC:                             9556.
Df Residuals:                    1201   BIC:                             9761.
Df Model:                          39
Covariance Type:              cluster
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
Intercept                                             53.2182     16.480      3.229      0.001      20.917      85.519
lag_Budget_per_capita                                -14.4728      5.237     -2.763      0.006     -24.737      -4.208
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1         1.36e+04   9170.355      1.483      0.138   -4372.568    3.16e+04
RAPE_per_capita_lag1                                1.587e+04   4221.295      3.759      0.000    7594.205    2.41e+04
FELONY_ASSAULT_per_capita_lag1                      1395.7888    854.696      1.633      0.102    -279.384    3070.961
BURGLARY_per_capita_lag1                             333.0272    840.931      0.396      0.692   -1315.167    1981.222
GRAND_LARCENY_per_capita_lag1                        154.0616    374.019      0.412      0.680    -579.001     887.125
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1      -685.6425   1292.773     -0.530      0.596   -3219.432    1848.147
ROBBERY_per_capita_lag1                              -27.6983   1007.536     -0.027      0.978   -2002.433    1947.036
Budget_per_capita_lag1                                 0.8593      0.041     21.001      0.000       0.779       0.939
minority_pct_lag1                                     -0.5845      4.301     -0.136      0.892      -9.014       7.845
per_capita_income_lag1                              2.425e-05   6.02e-05      0.403      0.687   -9.37e-05       0.000
total_pop_lag1                                     -3.882e-05   1.62e-05     -2.391      0.017   -7.06e-05      -7e-06
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1    2.087e+05   8.95e+04      2.333      0.020    3.34e+04    3.84e+05
lag_RAPE_per_capita_lag1                            1.078e+04   3.65e+04      0.296      0.768   -6.07e+04    8.23e+04
lag_FELONY_ASSAULT_per_capita_lag1                  1.042e+04   4120.818      2.528      0.011    2339.120    1.85e+04
lag_BURGLARY_per_capita_lag1                        -1.39e+04   5956.494     -2.334      0.020   -2.56e+04   -2228.000
lag_GRAND_LARCENY_per_capita_lag1                   -187.5506    765.962     -0.245      0.807   -1688.809    1313.708
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1   1.02e+04   4952.813      2.059      0.040     488.622    1.99e+04
lag_ROBBERY_per_capita_lag1                         -2.01e+04   7104.155     -2.830      0.005    -3.4e+04   -6179.456
lag_Budget_per_capita_lag1                            14.8349      5.346      2.775      0.006       4.358      25.312
lag_minority_pct_lag1                                -17.4762     11.712     -1.492      0.136     -40.431       5.479
lag_per_capita_income_lag1                            -0.0003      0.000     -1.455      0.146      -0.001       0.000
lag_total_pop_lag1                                  2.439e-05   1.99e-05      1.228      0.220   -1.45e-05    6.33e-05
Year_2008                                             -8.1001      2.653     -3.054      0.002     -13.299      -2.901
Year_2009                                            -10.4039      2.832     -3.673      0.000     -15.955      -4.853
Year_2010                                             -7.9756      4.504     -1.771      0.077     -16.804       0.853
Year_2011                                             11.1308      3.037      3.665      0.000       5.178      17.083
Year_2012                                            -14.4750      4.705     -3.077      0.002     -23.696      -5.254
Year_2013                                             -2.9863      3.644     -0.820      0.412     -10.128       4.155
Year_2014                                             -7.6416      3.528     -2.166      0.030     -14.556      -0.727
Year_2015                                             -7.8156      3.879     -2.015      0.044     -15.418      -0.213
Year_2016                                             -6.3866      3.845     -1.661      0.097     -13.922       1.149
Year_2017                                             -3.9253      3.575     -1.098      0.272     -10.931       3.081
Year_2018                                              1.6189      3.530      0.459      0.646      -5.299       8.537
Year_2019                                             -6.9202      4.496     -1.539      0.124     -15.733       1.893
Year_2020                                             -6.2853      4.298     -1.462      0.144     -14.709       2.138
Year_2021                                             -8.3611      4.135     -2.022      0.043     -16.466      -0.256
Year_2022                                             -4.8887      3.513     -1.392      0.164     -11.774       1.996
Year_2023                                             -4.4300      3.389     -1.307      0.191     -11.072       2.212
==============================================================================
Omnibus:                      575.977   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           143435.321
Skew:                           0.935   Prob(JB):                         0.00
Kurtosis:                      55.635   Cond. No.                     2.68e+10
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 2.68e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 39, but rank is 34
  warnings.warn('covariance of constraints does not have full '

In [51]:
def clean_name(s: str) -> str:
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged = clean_cols(merged)              # clean all column names
merged = merged[merged["Year"] > 2006].copy()

X_vars_raw = [
    "MURDER & NON NEGL. MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND LARCENY_per_capita_lag1",
    "GRAND LARCENY OF MOTOR VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var  = clean_name(y_var_raw)

keep_cols = ["Precinct", "Year", y_var] + X_vars
df = merged[keep_cols].dropna().copy()

w = Queen.from_dataframe(merged.loc[df.index, ["geometry"]].join(df[["Precinct","Year"]]))
w.transform = 'r'

lag_y = f"lag_{y_var}"
df[lag_y] = lag_spatial(w, df[y_var])

for var in X_vars:
    df[var] = df[var].fillna(df[var].mean())
    df[f"lag_{var}"] = lag_spatial(w, df[var])

lag_cols = [lag_y] + [f"lag_{v}" for v in X_vars]
df = df.dropna(subset=[y_var] + lag_cols).copy()

year_dummies = pd.get_dummies(df["Year"], prefix="Year", drop_first=True, dtype=float)
prec_dummies = pd.get_dummies(df["Precinct"], prefix="Precinct", drop_first=True, dtype=float)

scaler_X = StandardScaler()
scaler_y = StandardScaler()

cont_X_cols = X_vars + lag_cols  
X_cont_scaled = pd.DataFrame(
    scaler_X.fit_transform(df[cont_X_cols]),
    columns=cont_X_cols,
    index=df.index
)

y_scaled = scaler_y.fit_transform(df[[y_var]]).ravel()
y_scaled = pd.Series(y_scaled, name=y_var, index=df.index)

# ---------------- Design matrix ----------------
X = pd.concat([X_cont_scaled, year_dummies, prec_dummies], axis=1)
X = sm.add_constant(X).astype(float)

# ---------------- Fit OLS with clustered SEs by Precinct ----------------
res = sm.OLS(y_scaled, X).fit(
    cov_type="cluster",
    cov_kwds={"groups": df["Precinct"]}  # one-way clustering by unit
)

print(res.summary())

coef_table = (
    pd.DataFrame({
        "beta_std": res.params,
        "se_cluster": res.bse,
        "z": res.tvalues,
        "pval": res.pvalues
    })
    .assign(
        is_dummy=lambda s: s.index.str.startswith(("Year_", "Precinct_")) | (s.index == "const")
    )
)
print("\nStandardized coefficients (continuous vars only), sorted by |beta|:\n")
print(coef_table.loc[~coef_table["is_dummy"]]
      .drop(columns="is_dummy")
      .sort_values("beta_std", key=lambda s: s.abs(), ascending=False)
      .round(4))

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\1555611789.py:37: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged.loc[df.index, ["geometry"]].join(df[["Precinct","Year"]]))
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.993
Model:                            OLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     166.9
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           1.67e-56
Time:                        01:23:38   Log-Likelihood:                 1320.4
No. Observations:                1224   AIC:                            -2419.
Df Residuals:                    1113   BIC:                            -1852.
Df Model:                         110
Covariance Type:              cluster
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
const                                                 20.4127      5.619      3.633      0.000       9.399      31.427
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1          -0.0191      0.014     -1.408      0.159      -0.046       0.008
RAPE_per_capita_lag1                                   0.0317      0.023      1.383      0.167      -0.013       0.077
FELONY_ASSAULT_per_capita_lag1                         0.0940      0.035      2.718      0.007       0.026       0.162
BURGLARY_per_capita_lag1                              -0.0205      0.016     -1.294      0.196      -0.051       0.011
GRAND_LARCENY_per_capita_lag1                          0.0505      0.027      1.883      0.060      -0.002       0.103
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1        -0.0133      0.011     -1.246      0.213      -0.034       0.008
ROBBERY_per_capita_lag1                               -0.0466      0.046     -1.018      0.309      -0.136       0.043
Budget_per_capita_lag1                                 0.4833      0.048     10.053      0.000       0.389       0.578
minority_pct_lag1                                     -0.0394      0.019     -2.118      0.034      -0.076      -0.003
per_capita_income_lag1                                -0.0330      0.023     -1.448      0.148      -0.078       0.012
total_pop_lag1                                        -0.0279      0.015     -1.839      0.066      -0.058       0.002
lag_Budget_per_capita                                -39.1760      4.948     -7.917      0.000     -48.875     -29.477
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1      -1.1302      0.563     -2.006      0.045      -2.234      -0.026
lag_RAPE_per_capita_lag1                               1.1116      1.023      1.086      0.277      -0.894       3.118
lag_FELONY_ASSAULT_per_capita_lag1                     4.6569      1.738      2.680      0.007       1.251       8.062
lag_BURGLARY_per_capita_lag1                          -0.5269      0.581     -0.906      0.365      -1.666       0.612
lag_GRAND_LARCENY_per_capita_lag1                      1.0698      1.409      0.759      0.448      -1.691       3.831
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1    -0.4315      0.324     -1.332      0.183      -1.066       0.203
lag_ROBBERY_per_capita_lag1                           -2.0880      2.365     -0.883      0.377      -6.724       2.548
lag_Budget_per_capita_lag1                            18.1645      3.719      4.884      0.000      10.875      25.454
lag_minority_pct_lag1                                 -1.0456      0.739     -1.415      0.157      -2.494       0.403
lag_per_capita_income_lag1                            -0.7311      0.891     -0.821      0.412      -2.477       1.015
lag_total_pop_lag1                                    -1.5168      0.875     -1.734      0.083      -3.231       0.197
Year_2008                                             -0.0186      0.018     -1.063      0.288      -0.053       0.016
Year_2009                                             -0.0281      0.020     -1.419      0.156      -0.067       0.011
Year_2010                                             -0.0139      0.026     -0.536      0.592      -0.065       0.037
Year_2011                                              0.0631      0.034      1.854      0.064      -0.004       0.130
Year_2012                                             -0.0237      0.030     -0.789      0.430      -0.082       0.035
Year_2013                                             -0.0038      0.024     -0.157      0.875      -0.051       0.044
Year_2014                                             -0.0223      0.026     -0.851      0.395      -0.074       0.029
Year_2015                                             -0.0124      0.025     -0.487      0.626      -0.062       0.037
Year_2016                                             -0.0093      0.025     -0.373      0.709      -0.058       0.040
Year_2017                                              0.0002      0.026      0.009      0.992      -0.050       0.051
Year_2018                                              0.0289      0.025      1.142      0.254      -0.021       0.078
Year_2019                                              0.0135      0.029      0.463      0.643      -0.044       0.071
Year_2020                                              0.0093      0.028      0.335      0.738      -0.045       0.064
Year_2021                                              0.0022      0.028      0.079      0.937      -0.052       0.057
Year_2022                                              0.0024      0.025      0.097      0.923      -0.047       0.051
Year_2023                                              0.0023      0.021      0.107      0.915      -0.040       0.044
Precinct_5                                             0.2758      0.854      0.323      0.747      -1.398       1.950
Precinct_6                                            -3.8021      0.558     -6.818      0.000      -4.895      -2.709
Precinct_7                                            -3.1859      2.565     -1.242      0.214      -8.213       1.841
Precinct_9                                            -4.0599      0.866     -4.687      0.000      -5.757      -2.362
Precinct_10                                           -6.5436      1.178     -5.557      0.000      -8.852      -4.236
Precinct_13                                          -12.3331      1.901     -6.489      0.000     -16.058      -8.608
Precinct_17                                          -38.5260      6.153     -6.261      0.000     -50.587     -26.465
Precinct_19                                          -34.2709      6.396     -5.358      0.000     -46.807     -21.735
Precinct_20                                          -38.6715      7.005     -5.520      0.000     -52.402     -24.941
Precinct_23                                            4.2238      6.715      0.629      0.529      -8.937      17.384
Precinct_24                                           -4.8185      5.152     -0.935      0.350     -14.915       5.278
Precinct_25                                           16.6034      9.233      1.798      0.072      -1.492      34.699
Precinct_26                                            5.6535      7.080      0.799      0.425      -8.223      19.530
Precinct_28                                            7.7601      7.529      1.031      0.303      -6.996      22.516
Precinct_30                                            3.8444      7.388      0.520      0.603     -10.637      18.325
Precinct_32                                           14.9690      8.211      1.823      0.068      -1.123      31.061
Precinct_33                                           -7.6294      7.230     -1.055      0.291     -21.801       6.542
Precinct_34                                          -18.0937      6.190     -2.923      0.003     -30.226      -5.962
Precinct_40                                           -5.6187      9.330     -0.602      0.547     -23.905      12.668
Precinct_41                                          -10.3178      9.173     -1.125      0.261     -28.296       7.660
Precinct_42                                          -12.6022      8.886     -1.418      0.156     -30.018       4.814
Precinct_43                                          -14.1842      8.089     -1.754      0.080     -30.038       1.670
Precinct_44                                          -12.8118      9.001     -1.423      0.155     -30.454       4.830
Precinct_45                                          -39.6296      7.081     -5.596      0.000     -53.509     -25.750
Precinct_46                                          -18.3885      8.519     -2.159      0.031     -35.085      -1.692
Precinct_47                                          -32.3397      7.188     -4.499      0.000     -46.427     -18.252
Precinct_48                                          -22.8659      8.057     -2.838      0.005     -38.656      -7.075
Precinct_49                                          -28.1031      7.825     -3.592      0.000     -43.439     -12.767
Precinct_50                                          -33.7397      7.515     -4.489      0.000     -48.470     -19.010
Precinct_52                                          -25.6515      7.369     -3.481      0.000     -40.094     -11.209
Precinct_60                                          -41.4072      7.578     -5.464      0.000     -56.260     -26.554
Precinct_61                                          -56.1246      9.305     -6.032      0.000     -74.362     -37.887
Precinct_62                                          -46.3255      8.124     -5.702      0.000     -62.248     -30.403
Precinct_63                                          -30.6272      6.583     -4.653      0.000     -43.529     -17.725
Precinct_66                                          -46.4833      8.180     -5.682      0.000     -62.516     -30.450
Precinct_67                                          -18.7590      6.507     -2.883      0.004     -31.513      -6.005
Precinct_68                                          -50.0107      8.658     -5.776      0.000     -66.980     -33.042
Precinct_69                                          -16.3450      6.562     -2.491      0.013     -29.205      -3.485
Precinct_70                                          -30.6646      6.356     -4.825      0.000     -43.122     -18.207
Precinct_71                                          -16.0472      5.529     -2.902      0.004     -26.884      -5.210
Precinct_72                                          -27.0321      5.754     -4.698      0.000     -38.309     -15.755
Precinct_73                                          -10.5037      7.290     -1.441      0.150     -24.792       3.785
Precinct_75                                          -27.3118      7.125     -3.833      0.000     -41.277     -13.347
Precinct_76                                            5.7548      3.079      1.869      0.062      -0.280      11.790
Precinct_77                                           -2.1303      6.291     -0.339      0.735     -14.460      10.199
Precinct_78                                           -2.4617      4.073     -0.604      0.546     -10.445       5.521
Precinct_79                                           -5.4473      6.105     -0.892      0.372     -17.414       6.519
Precinct_81                                           -4.9697      7.148     -0.695      0.487     -18.980       9.040
Precinct_83                                          -14.7637      7.107     -2.077      0.038     -28.692      -0.835
Precinct_84                                           18.2222      3.561      5.117      0.000      11.242      25.202
Precinct_88                                            3.3375      4.286      0.779      0.436      -5.062      11.737
Precinct_90                                          -12.5008      5.318     -2.351      0.019     -22.924      -2.078
Precinct_94                                          -18.3125      4.245     -4.314      0.000     -26.632      -9.993
Precinct_100                                          -6.5666      5.820     -1.128      0.259     -17.974       4.840
Precinct_101                                           3.0145      6.012      0.501      0.616      -8.769      14.798
Precinct_102                                         -37.4717      7.504     -4.994      0.000     -52.179     -22.764
Precinct_103                                         -36.6319      7.404     -4.948      0.000     -51.143     -22.121
Precinct_104                                         -39.0392      7.420     -5.261      0.000     -53.582     -24.496
Precinct_105                                         -35.8739      7.114     -5.043      0.000     -49.817     -21.930
Precinct_106                                         -30.8753      7.512     -4.110      0.000     -45.598     -16.153
Precinct_107                                         -42.1361      7.758     -5.431      0.000     -57.341     -26.931
Precinct_108                                         -50.9043      8.667     -5.873      0.000     -67.892     -33.917
Precinct_109                                         -48.5232      8.332     -5.824      0.000     -64.854     -32.192
Precinct_110                                         -49.3330      8.512     -5.796      0.000     -66.016     -32.650
Precinct_111                                         -44.4136      7.791     -5.700      0.000     -59.684     -29.143
Precinct_112                                         -46.8409      8.319     -5.631      0.000     -63.146     -30.536
Precinct_114                                         -45.5712      7.521     -6.059      0.000     -60.312     -30.830
Precinct_115                                         -51.2635      8.783     -5.837      0.000     -68.478     -34.049
Precinct_120                                         -18.1270      5.313     -3.412      0.001     -28.540      -7.714
Precinct_122                                         -25.1293      5.844     -4.300      0.000     -36.584     -13.675
Precinct_123                                         -38.2166      7.216     -5.296      0.000     -52.359     -24.074
==============================================================================
Omnibus:                      294.760   Durbin-Watson:                   2.180
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14411.945
Skew:                           0.105   Prob(JB):                         0.00
Kurtosis:                      19.809   Cond. No.                     4.34e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 4.34e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Standardized coefficients (continuous vars only), sorted by |beta|:

                                                    beta_std  se_cluster  \
lag_Budget_per_capita                               -39.1760      4.9484
lag_Budget_per_capita_lag1                           18.1645      3.7191
lag_FELONY_ASSAULT_per_capita_lag1                    4.6569      1.7375
lag_ROBBERY_per_capita_lag1                          -2.0880      2.3652
lag_total_pop_lag1                                   -1.5168      0.8746
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1     -1.1302      0.5634
lag_RAPE_per_capita_lag1                              1.1116      1.0234
lag_GRAND_LARCENY_per_capita_lag1                     1.0698      1.4088
lag_minority_pct_lag1                                -1.0456      0.7390
lag_per_capita_income_lag1                           -0.7311      0.8908
lag_BURGLARY_per_capita_lag1                         -0.5269      0.5813
Budget_per_capita_lag1                                0.4833      0.0481
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1   -0.4315      0.3240
FELONY_ASSAULT_per_capita_lag1                        0.0940      0.0346
GRAND_LARCENY_per_capita_lag1                         0.0505      0.0268
ROBBERY_per_capita_lag1                              -0.0466      0.0457
minority_pct_lag1                                    -0.0394      0.0186
per_capita_income_lag1                               -0.0330      0.0228
RAPE_per_capita_lag1                                  0.0317      0.0229
total_pop_lag1                                       -0.0279      0.0152
BURGLARY_per_capita_lag1                             -0.0205      0.0158
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1         -0.0191      0.0136
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1       -0.0133      0.0107

                                                          z    pval
lag_Budget_per_capita                               -7.9169  0.0000
lag_Budget_per_capita_lag1                           4.8842  0.0000
lag_FELONY_ASSAULT_per_capita_lag1                   2.6802  0.0074
lag_ROBBERY_per_capita_lag1                         -0.8828  0.3773
lag_total_pop_lag1                                  -1.7342  0.0829
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1    -2.0061  0.0448
lag_RAPE_per_capita_lag1                             1.0861  0.2774
lag_GRAND_LARCENY_per_capita_lag1                    0.7594  0.4476
lag_minority_pct_lag1                               -1.4149  0.1571
lag_per_capita_income_lag1                          -0.8207  0.4118
lag_BURGLARY_per_capita_lag1                        -0.9064  0.3647
Budget_per_capita_lag1                              10.0535  0.0000
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1  -1.3319  0.1829
FELONY_ASSAULT_per_capita_lag1                       2.7178  0.0066
GRAND_LARCENY_per_capita_lag1                        1.8830  0.0597
ROBBERY_per_capita_lag1                             -1.0180  0.3087
minority_pct_lag1                                   -2.1180  0.0342
per_capita_income_lag1                              -1.4478  0.1477
RAPE_per_capita_lag1                                 1.3832  0.1666
total_pop_lag1                                      -1.8387  0.0660
BURGLARY_per_capita_lag1                            -1.2940  0.1957
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1        -1.4078  0.1592
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1      -1.2461  0.2127

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 110, but rank is 39
  warnings.warn('covariance of constraints does not have full '

In [52]:
def clean_name(s: str) -> str:
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged_sp = clean_cols(merged_sp)

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var = clean_name(y_var_raw)

w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# Lag of outcome
lag_y = f"lag_{y_var}"
merged_sp[lag_y] = lag_spatial(w, merged_sp[y_var])

# Lags of predictors
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f"lag_{var}"] = lag_spatial(w, merged_sp[var])

lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars).copy()

year_dummies = pd.get_dummies(
    merged_sp_clean['Year'], 
    prefix='Year', 
    drop_first=True, 
    dtype=float
)
merged_sp_clean = pd.concat([merged_sp_clean, year_dummies], axis=1)

rhs = [lag_y] + X_vars + [f"lag_{v}" for v in X_vars] + list(year_dummies.columns)
formula = f"{y_var} ~ " + " + ".join(rhs)
print("Formula:", formula)

model_timefe_cluster = smf.ols(formula=formula, data=merged_sp_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_sp_clean["Precinct"]}
)

print(model_timefe_cluster.summary())

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\1872542977.py:30: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Formula: Budget_per_capita ~ lag_Budget_per_capita + Violent_Crime_per_capita_lag1 + Property_Crime_per_capita_lag1 + Budget_per_capita_lag1 + minority_pct_lag1 + per_capita_income_lag1 + total_pop_lag1 + lag_Violent_Crime_per_capita_lag1 + lag_Property_Crime_per_capita_lag1 + lag_Budget_per_capita_lag1 + lag_minority_pct_lag1 + lag_per_capita_income_lag1 + lag_total_pop_lag1 + Year_2008 + Year_2009 + Year_2010 + Year_2011 + Year_2012 + Year_2013 + Year_2014 + Year_2015 + Year_2016 + Year_2017 + Year_2018 + Year_2019 + Year_2020 + Year_2021 + Year_2022 + Year_2023
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.963
Method:                 Least Squares   F-statistic:                     896.4
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           5.34e-80
Time:                        01:24:00   Log-Likelihood:                -4830.2
No. Observations:                1241   AIC:                             9720.
Df Residuals:                    1211   BIC:                             9874.
Df Model:                          29
Covariance Type:              cluster
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                             39.6797     13.048      3.041      0.002      14.106      65.253
lag_Budget_per_capita                 -7.5782      3.337     -2.271      0.023     -14.119      -1.037
Violent_Crime_per_capita_lag1       1527.1970    501.334      3.046      0.002     544.600    2509.794
Property_Crime_per_capita_lag1       288.9071    266.859      1.083      0.279    -234.127     811.941
Budget_per_capita_lag1                 0.8671      0.045     19.217      0.000       0.779       0.956
minority_pct_lag1                      1.1342      4.002      0.283      0.777      -6.710       8.979
per_capita_income_lag1              3.453e-05   5.32e-05      0.649      0.516   -6.97e-05       0.000
total_pop_lag1                     -2.976e-05   1.28e-05     -2.320      0.020   -5.49e-05   -4.61e-06
lag_Violent_Crime_per_capita_lag1   -157.2842    570.822     -0.276      0.783   -1276.074     961.506
lag_Property_Crime_per_capita_lag1 -1877.7718    747.894     -2.511      0.012   -3343.618    -411.926
lag_Budget_per_capita_lag1             7.8008      3.410      2.288      0.022       1.117      14.485
lag_minority_pct_lag1                -22.9042     13.068     -1.753      0.080     -48.516       2.708
lag_per_capita_income_lag1            -0.0001      0.000     -0.944      0.345      -0.000       0.000
lag_total_pop_lag1                  4.182e-06   1.73e-05      0.241      0.809   -2.98e-05    3.82e-05
Year_2008                             -9.5515      2.647     -3.609      0.000     -14.739      -4.364
Year_2009                            -12.2425      2.654     -4.612      0.000     -17.445      -7.040
Year_2010                             -8.7486      4.915     -1.780      0.075     -18.382       0.885
Year_2011                             13.4694      2.754      4.891      0.000       8.072      18.867
Year_2012                            -16.2706      4.632     -3.513      0.000     -25.348      -7.193
Year_2013                             -2.5570      3.884     -0.658      0.510     -10.170       5.056
Year_2014                             -8.4965      3.343     -2.541      0.011     -15.049      -1.944
Year_2015                             -8.3599      3.925     -2.130      0.033     -16.052      -0.668
Year_2016                             -6.4583      3.888     -1.661      0.097     -14.078       1.162
Year_2017                             -3.2760      3.724     -0.880      0.379     -10.575       4.023
Year_2018                              3.0676      3.808      0.806      0.421      -4.396      10.531
Year_2019                             -6.1048      4.548     -1.342      0.179     -15.019       2.809
Year_2020                             -5.4697      4.422     -1.237      0.216     -14.137       3.198
Year_2021                             -8.2326      4.539     -1.814      0.070     -17.128       0.663
Year_2022                             -4.4703      3.929     -1.138      0.255     -12.171       3.230
Year_2023                             -4.8885      3.552     -1.376      0.169     -11.850       2.073
==============================================================================
Omnibus:                      626.075   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           238852.047
Skew:                           1.027   Prob(JB):                         0.00
Kurtosis:                      70.934   Cond. No.                     2.57e+08
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 2.57e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 29, but rank is 25
  warnings.warn('covariance of constraints does not have full '

In [53]:
def clean_name(s: str) -> str:
    """Clean column names for formula safety"""
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged_sp = clean_cols(merged_sp)

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var = clean_name(y_var_raw)

w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

# Lag of outcome
lag_y = f"lag_{y_var}"
merged_sp[lag_y] = lag_spatial(w, merged_sp[y_var])

# Lags of predictors
for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f"lag_{var}"] = lag_spatial(w, merged_sp[var])

lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars + ['Year','Precinct']).copy()

year_dummies = pd.get_dummies(
    merged_sp_clean['Year'],
    prefix='Year',
    drop_first=True,
    dtype=float
)
merged_sp_clean = pd.concat([merged_sp_clean, year_dummies], axis=1)

cont_cols = [y_var] + X_vars + lag_vars
scaler = StandardScaler()
merged_sp_clean[[c + "_z" for c in cont_cols]] = scaler.fit_transform(merged_sp_clean[cont_cols])

y_var_z   = y_var + "_z"
lag_y_z   = lag_y + "_z"
X_vars_z  = [v + "_z" for v in X_vars]
lag_vars_z= [lv + "_z" for lv in lag_vars]

rhs = [lag_y_z] + X_vars_z + lag_vars_z + list(year_dummies.columns)
formula = f"{y_var_z} ~ " + " + ".join(rhs)
print("Formula:", formula)

model_timefe_cluster = smf.ols(formula=formula, data=merged_sp_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_sp_clean["Precinct"]}
)

print(model_timefe_cluster.summary())

coef_series = model_timefe_cluster.params
se_series   = model_timefe_cluster.bse
t_series    = model_timefe_cluster.tvalues
p_series    = model_timefe_cluster.pvalues

coef_table = (
    pd.DataFrame({
        "beta_std": coef_series,
        "se_cluster": se_series,
        "z": t_series,
        "pval": p_series
    })
    .assign(is_dummy=lambda s: s.index.str.startswith("Year_") | (s.index=="Intercept"))
)

print("\nStandardized coefficients (continuous vars only), sorted by |beta|:\n")
print(
    coef_table.loc[~coef_table["is_dummy"]]
              .drop(columns="is_dummy")
              .sort_values("beta_std", key=lambda s: s.abs(), ascending=False)
              .round(4)
)


def back_transform_beta(beta_std: float, x_name: str) -> float:
    """
    Convert standardized beta back to original units for predictor x_name.
    beta_unstd = beta_std * (sd_Y / sd_X)
    """
    # map names to scaler columns
    col_map = {c+"_z": i for i, c in enumerate(cont_cols)}
    sd_Y = scaler.scale_[cont_cols.index(y_var)]
    sd_X = scaler.scale_[cont_cols.index(x_name)]
    return float(beta_std * (sd_Y / sd_X))

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\4189272711.py:31: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Formula: Budget_per_capita_z ~ lag_Budget_per_capita_z + Violent_Crime_per_capita_lag1_z + Property_Crime_per_capita_lag1_z + Budget_per_capita_lag1_z + minority_pct_lag1_z + per_capita_income_lag1_z + total_pop_lag1_z + lag_Violent_Crime_per_capita_lag1_z + lag_Property_Crime_per_capita_lag1_z + lag_Budget_per_capita_lag1_z + lag_minority_pct_lag1_z + lag_per_capita_income_lag1_z + lag_total_pop_lag1_z + lag_Budget_per_capita_z + Year_2008 + Year_2009 + Year_2010 + Year_2011 + Year_2012 + Year_2013 + Year_2014 + Year_2015 + Year_2016 + Year_2017 + Year_2018 + Year_2019 + Year_2020 + Year_2021 + Year_2022 + Year_2023
                             OLS Regression Results
===============================================================================
Dep. Variable:     Budget_per_capita_z   R-squared:                       0.964
Model:                             OLS   Adj. R-squared:                  0.963
Method:                  Least Squares   F-statistic:                     1094.
Date:                 Mon, 13 Oct 2025   Prob (F-statistic):           2.86e-84
Time:                         01:24:20   Log-Likelihood:                 295.91
No. Observations:                 1241   AIC:                            -531.8
Df Residuals:                     1211   BIC:                            -378.1
Df Model:                           29
Covariance Type:               cluster
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                                0.0838      0.054      1.545      0.122      -0.023       0.190
lag_Budget_per_capita_z                 -5.5728      2.454     -2.271      0.023     -10.383      -0.763
Violent_Crime_per_capita_lag1_z          0.0723      0.024      3.046      0.002       0.026       0.119
Property_Crime_per_capita_lag1_z         0.0170      0.016      1.083      0.279      -0.014       0.048
Budget_per_capita_lag1_z                 0.8685      0.045     19.217      0.000       0.780       0.957
minority_pct_lag1_z                      0.0033      0.012      0.283      0.777      -0.019       0.026
per_capita_income_lag1_z                 0.0081      0.013      0.649      0.516      -0.016       0.033
total_pop_lag1_z                        -0.0293      0.013     -2.320      0.020      -0.054      -0.005
lag_Violent_Crime_per_capita_lag1_z     -0.0054      0.020     -0.276      0.783      -0.044       0.033
lag_Property_Crime_per_capita_lag1_z    -0.0864      0.034     -2.511      0.012      -0.154      -0.019
lag_Budget_per_capita_lag1_z             5.6805      2.483      2.288      0.022       0.813      10.548
lag_minority_pct_lag1_z                 -0.0381      0.022     -1.753      0.080      -0.081       0.005
lag_per_capita_income_lag1_z            -0.0201      0.021     -0.944      0.345      -0.062       0.022
lag_total_pop_lag1_z                     0.0029      0.012      0.241      0.809      -0.021       0.026
Year_2008                               -0.1535      0.043     -3.609      0.000      -0.237      -0.070
Year_2009                               -0.1968      0.043     -4.612      0.000      -0.280      -0.113
Year_2010                               -0.1406      0.079     -1.780      0.075      -0.295       0.014
Year_2011                                0.2165      0.044      4.891      0.000       0.130       0.303
Year_2012                               -0.2615      0.074     -3.513      0.000      -0.407      -0.116
Year_2013                               -0.0411      0.062     -0.658      0.510      -0.163       0.081
Year_2014                               -0.1366      0.054     -2.541      0.011      -0.242      -0.031
Year_2015                               -0.1344      0.063     -2.130      0.033      -0.258      -0.011
Year_2016                               -0.1038      0.062     -1.661      0.097      -0.226       0.019
Year_2017                               -0.0527      0.060     -0.880      0.379      -0.170       0.065
Year_2018                                0.0493      0.061      0.806      0.421      -0.071       0.169
Year_2019                               -0.0981      0.073     -1.342      0.179      -0.241       0.045
Year_2020                               -0.0879      0.071     -1.237      0.216      -0.227       0.051
Year_2021                               -0.1323      0.073     -1.814      0.070      -0.275       0.011
Year_2022                               -0.0719      0.063     -1.138      0.255      -0.196       0.052
Year_2023                               -0.0786      0.057     -1.376      0.169      -0.190       0.033
==============================================================================
Omnibus:                      626.075   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           238852.047
Skew:                           1.027   Prob(JB):                         0.00
Kurtosis:                      70.934   Cond. No.                         266.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Standardized coefficients (continuous vars only), sorted by |beta|:

                                      beta_std  se_cluster        z    pval
lag_Budget_per_capita_lag1_z            5.6805      2.4832   2.2875  0.0222
lag_Budget_per_capita_z                -5.5728      2.4541  -2.2708  0.0232
Budget_per_capita_lag1_z                0.8685      0.0452  19.2173  0.0000
lag_Property_Crime_per_capita_lag1_z   -0.0864      0.0344  -2.5107  0.0120
Violent_Crime_per_capita_lag1_z         0.0723      0.0237   3.0463  0.0023
lag_minority_pct_lag1_z                -0.0381      0.0218  -1.7528  0.0796
total_pop_lag1_z                       -0.0293      0.0126  -2.3196  0.0204
lag_per_capita_income_lag1_z           -0.0201      0.0213  -0.9436  0.3454
Property_Crime_per_capita_lag1_z        0.0170      0.0157   1.0826  0.2790
per_capita_income_lag1_z                0.0081      0.0126   0.6490  0.5164
lag_Violent_Crime_per_capita_lag1_z    -0.0054      0.0196  -0.2755  0.7829
minority_pct_lag1_z                     0.0033      0.0116   0.2834  0.7769
lag_total_pop_lag1_z                    0.0029      0.0119   0.2412  0.8094

In [54]:
def clean_name(s: str) -> str:
    """Clean column names for formula safety"""
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged_sp = clean_cols(merged_sp)

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var = clean_name(y_var_raw)

w = Queen.from_dataframe(merged_sp)
w.transform = 'r'

lag_y = f"lag_{y_var}"
merged_sp[lag_y] = lag_spatial(w, merged_sp[y_var])

for var in X_vars:
    merged_sp[var] = merged_sp[var].fillna(merged_sp[var].mean())
    merged_sp[f"lag_{var}"] = lag_spatial(w, merged_sp[var])

lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
merged_sp_clean = merged_sp.dropna(subset=[y_var] + lag_vars + ['Year','Precinct']).copy()

year_dummies = pd.get_dummies(
    merged_sp_clean['Year'],
    prefix='Year',
    drop_first=True,
    dtype=float
)
merged_sp_clean = pd.concat([merged_sp_clean, year_dummies], axis=1)

cont_cols = [y_var] + X_vars + lag_vars
scaler = StandardScaler()
merged_sp_clean[cont_cols] = scaler.fit_transform(merged_sp_clean[cont_cols])

rhs = [lag_y] + X_vars + lag_vars + list(year_dummies.columns)
formula = f"{y_var} ~ " + " + ".join(rhs)
print("Formula:", formula)

model_timefe_cluster = smf.ols(formula=formula, data=merged_sp_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_sp_clean["Precinct"]}
)

print(model_timefe_cluster.summary())

coef_table = (
    pd.DataFrame({
        "beta_std": model_timefe_cluster.params,
        "se_cluster": model_timefe_cluster.bse,
        "z": model_timefe_cluster.tvalues,
        "pval": model_timefe_cluster.pvalues
    })
    .assign(is_dummy=lambda s: s.index.str.startswith("Year_") | (s.index=="Intercept"))
)

print("\nStandardized coefficients (continuous vars only), sorted by |beta|:\n")
print(
    coef_table.loc[~coef_table["is_dummy"]]
              .drop(columns="is_dummy")
              .sort_values("beta_std", key=lambda s: s.abs(), ascending=False)
              .round(4)
)

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\1581840394.py:31: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(merged_sp)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Formula: Budget_per_capita ~ lag_Budget_per_capita + Violent_Crime_per_capita_lag1 + Property_Crime_per_capita_lag1 + Budget_per_capita_lag1 + minority_pct_lag1 + per_capita_income_lag1 + total_pop_lag1 + lag_Violent_Crime_per_capita_lag1 + lag_Property_Crime_per_capita_lag1 + lag_Budget_per_capita_lag1 + lag_minority_pct_lag1 + lag_per_capita_income_lag1 + lag_total_pop_lag1 + lag_Budget_per_capita + Year_2008 + Year_2009 + Year_2010 + Year_2011 + Year_2012 + Year_2013 + Year_2014 + Year_2015 + Year_2016 + Year_2017 + Year_2018 + Year_2019 + Year_2020 + Year_2021 + Year_2022 + Year_2023
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.963
Method:                 Least Squares   F-statistic:                     1094.
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           2.86e-84
Time:                        01:24:42   Log-Likelihood:                 295.91
No. Observations:                1241   AIC:                            -531.8
Df Residuals:                    1211   BIC:                            -378.1
Df Model:                          29
Covariance Type:              cluster
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                              0.0838      0.054      1.545      0.122      -0.023       0.190
lag_Budget_per_capita                 -5.5728      2.454     -2.271      0.023     -10.383      -0.763
Violent_Crime_per_capita_lag1          0.0723      0.024      3.046      0.002       0.026       0.119
Property_Crime_per_capita_lag1         0.0170      0.016      1.083      0.279      -0.014       0.048
Budget_per_capita_lag1                 0.8685      0.045     19.217      0.000       0.780       0.957
minority_pct_lag1                      0.0033      0.012      0.283      0.777      -0.019       0.026
per_capita_income_lag1                 0.0081      0.013      0.649      0.516      -0.016       0.033
total_pop_lag1                        -0.0293      0.013     -2.320      0.020      -0.054      -0.005
lag_Violent_Crime_per_capita_lag1     -0.0054      0.020     -0.276      0.783      -0.044       0.033
lag_Property_Crime_per_capita_lag1    -0.0864      0.034     -2.511      0.012      -0.154      -0.019
lag_Budget_per_capita_lag1             5.6805      2.483      2.288      0.022       0.813      10.548
lag_minority_pct_lag1                 -0.0381      0.022     -1.753      0.080      -0.081       0.005
lag_per_capita_income_lag1            -0.0201      0.021     -0.944      0.345      -0.062       0.022
lag_total_pop_lag1                     0.0029      0.012      0.241      0.809      -0.021       0.026
Year_2008                             -0.1535      0.043     -3.609      0.000      -0.237      -0.070
Year_2009                             -0.1968      0.043     -4.612      0.000      -0.280      -0.113
Year_2010                             -0.1406      0.079     -1.780      0.075      -0.295       0.014
Year_2011                              0.2165      0.044      4.891      0.000       0.130       0.303
Year_2012                             -0.2615      0.074     -3.513      0.000      -0.407      -0.116
Year_2013                             -0.0411      0.062     -0.658      0.510      -0.163       0.081
Year_2014                             -0.1366      0.054     -2.541      0.011      -0.242      -0.031
Year_2015                             -0.1344      0.063     -2.130      0.033      -0.258      -0.011
Year_2016                             -0.1038      0.062     -1.661      0.097      -0.226       0.019
Year_2017                             -0.0527      0.060     -0.880      0.379      -0.170       0.065
Year_2018                              0.0493      0.061      0.806      0.421      -0.071       0.169
Year_2019                             -0.0981      0.073     -1.342      0.179      -0.241       0.045
Year_2020                             -0.0879      0.071     -1.237      0.216      -0.227       0.051
Year_2021                             -0.1323      0.073     -1.814      0.070      -0.275       0.011
Year_2022                             -0.0719      0.063     -1.138      0.255      -0.196       0.052
Year_2023                             -0.0786      0.057     -1.376      0.169      -0.190       0.033
==============================================================================
Omnibus:                      626.075   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           238852.047
Skew:                           1.027   Prob(JB):                         0.00
Kurtosis:                      70.934   Cond. No.                         266.
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)

Standardized coefficients (continuous vars only), sorted by |beta|:

                                    beta_std  se_cluster        z    pval
lag_Budget_per_capita_lag1            5.6805      2.4832   2.2875  0.0222
lag_Budget_per_capita                -5.5728      2.4541  -2.2708  0.0232
Budget_per_capita_lag1                0.8685      0.0452  19.2173  0.0000
lag_Property_Crime_per_capita_lag1   -0.0864      0.0344  -2.5107  0.0120
Violent_Crime_per_capita_lag1         0.0723      0.0237   3.0463  0.0023
lag_minority_pct_lag1                -0.0381      0.0218  -1.7528  0.0796
total_pop_lag1                       -0.0293      0.0126  -2.3196  0.0204
lag_per_capita_income_lag1           -0.0201      0.0213  -0.9436  0.3454
Property_Crime_per_capita_lag1        0.0170      0.0157   1.0826  0.2790
per_capita_income_lag1                0.0081      0.0126   0.6490  0.5164
lag_Violent_Crime_per_capita_lag1    -0.0054      0.0196  -0.2755  0.7829
minority_pct_lag1                     0.0033      0.0116   0.2834  0.7769
lag_total_pop_lag1                    0.0029      0.0119   0.2412  0.8094

In [55]:
def clean_name(s: str) -> str:
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf = precincts_gdf.rename(columns={"precinct": "Precinct"})

merged = precincts_gdf.merge(pre_ts_analysis, on="Precinct")
merged = clean_cols(merged)
merged = merged[merged["Year"] > 2006].copy()

X_vars_raw = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1",
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var  = clean_name(y_var_raw)

keep_cols = ["Precinct", "Year", "geometry", y_var] + X_vars
df = merged[keep_cols].dropna().copy()


w = Queen.from_dataframe(df)
w.transform = 'r'

lag_y = f"lag_{y_var}"
df[lag_y] = lag_spatial(w, df[y_var])

for v in X_vars:
    if df[v].isna().any():
        df[v] = df[v].fillna(df[v].mean())
    df[f"lag_{v}"] = lag_spatial(w, df[v])

lag_cols = [lag_y] + [f"lag_{v}" for v in X_vars]
df = df.dropna(subset=[y_var] + lag_cols).copy()

year_dummies = pd.get_dummies(df["Year"], prefix="Year", drop_first=True, dtype=float)
prec_dummies = pd.get_dummies(df["Precinct"], prefix="Precinct", drop_first=True, dtype=float)


scaler_X = StandardScaler()
scaler_y = StandardScaler()

cont_X_cols = X_vars + lag_cols  

X_cont_scaled = pd.DataFrame(
    scaler_X.fit_transform(df[cont_X_cols]),
    columns=cont_X_cols,
    index=df.index
)

y_scaled = scaler_y.fit_transform(df[[y_var]]).ravel()
y_scaled = pd.Series(y_scaled, name=y_var, index=df.index)

X = pd.concat([X_cont_scaled, year_dummies, prec_dummies], axis=1)
X = sm.add_constant(X).astype(float)


print(res.summary())

coef_table = (
    pd.DataFrame({
        "beta_std": res.params,
        "se_cluster": res.bse,
        "z": res.tvalues,
        "pval": res.pvalues
    })
    .assign(
        is_dummy=lambda s: s.index.str.startswith(("Year_", "Precinct_")) | (s.index == "const")
    )
)

print("\nStandardized coefficients (continuous vars only), sorted by |beta|:\n")
print(
    coef_table.loc[~coef_table["is_dummy"]]
              .drop(columns="is_dummy")
              .sort_values("beta_std", key=lambda s: s.abs(), ascending=False)
              .round(4)
)

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\194658299.py:33: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(df)

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.993
Model:                            OLS   Adj. R-squared:                  0.993
Method:                 Least Squares   F-statistic:                     166.9
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           1.67e-56
Time:                        01:25:02   Log-Likelihood:                 1320.4
No. Observations:                1224   AIC:                            -2419.
Df Residuals:                    1113   BIC:                            -1852.
Df Model:                         110
Covariance Type:              cluster
======================================================================================================================
                                                         coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------
const                                                 20.4127      5.619      3.633      0.000       9.399      31.427
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1          -0.0191      0.014     -1.408      0.159      -0.046       0.008
RAPE_per_capita_lag1                                   0.0317      0.023      1.383      0.167      -0.013       0.077
FELONY_ASSAULT_per_capita_lag1                         0.0940      0.035      2.718      0.007       0.026       0.162
BURGLARY_per_capita_lag1                              -0.0205      0.016     -1.294      0.196      -0.051       0.011
GRAND_LARCENY_per_capita_lag1                          0.0505      0.027      1.883      0.060      -0.002       0.103
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1        -0.0133      0.011     -1.246      0.213      -0.034       0.008
ROBBERY_per_capita_lag1                               -0.0466      0.046     -1.018      0.309      -0.136       0.043
Budget_per_capita_lag1                                 0.4833      0.048     10.053      0.000       0.389       0.578
minority_pct_lag1                                     -0.0394      0.019     -2.118      0.034      -0.076      -0.003
per_capita_income_lag1                                -0.0330      0.023     -1.448      0.148      -0.078       0.012
total_pop_lag1                                        -0.0279      0.015     -1.839      0.066      -0.058       0.002
lag_Budget_per_capita                                -39.1760      4.948     -7.917      0.000     -48.875     -29.477
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1      -1.1302      0.563     -2.006      0.045      -2.234      -0.026
lag_RAPE_per_capita_lag1                               1.1116      1.023      1.086      0.277      -0.894       3.118
lag_FELONY_ASSAULT_per_capita_lag1                     4.6569      1.738      2.680      0.007       1.251       8.062
lag_BURGLARY_per_capita_lag1                          -0.5269      0.581     -0.906      0.365      -1.666       0.612
lag_GRAND_LARCENY_per_capita_lag1                      1.0698      1.409      0.759      0.448      -1.691       3.831
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1    -0.4315      0.324     -1.332      0.183      -1.066       0.203
lag_ROBBERY_per_capita_lag1                           -2.0880      2.365     -0.883      0.377      -6.724       2.548
lag_Budget_per_capita_lag1                            18.1645      3.719      4.884      0.000      10.875      25.454
lag_minority_pct_lag1                                 -1.0456      0.739     -1.415      0.157      -2.494       0.403
lag_per_capita_income_lag1                            -0.7311      0.891     -0.821      0.412      -2.477       1.015
lag_total_pop_lag1                                    -1.5168      0.875     -1.734      0.083      -3.231       0.197
Year_2008                                             -0.0186      0.018     -1.063      0.288      -0.053       0.016
Year_2009                                             -0.0281      0.020     -1.419      0.156      -0.067       0.011
Year_2010                                             -0.0139      0.026     -0.536      0.592      -0.065       0.037
Year_2011                                              0.0631      0.034      1.854      0.064      -0.004       0.130
Year_2012                                             -0.0237      0.030     -0.789      0.430      -0.082       0.035
Year_2013                                             -0.0038      0.024     -0.157      0.875      -0.051       0.044
Year_2014                                             -0.0223      0.026     -0.851      0.395      -0.074       0.029
Year_2015                                             -0.0124      0.025     -0.487      0.626      -0.062       0.037
Year_2016                                             -0.0093      0.025     -0.373      0.709      -0.058       0.040
Year_2017                                              0.0002      0.026      0.009      0.992      -0.050       0.051
Year_2018                                              0.0289      0.025      1.142      0.254      -0.021       0.078
Year_2019                                              0.0135      0.029      0.463      0.643      -0.044       0.071
Year_2020                                              0.0093      0.028      0.335      0.738      -0.045       0.064
Year_2021                                              0.0022      0.028      0.079      0.937      -0.052       0.057
Year_2022                                              0.0024      0.025      0.097      0.923      -0.047       0.051
Year_2023                                              0.0023      0.021      0.107      0.915      -0.040       0.044
Precinct_5                                             0.2758      0.854      0.323      0.747      -1.398       1.950
Precinct_6                                            -3.8021      0.558     -6.818      0.000      -4.895      -2.709
Precinct_7                                            -3.1859      2.565     -1.242      0.214      -8.213       1.841
Precinct_9                                            -4.0599      0.866     -4.687      0.000      -5.757      -2.362
Precinct_10                                           -6.5436      1.178     -5.557      0.000      -8.852      -4.236
Precinct_13                                          -12.3331      1.901     -6.489      0.000     -16.058      -8.608
Precinct_17                                          -38.5260      6.153     -6.261      0.000     -50.587     -26.465
Precinct_19                                          -34.2709      6.396     -5.358      0.000     -46.807     -21.735
Precinct_20                                          -38.6715      7.005     -5.520      0.000     -52.402     -24.941
Precinct_23                                            4.2238      6.715      0.629      0.529      -8.937      17.384
Precinct_24                                           -4.8185      5.152     -0.935      0.350     -14.915       5.278
Precinct_25                                           16.6034      9.233      1.798      0.072      -1.492      34.699
Precinct_26                                            5.6535      7.080      0.799      0.425      -8.223      19.530
Precinct_28                                            7.7601      7.529      1.031      0.303      -6.996      22.516
Precinct_30                                            3.8444      7.388      0.520      0.603     -10.637      18.325
Precinct_32                                           14.9690      8.211      1.823      0.068      -1.123      31.061
Precinct_33                                           -7.6294      7.230     -1.055      0.291     -21.801       6.542
Precinct_34                                          -18.0937      6.190     -2.923      0.003     -30.226      -5.962
Precinct_40                                           -5.6187      9.330     -0.602      0.547     -23.905      12.668
Precinct_41                                          -10.3178      9.173     -1.125      0.261     -28.296       7.660
Precinct_42                                          -12.6022      8.886     -1.418      0.156     -30.018       4.814
Precinct_43                                          -14.1842      8.089     -1.754      0.080     -30.038       1.670
Precinct_44                                          -12.8118      9.001     -1.423      0.155     -30.454       4.830
Precinct_45                                          -39.6296      7.081     -5.596      0.000     -53.509     -25.750
Precinct_46                                          -18.3885      8.519     -2.159      0.031     -35.085      -1.692
Precinct_47                                          -32.3397      7.188     -4.499      0.000     -46.427     -18.252
Precinct_48                                          -22.8659      8.057     -2.838      0.005     -38.656      -7.075
Precinct_49                                          -28.1031      7.825     -3.592      0.000     -43.439     -12.767
Precinct_50                                          -33.7397      7.515     -4.489      0.000     -48.470     -19.010
Precinct_52                                          -25.6515      7.369     -3.481      0.000     -40.094     -11.209
Precinct_60                                          -41.4072      7.578     -5.464      0.000     -56.260     -26.554
Precinct_61                                          -56.1246      9.305     -6.032      0.000     -74.362     -37.887
Precinct_62                                          -46.3255      8.124     -5.702      0.000     -62.248     -30.403
Precinct_63                                          -30.6272      6.583     -4.653      0.000     -43.529     -17.725
Precinct_66                                          -46.4833      8.180     -5.682      0.000     -62.516     -30.450
Precinct_67                                          -18.7590      6.507     -2.883      0.004     -31.513      -6.005
Precinct_68                                          -50.0107      8.658     -5.776      0.000     -66.980     -33.042
Precinct_69                                          -16.3450      6.562     -2.491      0.013     -29.205      -3.485
Precinct_70                                          -30.6646      6.356     -4.825      0.000     -43.122     -18.207
Precinct_71                                          -16.0472      5.529     -2.902      0.004     -26.884      -5.210
Precinct_72                                          -27.0321      5.754     -4.698      0.000     -38.309     -15.755
Precinct_73                                          -10.5037      7.290     -1.441      0.150     -24.792       3.785
Precinct_75                                          -27.3118      7.125     -3.833      0.000     -41.277     -13.347
Precinct_76                                            5.7548      3.079      1.869      0.062      -0.280      11.790
Precinct_77                                           -2.1303      6.291     -0.339      0.735     -14.460      10.199
Precinct_78                                           -2.4617      4.073     -0.604      0.546     -10.445       5.521
Precinct_79                                           -5.4473      6.105     -0.892      0.372     -17.414       6.519
Precinct_81                                           -4.9697      7.148     -0.695      0.487     -18.980       9.040
Precinct_83                                          -14.7637      7.107     -2.077      0.038     -28.692      -0.835
Precinct_84                                           18.2222      3.561      5.117      0.000      11.242      25.202
Precinct_88                                            3.3375      4.286      0.779      0.436      -5.062      11.737
Precinct_90                                          -12.5008      5.318     -2.351      0.019     -22.924      -2.078
Precinct_94                                          -18.3125      4.245     -4.314      0.000     -26.632      -9.993
Precinct_100                                          -6.5666      5.820     -1.128      0.259     -17.974       4.840
Precinct_101                                           3.0145      6.012      0.501      0.616      -8.769      14.798
Precinct_102                                         -37.4717      7.504     -4.994      0.000     -52.179     -22.764
Precinct_103                                         -36.6319      7.404     -4.948      0.000     -51.143     -22.121
Precinct_104                                         -39.0392      7.420     -5.261      0.000     -53.582     -24.496
Precinct_105                                         -35.8739      7.114     -5.043      0.000     -49.817     -21.930
Precinct_106                                         -30.8753      7.512     -4.110      0.000     -45.598     -16.153
Precinct_107                                         -42.1361      7.758     -5.431      0.000     -57.341     -26.931
Precinct_108                                         -50.9043      8.667     -5.873      0.000     -67.892     -33.917
Precinct_109                                         -48.5232      8.332     -5.824      0.000     -64.854     -32.192
Precinct_110                                         -49.3330      8.512     -5.796      0.000     -66.016     -32.650
Precinct_111                                         -44.4136      7.791     -5.700      0.000     -59.684     -29.143
Precinct_112                                         -46.8409      8.319     -5.631      0.000     -63.146     -30.536
Precinct_114                                         -45.5712      7.521     -6.059      0.000     -60.312     -30.830
Precinct_115                                         -51.2635      8.783     -5.837      0.000     -68.478     -34.049
Precinct_120                                         -18.1270      5.313     -3.412      0.001     -28.540      -7.714
Precinct_122                                         -25.1293      5.844     -4.300      0.000     -36.584     -13.675
Precinct_123                                         -38.2166      7.216     -5.296      0.000     -52.359     -24.074
==============================================================================
Omnibus:                      294.760   Durbin-Watson:                   2.180
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14411.945
Skew:                           0.105   Prob(JB):                         0.00
Kurtosis:                      19.809   Cond. No.                     4.34e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 4.34e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Standardized coefficients (continuous vars only), sorted by |beta|:

                                                    beta_std  se_cluster  \
lag_Budget_per_capita                               -39.1760      4.9484
lag_Budget_per_capita_lag1                           18.1645      3.7191
lag_FELONY_ASSAULT_per_capita_lag1                    4.6569      1.7375
lag_ROBBERY_per_capita_lag1                          -2.0880      2.3652
lag_total_pop_lag1                                   -1.5168      0.8746
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1     -1.1302      0.5634
lag_RAPE_per_capita_lag1                              1.1116      1.0234
lag_GRAND_LARCENY_per_capita_lag1                     1.0698      1.4088
lag_minority_pct_lag1                                -1.0456      0.7390
lag_per_capita_income_lag1                           -0.7311      0.8908
lag_BURGLARY_per_capita_lag1                         -0.5269      0.5813
Budget_per_capita_lag1                                0.4833      0.0481
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1   -0.4315      0.3240
FELONY_ASSAULT_per_capita_lag1                        0.0940      0.0346
GRAND_LARCENY_per_capita_lag1                         0.0505      0.0268
ROBBERY_per_capita_lag1                              -0.0466      0.0457
minority_pct_lag1                                    -0.0394      0.0186
per_capita_income_lag1                               -0.0330      0.0228
RAPE_per_capita_lag1                                  0.0317      0.0229
total_pop_lag1                                       -0.0279      0.0152
BURGLARY_per_capita_lag1                             -0.0205      0.0158
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1         -0.0191      0.0136
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1       -0.0133      0.0107

                                                          z    pval
lag_Budget_per_capita                               -7.9169  0.0000
lag_Budget_per_capita_lag1                           4.8842  0.0000
lag_FELONY_ASSAULT_per_capita_lag1                   2.6802  0.0074
lag_ROBBERY_per_capita_lag1                         -0.8828  0.3773
lag_total_pop_lag1                                  -1.7342  0.0829
lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1    -2.0061  0.0448
lag_RAPE_per_capita_lag1                             1.0861  0.2774
lag_GRAND_LARCENY_per_capita_lag1                    0.7594  0.4476
lag_minority_pct_lag1                               -1.4149  0.1571
lag_per_capita_income_lag1                          -0.8207  0.4118
lag_BURGLARY_per_capita_lag1                        -0.9064  0.3647
Budget_per_capita_lag1                              10.0535  0.0000
lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1  -1.3319  0.1829
FELONY_ASSAULT_per_capita_lag1                       2.7178  0.0066
GRAND_LARCENY_per_capita_lag1                        1.8830  0.0597
ROBBERY_per_capita_lag1                             -1.0180  0.3087
minority_pct_lag1                                   -2.1180  0.0342
per_capita_income_lag1                              -1.4478  0.1477
RAPE_per_capita_lag1                                 1.3832  0.1666
total_pop_lag1                                      -1.8387  0.0660
BURGLARY_per_capita_lag1                            -1.2940  0.1957
MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1        -1.4078  0.1592
GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1      -1.2461  0.2127

C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 5 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

In [56]:
def clean_name(s: str) -> str:
    """Clean column names for formula safety"""
    return re.sub(r'[^0-9A-Za-z_]+', '_', s)

def clean_cols(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [clean_name(c) for c in df.columns]
    return df

precincts_gdf_s = gpd.read_file("Geo/NYPD_Precincts.geojson").to_crs(epsg=4326)
precincts_gdf_s = precincts_gdf_s.rename(columns={"precinct": "Precinct"})

merged_sp = precincts_gdf_s.merge(pre_ts_analysis, on="Precinct")
merged_sp = clean_cols(merged_sp)

merged_sp = merged_sp[merged_sp["Year"] > 2006].copy()

X_vars_raw = [
    "Violent Crime_per_capita_lag1",
    "Property Crime_per_capita_lag1",
    "Budget_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1"
]
y_var_raw = "Budget_per_capita"

X_vars = [clean_name(v) for v in X_vars_raw]
y_var  = clean_name(y_var_raw)

# Ensure required cols present
keep_cols = ["Precinct", "Year", "geometry", y_var] + X_vars
df = merged_sp[keep_cols].copy()

w = Queen.from_dataframe(df)
w.transform = 'r'

lag_y = f"lag_{y_var}"
df[lag_y] = lag_spatial(w, df[y_var])

for var in X_vars:
    if df[var].isna().any():
        df[var] = df[var].fillna(df[var].mean())
    df[f"lag_{var}"] = lag_spatial(w, df[var])

lag_vars = [f"lag_{v}" for v in X_vars] + [lag_y]
df_clean = df.dropna(subset=[y_var] + lag_vars + ['Year','Precinct']).copy()

cont_cols = [y_var] + X_vars + lag_vars
scaler = StandardScaler()
df_clean[cont_cols] = scaler.fit_transform(df_clean[cont_cols])

rhs_terms = [lag_y] + X_vars + lag_vars + ["C(Year)", "C(Precinct)"]
formula = f"{y_var} ~ " + " + ".join(rhs_terms)
print("Two-way FE + spillovers formula:\n", formula)

model_twfe_cluster = smf.ols(formula=formula, data=df_clean).fit(
    cov_type="cluster",
    cov_kwds={"groups": df_clean["Precinct"]}
)
print(model_twfe_cluster.summary())

coef_table = (
    pd.DataFrame({
        "beta_std": model_twfe_cluster.params,
        "se_cluster": model_twfe_cluster.bse,
        "z": model_twfe_cluster.tvalues,
        "pval": model_twfe_cluster.pvalues
    })
    .assign(is_fe_or_const=lambda s:
            s.index.str.startswith(("C(Year)[T.", "C(Precinct)[T.")) |
            (s.index == "Intercept"))
)

print("\nStandardized coefficients (continuous vars only), sorted by |beta|:\n")
print(
    coef_table.loc[~coef_table["is_fe_or_const"]]
              .drop(columns="is_fe_or_const")
              .sort_values("beta_std", key=lambda s: s.abs(), ascending=False)
              .round(4)
)

C:\Users\yinwe\AppData\Local\Temp\ipykernel_22260\3129583446.py:35: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(df)
C:\Users\yinwe\Work_software\Lib\site-packages\libpysal\weights\contiguity.py:347: UserWarning: The weights matrix is not fully connected:
 There are 6 disconnected components.
  W.__init__(self, neighbors, ids=ids, **kw)

Two-way FE + spillovers formula:
 Budget_per_capita ~ lag_Budget_per_capita + Violent_Crime_per_capita_lag1 + Property_Crime_per_capita_lag1 + Budget_per_capita_lag1 + minority_pct_lag1 + per_capita_income_lag1 + total_pop_lag1 + lag_Violent_Crime_per_capita_lag1 + lag_Property_Crime_per_capita_lag1 + lag_Budget_per_capita_lag1 + lag_minority_pct_lag1 + lag_per_capita_income_lag1 + lag_total_pop_lag1 + lag_Budget_per_capita + C(Year) + C(Precinct)
                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     126.8
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           6.13e-51
Time:                        01:25:23   Log-Likelihood:                 1191.5
No. Observations:                1241   AIC:                            -2179.
Df Residuals:                    1139   BIC:                            -1656.
Df Model:                         101
Covariance Type:              cluster
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                             29.3907      8.641      3.401      0.001      12.455      46.327
C(Year)[T.2008]                       -0.0225      0.020     -1.133      0.257      -0.061       0.016
C(Year)[T.2009]                       -0.0305      0.023     -1.331      0.183      -0.075       0.014
C(Year)[T.2010]                       -0.0120      0.032     -0.375      0.708      -0.075       0.051
C(Year)[T.2011]                        0.0843      0.036      2.345      0.019       0.014       0.155
C(Year)[T.2012]                       -0.0090      0.035     -0.260      0.795      -0.077       0.059
C(Year)[T.2013]                        0.0081      0.024      0.337      0.736      -0.039       0.055
C(Year)[T.2014]                        0.0039      0.027      0.145      0.885      -0.049       0.057
C(Year)[T.2015]                        0.0074      0.026      0.287      0.774      -0.043       0.058
C(Year)[T.2016]                        0.0146      0.026      0.551      0.581      -0.037       0.067
C(Year)[T.2017]                        0.0226      0.025      0.906      0.365      -0.026       0.071
C(Year)[T.2018]                        0.0626      0.027      2.305      0.021       0.009       0.116
C(Year)[T.2019]                        0.0460      0.030      1.559      0.119      -0.012       0.104
C(Year)[T.2020]                        0.0388      0.029      1.343      0.179      -0.018       0.095
C(Year)[T.2021]                        0.0190      0.030      0.633      0.526      -0.040       0.078
C(Year)[T.2022]                        0.0261      0.026      0.991      0.322      -0.025       0.078
C(Year)[T.2023]                        0.0253      0.025      1.027      0.304      -0.023       0.074
C(Precinct)[T.5]                      -1.6435      1.027     -1.600      0.110      -3.657       0.370
C(Precinct)[T.6]                      -2.8129      0.528     -5.331      0.000      -3.847      -1.779
C(Precinct)[T.7]                      -7.9268      3.505     -2.262      0.024     -14.796      -1.058
C(Precinct)[T.9]                      -4.6000      1.120     -4.109      0.000      -6.794      -2.406
C(Precinct)[T.10]                     -2.8348      0.999     -2.837      0.005      -4.793      -0.876
C(Precinct)[T.13]                    -10.7720      2.093     -5.146      0.000     -14.875      -6.669
C(Precinct)[T.17]                    -40.3227      7.721     -5.223      0.000     -55.455     -25.190
C(Precinct)[T.19]                    -40.3942      9.155     -4.412      0.000     -58.339     -22.450
C(Precinct)[T.20]                    -45.3612      9.696     -4.678      0.000     -64.365     -26.357
C(Precinct)[T.23]                     -6.2481      8.035     -0.778      0.437     -21.997       9.501
C(Precinct)[T.24]                    -16.2291      6.854     -2.368      0.018     -29.663      -2.795
C(Precinct)[T.25]                      5.1815      9.444      0.549      0.583     -13.328      23.691
C(Precinct)[T.26]                     -7.2777      7.944     -0.916      0.360     -22.848       8.292
C(Precinct)[T.28]                     -3.8767      8.383     -0.462      0.644     -20.307      12.553
C(Precinct)[T.30]                     -9.3241      8.275     -1.127      0.260     -25.542       6.894
C(Precinct)[T.32]                      1.9242      8.281      0.232      0.816     -14.306      18.155
C(Precinct)[T.33]                    -19.0537      8.997     -2.118      0.034     -36.687      -1.421
C(Precinct)[T.34]                    -29.0227      8.807     -3.295      0.001     -46.284     -11.762
C(Precinct)[T.40]                    -11.9663     11.556     -1.036      0.300     -34.615      10.683
C(Precinct)[T.41]                    -16.2871     11.472     -1.420      0.156     -38.772       6.198
C(Precinct)[T.42]                    -19.6836     11.398     -1.727      0.084     -42.023       2.655
C(Precinct)[T.43]                    -21.8289     10.699     -2.040      0.041     -42.798      -0.860
C(Precinct)[T.44]                    -20.8659     11.635     -1.793      0.073     -43.669       1.937
C(Precinct)[T.45]                    -46.9948     10.139     -4.635      0.000     -66.868     -27.122
C(Precinct)[T.46]                    -26.5302     11.450     -2.317      0.020     -48.972      -4.089
C(Precinct)[T.47]                    -41.0070     10.708     -3.829      0.000     -61.995     -20.019
C(Precinct)[T.48]                    -30.9276     11.219     -2.757      0.006     -52.917      -8.938
C(Precinct)[T.49]                    -36.2875     11.210     -3.237      0.001     -58.259     -14.316
C(Precinct)[T.50]                    -41.7285     11.055     -3.775      0.000     -63.396     -20.061
C(Precinct)[T.52]                    -34.5781     10.703     -3.231      0.001     -55.556     -13.600
C(Precinct)[T.60]                    -51.9988     11.765     -4.420      0.000     -75.057     -28.940
C(Precinct)[T.61]                    -58.7228     11.922     -4.926      0.000     -82.089     -35.357
C(Precinct)[T.62]                    -57.8472     12.347     -4.685      0.000     -82.047     -33.647
C(Precinct)[T.63]                    -41.5021     10.633     -3.903      0.000     -62.343     -20.661
C(Precinct)[T.66]                    -58.3196     12.457     -4.682      0.000     -82.736     -33.903
C(Precinct)[T.67]                    -30.4003     10.354     -2.936      0.003     -50.695     -10.106
C(Precinct)[T.68]                    -61.8025     12.906     -4.789      0.000     -87.098     -36.507
C(Precinct)[T.69]                    -27.3258     10.228     -2.672      0.008     -47.373      -7.279
C(Precinct)[T.70]                    -41.9228     10.361     -4.046      0.000     -62.229     -21.616
C(Precinct)[T.71]                    -28.6075      9.311     -3.073      0.002     -46.856     -10.359
C(Precinct)[T.72]                    -40.1332      9.577     -4.191      0.000     -58.904     -21.363
C(Precinct)[T.73]                    -22.4934     10.595     -2.123      0.034     -43.259      -1.728
C(Precinct)[T.75]                    -37.1834     10.888     -3.415      0.001     -58.523     -15.844
C(Precinct)[T.76]                     -9.0865      5.117     -1.776      0.076     -19.116       0.944
C(Precinct)[T.77]                    -15.1279      9.181     -1.648      0.099     -33.121       2.866
C(Precinct)[T.78]                    -16.3288      6.905     -2.365      0.018     -29.862      -2.796
C(Precinct)[T.79]                    -18.6657      8.901     -2.097      0.036     -36.112      -1.219
C(Precinct)[T.81]                    -17.9211     10.029     -1.787      0.074     -37.578       1.736
C(Precinct)[T.83]                    -25.9815     10.424     -2.492      0.013     -46.412      -5.551
C(Precinct)[T.84]                      2.3328      4.299      0.543      0.587      -6.093      10.759
C(Precinct)[T.88]                    -10.9385      6.565     -1.666      0.096     -23.805       1.928
C(Precinct)[T.90]                    -24.1437      8.261     -2.923      0.003     -40.335      -7.953
C(Precinct)[T.94]                    -28.7171      6.618     -4.339      0.000     -41.689     -15.745
C(Precinct)[T.100]                   -18.3340      8.457     -2.168      0.030     -34.909      -1.759
C(Precinct)[T.101]                    -9.2447      7.925     -1.166      0.243     -24.778       6.288
C(Precinct)[T.102]                   -45.6553     11.147     -4.096      0.000     -67.503     -23.807
C(Precinct)[T.103]                   -45.7784     11.134     -4.112      0.000     -67.600     -23.957
C(Precinct)[T.104]                   -46.9957     11.043     -4.256      0.000     -68.639     -25.352
C(Precinct)[T.105]                   -45.2387     10.799     -4.189      0.000     -66.404     -24.073
C(Precinct)[T.106]                   -39.4290     11.044     -3.570      0.000     -61.075     -17.783
C(Precinct)[T.107]                   -50.0375     11.430     -4.378      0.000     -72.439     -27.636
C(Precinct)[T.108]                   -55.4642     12.065     -4.597      0.000     -79.111     -31.818
C(Precinct)[T.109]                   -55.0107     11.848     -4.643      0.000     -78.232     -31.789
C(Precinct)[T.110]                   -54.7623     11.973     -4.574      0.000     -78.229     -31.296
C(Precinct)[T.111]                   -53.4165     11.407     -4.683      0.000     -75.773     -31.060
C(Precinct)[T.112]                   -54.0241     11.968     -4.514      0.000     -77.480     -30.568
C(Precinct)[T.113]                   -37.7885     10.126     -3.732      0.000     -57.635     -17.942
C(Precinct)[T.114]                   -49.6901     10.183     -4.880      0.000     -69.649     -29.731
C(Precinct)[T.115]                   -54.9332     12.049     -4.559      0.000     -78.549     -31.317
C(Precinct)[T.120]                   -31.0793      8.214     -3.784      0.000     -47.179     -14.980
C(Precinct)[T.122]                   -37.7549      8.892     -4.246      0.000     -55.183     -20.327
C(Precinct)[T.123]                   -49.9901     10.280     -4.863      0.000     -70.138     -29.842
lag_Budget_per_capita                -35.8373      5.324     -6.731      0.000     -46.273     -25.402
Violent_Crime_per_capita_lag1          0.0046      0.044      0.106      0.915      -0.081       0.090
Property_Crime_per_capita_lag1        -0.0500      0.036     -1.371      0.170      -0.121       0.021
Budget_per_capita_lag1                 0.5428      0.050     10.924      0.000       0.445       0.640
minority_pct_lag1                     -0.0388      0.021     -1.867      0.062      -0.079       0.002
per_capita_income_lag1                -0.0190      0.024     -0.796      0.426      -0.066       0.028
total_pop_lag1                        -0.0010      0.017     -0.060      0.952      -0.034       0.032
lag_Violent_Crime_per_capita_lag1      0.1644      2.432      0.068      0.946      -4.603       4.932
lag_Property_Crime_per_capita_lag1    -3.7823      1.831     -2.066      0.039      -7.371      -0.193
lag_Budget_per_capita_lag1            19.7627      4.030      4.904      0.000      11.865      27.661
lag_minority_pct_lag1                 -1.0830      0.774     -1.399      0.162      -2.600       0.435
lag_per_capita_income_lag1            -0.5072      0.883     -0.574      0.566      -2.238       1.224
lag_total_pop_lag1                     0.1674      0.847      0.198      0.843      -1.493       1.828
==============================================================================
Omnibus:                      335.725   Durbin-Watson:                   2.237
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14351.970
Skew:                           0.463   Prob(JB):                         0.00
Kurtosis:                      19.634   Cond. No.                     2.72e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 2.72e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Standardized coefficients (continuous vars only), sorted by |beta|:

                                    beta_std  se_cluster        z    pval
lag_Budget_per_capita               -35.8373      5.3245  -6.7307  0.0000
lag_Budget_per_capita_lag1           19.7627      4.0296   4.9044  0.0000
lag_Property_Crime_per_capita_lag1   -3.7823      1.8311  -2.0656  0.0389
lag_minority_pct_lag1                -1.0830      0.7743  -1.3987  0.1619
Budget_per_capita_lag1                0.5428      0.0497  10.9237  0.0000
lag_per_capita_income_lag1           -0.5072      0.8833  -0.5742  0.5658
lag_total_pop_lag1                    0.1674      0.8472   0.1976  0.8433
lag_Violent_Crime_per_capita_lag1     0.1644      2.4323   0.0676  0.9461
Property_Crime_per_capita_lag1       -0.0500      0.0364  -1.3711  0.1703
minority_pct_lag1                    -0.0388      0.0208  -1.8675  0.0618
per_capita_income_lag1               -0.0190      0.0239  -0.7965  0.4258
Violent_Crime_per_capita_lag1         0.0046      0.0436   0.1062  0.9155
total_pop_lag1                       -0.0010      0.0170  -0.0602  0.9520

C:\Users\yinwe\Work_software\Lib\site-packages\statsmodels\base\model.py:1896: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 101, but rank is 29
  warnings.warn('covariance of constraints does not have full '

In [57]:
res = model_twfe_cluster

def _rename_term(name: str) -> str:
    name = re.sub(r'^C\(Year\)\[T\.(\d+)\]$', r'Year_\1', name)
    name = re.sub(r'^C\(Precinct\)\[T\.(.+)\]$', r'Precinct_\1', name)
    if name == "Intercept":
        name = "const"
    return name

renamed_idx = [ _rename_term(s) for s in res.params.index ]
params_ren = pd.Series(res.params.values, index=renamed_idx, name="coef")
se_ren     = pd.Series(res.bse.values,     index=renamed_idx, name="se")
t_ren      = pd.Series(res.tvalues.values, index=renamed_idx, name="z")
p_ren      = pd.Series(res.pvalues.values, index=renamed_idx, name="pval")

table = pd.concat([params_ren, se_ren, t_ren, p_ren], axis=1)
table["is_FE"] = table.index.str.startswith(("Year_", "Precinct_"))

preferred_order = [
    "const",
    # Core outcome spillover + own lag(s)
    "lag_Budget_per_capita",
    "Budget_per_capita_lag1",
    "lag_Budget_per_capita_lag1",
    # Disaggregated index crimes 
    "MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY_ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND_LARCENY_per_capita_lag1",
    "GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    # Aggregated crimes 
    "Violent_Crime_per_capita_lag1",
    "Property_Crime_per_capita_lag1",
    # Socioeconomics
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1",
    # Spatial lags of X
    "lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "lag_RAPE_per_capita_lag1",
    "lag_FELONY_ASSAULT_per_capita_lag1",
    "lag_BURGLARY_per_capita_lag1",
    "lag_GRAND_LARCENY_per_capita_lag1",
    "lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "lag_ROBBERY_per_capita_lag1",
    "lag_Violent_Crime_per_capita_lag1",
    "lag_Property_Crime_per_capita_lag1",
    "lag_minority_pct_lag1",
    "lag_per_capita_income_lag1",
    "lag_total_pop_lag1",
]

substantive = table.loc[~table["is_FE"]].drop(columns="is_FE")

present_pref = [v for v in preferred_order if v in substantive.index]
remaining    = [v for v in substantive.index if v not in present_pref]
if remaining:
    remaining_sorted = substantive.loc[remaining].assign(_abs=lambda s: s["coef"].abs()) \
                                             .sort_values("_abs", ascending=False) \
                                             .drop(columns="_abs").index.tolist()
else:
    remaining_sorted = []

ordered_index = present_pref + remaining_sorted
clean_table = substantive.loc[ordered_index].round(4)

print("\n=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===")
print(clean_table.to_string())

n_year_fe = (table.index.str.startswith("Year_")).sum()
n_prec_fe = (table.index.str.startswith("Precinct_")).sum()
print(f"\n[Note] Hidden fixed effects: {n_year_fe} Year FEs, {n_prec_fe} Precinct FEs.")

=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===
                                       coef      se        z    pval
const                               29.3907  8.6410   3.4013  0.0007
lag_Budget_per_capita              -35.8373  5.3245  -6.7307  0.0000
Budget_per_capita_lag1               0.5428  0.0497  10.9237  0.0000
lag_Budget_per_capita_lag1          19.7627  4.0296   4.9044  0.0000
Violent_Crime_per_capita_lag1        0.0046  0.0436   0.1062  0.9155
Property_Crime_per_capita_lag1      -0.0500  0.0364  -1.3711  0.1703
minority_pct_lag1                   -0.0388  0.0208  -1.8675  0.0618
per_capita_income_lag1              -0.0190  0.0239  -0.7965  0.4258
total_pop_lag1                      -0.0010  0.0170  -0.0602  0.9520
lag_Violent_Crime_per_capita_lag1    0.1644  2.4323   0.0676  0.9461
lag_Property_Crime_per_capita_lag1  -3.7823  1.8311  -2.0656  0.0389
lag_minority_pct_lag1               -1.0830  0.7743  -1.3987  0.1619
lag_per_capita_income_lag1          -0.5072  0.8833  -0.5742  0.5658
lag_total_pop_lag1                   0.1674  0.8472   0.1976  0.8433

[Note] Hidden fixed effects: 16 Year FEs, 72 Precinct FEs.

In [58]:
res = model_twfe_cluster 

def _rename_term(name: str) -> str:
    name = re.sub(r'^C\(Year\)\[T\.(\d+)\]$', r'Year_\1', name)
    name = re.sub(r'^C\(Precinct\)\[T\.(.+)\]$', r'Precinct_\1', name)
    if name == "Intercept":
        name = "const"
    return name

renamed_idx = [_rename_term(s) for s in res.params.index]
params_ren = pd.Series(res.params.values, index=renamed_idx, name="coef")
se_ren     = pd.Series(res.bse.values,     index=renamed_idx, name="se")
t_ren      = pd.Series(res.tvalues.values, index=renamed_idx, name="z")
p_ren      = pd.Series(res.pvalues.values, index=renamed_idx, name="pval")

table = pd.concat([params_ren, se_ren, t_ren, p_ren], axis=1)
table["is_FE"] = table.index.str.startswith(("Year_", "Precinct_"))

preferred_order = [
    "const",
    # Core outcome spillover + own lag(s)
    "lag_Budget_per_capita",
    "Budget_per_capita_lag1",
    "lag_Budget_per_capita_lag1",
    # Disaggregated index crimes 
    "MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY_ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND_LARCENY_per_capita_lag1",
    "GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    # Aggregated crimes 
    "Violent_Crime_per_capita_lag1",
    "Property_Crime_per_capita_lag1",
    # Socioeconomics
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1",
    # Spatial lags of X
    "lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "lag_RAPE_per_capita_lag1",
    "lag_FELONY_ASSAULT_per_capita_lag1",
    "lag_BURGLARY_per_capita_lag1",
    "lag_GRAND_LARCENY_per_capita_lag1",
    "lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "lag_ROBBERY_per_capita_lag1",
    "lag_Violent_Crime_per_capita_lag1",
    "lag_Property_Crime_per_capita_lag1",
    "lag_minority_pct_lag1",
    "lag_per_capita_income_lag1",
    "lag_total_pop_lag1",
]

substantive = table.loc[~table["is_FE"]].drop(columns="is_FE")

present_pref = [v for v in preferred_order if v in substantive.index]
remaining    = [v for v in substantive.index if v not in present_pref]
if remaining:
    remaining_sorted = (
        substantive.loc[remaining]
                  .assign(_abs=lambda s: s["coef"].abs())
                  .sort_values("_abs", ascending=False)
                  .drop(columns="_abs")
                  .index.tolist()
    )
else:
    remaining_sorted = []

ordered_index = present_pref + remaining_sorted
clean_table = substantive.loc[ordered_index].round(4)

print("\n=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===")
print(clean_table.to_string())

dw = durbin_watson(res.resid)
print("\n=== Model Fit (robust/clustered) ===")
print(f"Observations: {int(res.nobs)}")
print(f"R-squared / Adj.: {res.rsquared:.3f} / {res.rsquared_adj:.3f}")
if res.fvalue is not None:
    print(f"F-statistic (model): {res.fvalue:.2f}, p-value: {res.f_pvalue:.2g}")
print(f"Log-Likelihood: {res.llf:.1f} | AIC: {res.aic:.1f} | BIC: {res.bic:.1f}")
print(f"Durbin-Watson: {dw:.3f}")
print(f"Covariance Type: {res.cov_type} (groups=Precinct)")

n_year_fe = (table.index.str.startswith("Year_")).sum()
n_prec_fe = (table.index.str.startswith("Precinct_")).sum()
print(f"\n[Note] Hidden fixed effects: {n_year_fe} Year FEs, {n_prec_fe} Precinct FEs.")

def cleaned_summary_no_fe(res_):
    txt = res_.summary().as_text()
    # rename in the text first
    txt = re.sub(r'C\(Year\)\[T\.(\d+)\]', r'Year_\1', txt)
    txt = re.sub(r'C\(Precinct\)\[T\.([^\]]+)\]', r'Precinct_\1', txt)
    # drop any lines that start with Year_ or Precinct_
    cleaned_lines = []
    for line in txt.splitlines():
        if re.match(r'^\s*(Year_|Precinct_)', line):
            continue
        cleaned_lines.append(line)
    return "\n".join(cleaned_lines)

=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===
                                       coef      se        z    pval
const                               29.3907  8.6410   3.4013  0.0007
lag_Budget_per_capita              -35.8373  5.3245  -6.7307  0.0000
Budget_per_capita_lag1               0.5428  0.0497  10.9237  0.0000
lag_Budget_per_capita_lag1          19.7627  4.0296   4.9044  0.0000
Violent_Crime_per_capita_lag1        0.0046  0.0436   0.1062  0.9155
Property_Crime_per_capita_lag1      -0.0500  0.0364  -1.3711  0.1703
minority_pct_lag1                   -0.0388  0.0208  -1.8675  0.0618
per_capita_income_lag1              -0.0190  0.0239  -0.7965  0.4258
total_pop_lag1                      -0.0010  0.0170  -0.0602  0.9520
lag_Violent_Crime_per_capita_lag1    0.1644  2.4323   0.0676  0.9461
lag_Property_Crime_per_capita_lag1  -3.7823  1.8311  -2.0656  0.0389
lag_minority_pct_lag1               -1.0830  0.7743  -1.3987  0.1619
lag_per_capita_income_lag1          -0.5072  0.8833  -0.5742  0.5658
lag_total_pop_lag1                   0.1674  0.8472   0.1976  0.8433

=== Model Fit (robust/clustered) ===
Observations: 1241
R-squared / Adj.: 0.991 / 0.991
F-statistic (model): 126.82, p-value: 6.1e-51
Log-Likelihood: 1191.5 | AIC: -2179.0 | BIC: -1656.4
Durbin-Watson: 2.237
Covariance Type: cluster (groups=Precinct)

[Note] Hidden fixed effects: 16 Year FEs, 72 Precinct FEs.

In [59]:
def _rename_term(name: str) -> str:
    name = re.sub(r'^C\(Year\)\[T\.(\d+)\]$', r'Year_\1', name)          
    name = re.sub(r'^C\(Precinct\)\[T\.(.+)\]$', r'Precinct_\1', name)   
    if name == "Intercept":
        name = "const"
    return name

def print_classic_summary_renamed(res):
    """
    Prints statsmodels' classic summary, but with FE names cleaned:
    - C(Year)[T.x]     -> Year_x
    - C(Precinct)[T.y] -> Precinct_y
    - Intercept        -> const
    Keeps *all* FE rows (nothing hidden).
    """
    summ = res.summary()           
    coef_tbl = summ.tables[1]     

    for i in range(1, len(coef_tbl.data)):  
        coef_tbl.data[i][0] = _rename_term(coef_tbl.data[i][0])

    print(summ)

res = model_twfe_cluster
print_classic_summary_renamed(res)

                            OLS Regression Results
==============================================================================
Dep. Variable:      Budget_per_capita   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     126.8
Date:                Mon, 13 Oct 2025   Prob (F-statistic):           6.13e-51
Time:                        01:25:24   Log-Likelihood:                 1191.5
No. Observations:                1241   AIC:                            -2179.
Df Residuals:                    1139   BIC:                            -1656.
Df Model:                         101
Covariance Type:              cluster
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                             29.3907      8.641      3.401      0.001      12.455      46.327
C(Year)[T.2008]                       -0.0225      0.020     -1.133      0.257      -0.061       0.016
C(Year)[T.2009]                       -0.0305      0.023     -1.331      0.183      -0.075       0.014
C(Year)[T.2010]                       -0.0120      0.032     -0.375      0.708      -0.075       0.051
C(Year)[T.2011]                        0.0843      0.036      2.345      0.019       0.014       0.155
C(Year)[T.2012]                       -0.0090      0.035     -0.260      0.795      -0.077       0.059
C(Year)[T.2013]                        0.0081      0.024      0.337      0.736      -0.039       0.055
C(Year)[T.2014]                        0.0039      0.027      0.145      0.885      -0.049       0.057
C(Year)[T.2015]                        0.0074      0.026      0.287      0.774      -0.043       0.058
C(Year)[T.2016]                        0.0146      0.026      0.551      0.581      -0.037       0.067
C(Year)[T.2017]                        0.0226      0.025      0.906      0.365      -0.026       0.071
C(Year)[T.2018]                        0.0626      0.027      2.305      0.021       0.009       0.116
C(Year)[T.2019]                        0.0460      0.030      1.559      0.119      -0.012       0.104
C(Year)[T.2020]                        0.0388      0.029      1.343      0.179      -0.018       0.095
C(Year)[T.2021]                        0.0190      0.030      0.633      0.526      -0.040       0.078
C(Year)[T.2022]                        0.0261      0.026      0.991      0.322      -0.025       0.078
C(Year)[T.2023]                        0.0253      0.025      1.027      0.304      -0.023       0.074
C(Precinct)[T.5]                      -1.6435      1.027     -1.600      0.110      -3.657       0.370
C(Precinct)[T.6]                      -2.8129      0.528     -5.331      0.000      -3.847      -1.779
C(Precinct)[T.7]                      -7.9268      3.505     -2.262      0.024     -14.796      -1.058
C(Precinct)[T.9]                      -4.6000      1.120     -4.109      0.000      -6.794      -2.406
C(Precinct)[T.10]                     -2.8348      0.999     -2.837      0.005      -4.793      -0.876
C(Precinct)[T.13]                    -10.7720      2.093     -5.146      0.000     -14.875      -6.669
C(Precinct)[T.17]                    -40.3227      7.721     -5.223      0.000     -55.455     -25.190
C(Precinct)[T.19]                    -40.3942      9.155     -4.412      0.000     -58.339     -22.450
C(Precinct)[T.20]                    -45.3612      9.696     -4.678      0.000     -64.365     -26.357
C(Precinct)[T.23]                     -6.2481      8.035     -0.778      0.437     -21.997       9.501
C(Precinct)[T.24]                    -16.2291      6.854     -2.368      0.018     -29.663      -2.795
C(Precinct)[T.25]                      5.1815      9.444      0.549      0.583     -13.328      23.691
C(Precinct)[T.26]                     -7.2777      7.944     -0.916      0.360     -22.848       8.292
C(Precinct)[T.28]                     -3.8767      8.383     -0.462      0.644     -20.307      12.553
C(Precinct)[T.30]                     -9.3241      8.275     -1.127      0.260     -25.542       6.894
C(Precinct)[T.32]                      1.9242      8.281      0.232      0.816     -14.306      18.155
C(Precinct)[T.33]                    -19.0537      8.997     -2.118      0.034     -36.687      -1.421
C(Precinct)[T.34]                    -29.0227      8.807     -3.295      0.001     -46.284     -11.762
C(Precinct)[T.40]                    -11.9663     11.556     -1.036      0.300     -34.615      10.683
C(Precinct)[T.41]                    -16.2871     11.472     -1.420      0.156     -38.772       6.198
C(Precinct)[T.42]                    -19.6836     11.398     -1.727      0.084     -42.023       2.655
C(Precinct)[T.43]                    -21.8289     10.699     -2.040      0.041     -42.798      -0.860
C(Precinct)[T.44]                    -20.8659     11.635     -1.793      0.073     -43.669       1.937
C(Precinct)[T.45]                    -46.9948     10.139     -4.635      0.000     -66.868     -27.122
C(Precinct)[T.46]                    -26.5302     11.450     -2.317      0.020     -48.972      -4.089
C(Precinct)[T.47]                    -41.0070     10.708     -3.829      0.000     -61.995     -20.019
C(Precinct)[T.48]                    -30.9276     11.219     -2.757      0.006     -52.917      -8.938
C(Precinct)[T.49]                    -36.2875     11.210     -3.237      0.001     -58.259     -14.316
C(Precinct)[T.50]                    -41.7285     11.055     -3.775      0.000     -63.396     -20.061
C(Precinct)[T.52]                    -34.5781     10.703     -3.231      0.001     -55.556     -13.600
C(Precinct)[T.60]                    -51.9988     11.765     -4.420      0.000     -75.057     -28.940
C(Precinct)[T.61]                    -58.7228     11.922     -4.926      0.000     -82.089     -35.357
C(Precinct)[T.62]                    -57.8472     12.347     -4.685      0.000     -82.047     -33.647
C(Precinct)[T.63]                    -41.5021     10.633     -3.903      0.000     -62.343     -20.661
C(Precinct)[T.66]                    -58.3196     12.457     -4.682      0.000     -82.736     -33.903
C(Precinct)[T.67]                    -30.4003     10.354     -2.936      0.003     -50.695     -10.106
C(Precinct)[T.68]                    -61.8025     12.906     -4.789      0.000     -87.098     -36.507
C(Precinct)[T.69]                    -27.3258     10.228     -2.672      0.008     -47.373      -7.279
C(Precinct)[T.70]                    -41.9228     10.361     -4.046      0.000     -62.229     -21.616
C(Precinct)[T.71]                    -28.6075      9.311     -3.073      0.002     -46.856     -10.359
C(Precinct)[T.72]                    -40.1332      9.577     -4.191      0.000     -58.904     -21.363
C(Precinct)[T.73]                    -22.4934     10.595     -2.123      0.034     -43.259      -1.728
C(Precinct)[T.75]                    -37.1834     10.888     -3.415      0.001     -58.523     -15.844
C(Precinct)[T.76]                     -9.0865      5.117     -1.776      0.076     -19.116       0.944
C(Precinct)[T.77]                    -15.1279      9.181     -1.648      0.099     -33.121       2.866
C(Precinct)[T.78]                    -16.3288      6.905     -2.365      0.018     -29.862      -2.796
C(Precinct)[T.79]                    -18.6657      8.901     -2.097      0.036     -36.112      -1.219
C(Precinct)[T.81]                    -17.9211     10.029     -1.787      0.074     -37.578       1.736
C(Precinct)[T.83]                    -25.9815     10.424     -2.492      0.013     -46.412      -5.551
C(Precinct)[T.84]                      2.3328      4.299      0.543      0.587      -6.093      10.759
C(Precinct)[T.88]                    -10.9385      6.565     -1.666      0.096     -23.805       1.928
C(Precinct)[T.90]                    -24.1437      8.261     -2.923      0.003     -40.335      -7.953
C(Precinct)[T.94]                    -28.7171      6.618     -4.339      0.000     -41.689     -15.745
C(Precinct)[T.100]                   -18.3340      8.457     -2.168      0.030     -34.909      -1.759
C(Precinct)[T.101]                    -9.2447      7.925     -1.166      0.243     -24.778       6.288
C(Precinct)[T.102]                   -45.6553     11.147     -4.096      0.000     -67.503     -23.807
C(Precinct)[T.103]                   -45.7784     11.134     -4.112      0.000     -67.600     -23.957
C(Precinct)[T.104]                   -46.9957     11.043     -4.256      0.000     -68.639     -25.352
C(Precinct)[T.105]                   -45.2387     10.799     -4.189      0.000     -66.404     -24.073
C(Precinct)[T.106]                   -39.4290     11.044     -3.570      0.000     -61.075     -17.783
C(Precinct)[T.107]                   -50.0375     11.430     -4.378      0.000     -72.439     -27.636
C(Precinct)[T.108]                   -55.4642     12.065     -4.597      0.000     -79.111     -31.818
C(Precinct)[T.109]                   -55.0107     11.848     -4.643      0.000     -78.232     -31.789
C(Precinct)[T.110]                   -54.7623     11.973     -4.574      0.000     -78.229     -31.296
C(Precinct)[T.111]                   -53.4165     11.407     -4.683      0.000     -75.773     -31.060
C(Precinct)[T.112]                   -54.0241     11.968     -4.514      0.000     -77.480     -30.568
C(Precinct)[T.113]                   -37.7885     10.126     -3.732      0.000     -57.635     -17.942
C(Precinct)[T.114]                   -49.6901     10.183     -4.880      0.000     -69.649     -29.731
C(Precinct)[T.115]                   -54.9332     12.049     -4.559      0.000     -78.549     -31.317
C(Precinct)[T.120]                   -31.0793      8.214     -3.784      0.000     -47.179     -14.980
C(Precinct)[T.122]                   -37.7549      8.892     -4.246      0.000     -55.183     -20.327
C(Precinct)[T.123]                   -49.9901     10.280     -4.863      0.000     -70.138     -29.842
lag_Budget_per_capita                -35.8373      5.324     -6.731      0.000     -46.273     -25.402
Violent_Crime_per_capita_lag1          0.0046      0.044      0.106      0.915      -0.081       0.090
Property_Crime_per_capita_lag1        -0.0500      0.036     -1.371      0.170      -0.121       0.021
Budget_per_capita_lag1                 0.5428      0.050     10.924      0.000       0.445       0.640
minority_pct_lag1                     -0.0388      0.021     -1.867      0.062      -0.079       0.002
per_capita_income_lag1                -0.0190      0.024     -0.796      0.426      -0.066       0.028
total_pop_lag1                        -0.0010      0.017     -0.060      0.952      -0.034       0.032
lag_Violent_Crime_per_capita_lag1      0.1644      2.432      0.068      0.946      -4.603       4.932
lag_Property_Crime_per_capita_lag1    -3.7823      1.831     -2.066      0.039      -7.371      -0.193
lag_Budget_per_capita_lag1            19.7627      4.030      4.904      0.000      11.865      27.661
lag_minority_pct_lag1                 -1.0830      0.774     -1.399      0.162      -2.600       0.435
lag_per_capita_income_lag1            -0.5072      0.883     -0.574      0.566      -2.238       1.224
lag_total_pop_lag1                     0.1674      0.847      0.198      0.843      -1.493       1.828
==============================================================================
Omnibus:                      335.725   Durbin-Watson:                   2.237
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            14351.970
Skew:                           0.463   Prob(JB):                         0.00
Kurtosis:                      19.634   Cond. No.                     2.72e+04
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 2.72e+04. This might indicate that there are

strong multicollinearity or other numerical problems.

In [60]:
res = model_twfe_cluster  

def _rename_term(name: str) -> str:
    name = re.sub(r'^C\(Year\)\[T\.(\d+)\]$', r'Year_\1', name)
    name = re.sub(r'^C\(Precinct\)\[T\.([^\]]+)\]$', r'Precinct_\1', name)
    if name == "Intercept":
        name = "const"
    return name

renamed_idx = [_rename_term(s) for s in res.params.index]
params_ren = pd.Series(res.params.values, index=renamed_idx, name="coef")
se_ren     = pd.Series(res.bse.values,     index=renamed_idx, name="se")
t_ren      = pd.Series(res.tvalues.values, index=renamed_idx, name="z")
p_ren      = pd.Series(res.pvalues.values, index=renamed_idx, name="pval")

table = pd.concat([params_ren, se_ren, t_ren, p_ren], axis=1)
table["is_FE"] = table.index.str.startswith(("Year_", "Precinct_"))

preferred_order = [
    "const",
    "lag_Budget_per_capita",
    "Budget_per_capita_lag1",
    "lag_Budget_per_capita_lag1",
    "MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "RAPE_per_capita_lag1",
    "FELONY_ASSAULT_per_capita_lag1",
    "BURGLARY_per_capita_lag1",
    "GRAND_LARCENY_per_capita_lag1",
    "GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "ROBBERY_per_capita_lag1",
    "Violent_Crime_per_capita_lag1",
    "Property_Crime_per_capita_lag1",
    "minority_pct_lag1",
    "per_capita_income_lag1",
    "total_pop_lag1",
    "lag_MURDER_NON_NEGL_MANSLAUGHTER_per_capita_lag1",
    "lag_RAPE_per_capita_lag1",
    "lag_FELONY_ASSAULT_per_capita_lag1",
    "lag_BURGLARY_per_capita_lag1",
    "lag_GRAND_LARCENY_per_capita_lag1",
    "lag_GRAND_LARCENY_OF_MOTOR_VEHICLE_per_capita_lag1",
    "lag_ROBBERY_per_capita_lag1",
    "lag_Violent_Crime_per_capita_lag1",
    "lag_Property_Crime_per_capita_lag1",
    "lag_minority_pct_lag1",
    "lag_per_capita_income_lag1",
    "lag_total_pop_lag1",
]

substantive = table.loc[~table["is_FE"]].drop(columns="is_FE")
present_pref = [v for v in preferred_order if v in substantive.index]
remaining    = [v for v in substantive.index if v not in present_pref]
remaining_sorted = []
if remaining:
    remaining_sorted = (
        substantive.loc[remaining]
                  .assign(_abs=lambda s: s["coef"].abs())
                  .sort_values("_abs", ascending=False)
                  .drop(columns="_abs")
                  .index.tolist()
    )
ordered_index = present_pref + remaining_sorted
clean_table = substantive.loc[ordered_index].round(4)

print("\n=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===")
print(clean_table.to_string())

dw = durbin_watson(res.resid)
print("\n=== Model Fit (robust/clustered) ===")
print(f"Observations: {int(res.nobs)}")
print(f"R-squared / Adj.: {res.rsquared:.3f} / {res.rsquared_adj:.3f}")
if res.fvalue is not None:
    print(f"F-statistic (model): {res.fvalue:.2f}, p-value: {res.f_pvalue:.2g}")
print(f"Log-Likelihood: {res.llf:.1f} | AIC: {res.aic:.1f} | BIC: {res.bic:.1f}")
print(f"Durbin-Watson: {dw:.3f}")
print(f"Covariance Type: {res.cov_type} (groups=Precinct)")

n_year_fe = (table.index.str.startswith("Year_")).sum()
n_prec_fe = (table.index.str.startswith("Precinct_")).sum()
print(f"\n[Note] Hidden fixed effects: {n_year_fe} Year FEs, {n_prec_fe} Precinct FEs.")

def relabel_exog_inplace(res_):
    """
    Overwrite model xnames so summary() prints without C(...).
    Clears caches so Series pick up new names.
    """
    # Try to get current names
    if hasattr(res_.model, "data") and getattr(res_.model.data, "xnames", None):
        xnames = list(res_.model.data.xnames)
    elif hasattr(res_.model, "exog_names") and res_.model.exog_names:
        xnames = list(res_.model.exog_names)
    else:
        return res_

    new_names = [_rename_term(n) for n in xnames]

    # Assign back
    if hasattr(res_.model, "exog_names"):
        res_.model.exog_names = new_names
    if hasattr(res_.model, "data") and hasattr(res_.model.data, "xnames"):
        res_.model.data.xnames = new_names
    if hasattr(res_.model, "xnames"):
        res_.model.xnames = new_names

    # Clear cached Series/tables
    if hasattr(res_, "_cache") and isinstance(res_._cache, dict):
        res_._cache.clear()

    return res_

def print_summary_keep_fe_noC(res_):
    """
    Classic statsmodels summary WITH all FE rows, but labels cleaned:
    C(Year)[T.x] -> Year_x; C(Precinct)[T.y] -> Precinct_y; Intercept -> const
    """
    txt = res_.summary().as_text()
    txt = re.sub(r'C\(Year\)\[T\.([^\]]+)\]', r'Year_\1', txt)
    txt = re.sub(r'C\(Precinct\)\[T\.([^\]]+)\]', r'Precinct_\1', txt)
    txt = txt.replace("Intercept", "const")
    print(txt)

def print_summary_drop_fe_noC(res_):
    """
    Classic statsmodels summary with FE rows REMOVED and labels cleaned.
    """
    txt = res_.summary().as_text()
    txt = re.sub(r'C\(Year\)\[T\.([^\]]+)\]', r'Year_\1', txt)
    txt = re.sub(r'C\(Precinct\)\[T\.([^\]]+)\]', r'Precinct_\1', txt)
    txt = txt.replace("Intercept", "const")
    cleaned_lines = []
    for line in txt.splitlines():
        if re.match(r'^\s*(Year_|Precinct_)', line):
            continue
        cleaned_lines.append(line)
    print("\n".join(cleaned_lines))

=== TWFE with Spillovers — Substantive Coefficients (FE hidden) ===
                                       coef      se        z    pval
const                               29.3907  8.6410   3.4013  0.0007
lag_Budget_per_capita              -35.8373  5.3245  -6.7307  0.0000
Budget_per_capita_lag1               0.5428  0.0497  10.9237  0.0000
lag_Budget_per_capita_lag1          19.7627  4.0296   4.9044  0.0000
Violent_Crime_per_capita_lag1        0.0046  0.0436   0.1062  0.9155
Property_Crime_per_capita_lag1      -0.0500  0.0364  -1.3711  0.1703
minority_pct_lag1                   -0.0388  0.0208  -1.8675  0.0618
per_capita_income_lag1              -0.0190  0.0239  -0.7965  0.4258
total_pop_lag1                      -0.0010  0.0170  -0.0602  0.9520
lag_Violent_Crime_per_capita_lag1    0.1644  2.4323   0.0676  0.9461
lag_Property_Crime_per_capita_lag1  -3.7823  1.8311  -2.0656  0.0389
lag_minority_pct_lag1               -1.0830  0.7743  -1.3987  0.1619
lag_per_capita_income_lag1          -0.5072  0.8833  -0.5742  0.5658
lag_total_pop_lag1                   0.1674  0.8472   0.1976  0.8433

=== Model Fit (robust/clustered) ===
Observations: 1241
R-squared / Adj.: 0.991 / 0.991
F-statistic (model): 126.82, p-value: 6.1e-51
Log-Likelihood: 1191.5 | AIC: -2179.0 | BIC: -1656.4
Durbin-Watson: 2.237
Covariance Type: cluster (groups=Precinct)

[Note] Hidden fixed effects: 16 Year FEs, 72 Precinct FEs.